"""wave/shape — create_directshape: mesh laws, emission, round-trip, the lifter.

The package's discipline is: a refuting test first, then the code. Here it is followed
PARTIALLY, and it is more honest to say so directly than to pretend otherwise: the shape laws and the
emission were written after MEASURING the API on the live compile service (the measurement was
exactly the step that refuted guesses — the four-argument DirectShape.CreateElement
that memory alone would have written does not exist on any of the six versions), while
the lifter tests (LifterReadsBackOrNamesWhy) were written and run BEFORE the lifter and
failed exactly as intended.
"""
from __future__ import annotations

import math
import unittest

from kir import spec
from kir.compiler import compile_program
from kir.mesh import (
    MAX_TRIANGLES, MESH_DEGENERATE, MESH_DISCONNECTED, MESH_DUPLICATE_FACE,
    MESH_INDEX_RANGE, MESH_UNUSED_VERTEX, validate_mesh,
)
from kir.shape_emit import parse_emitted_mesh


# ── samples ──────────────────────────────────────────────────────────────────

def tetra() -> tuple[list, list]:
    return ([[0, 0, 0], [3000, 0, 0], [1500, 2600, 0], [1500, 900, 2400]],
            [[0, 1, 2], [0, 1, 3], [1, 2, 3], [0, 2, 3]])


def twisted_tower(sides=16, storeys=12, r0=6000.0, r1=3500.0,
                  h=36000.0, twist=140.0) -> tuple[list, list]:
    """A twisted tower generated by mathematics (see artifacts/twisted_tower.py)."""
    verts, tris = [], []
    for k in range(storeys + 1):
        f = k / storeys
        r = r0 + (r1 - r0) * f
        a0 = math.radians(twist * f)
        for j in range(sides):
            a = a0 + 2 * math.pi * j / sides
            verts.append([r * math.cos(a), r * math.sin(a), h * f])
    for k in range(storeys):
        for j in range(sides):
            a, b = k * sides + j, k * sides + (j + 1) % sides
            c, d = (k + 1) * sides + j, (k + 1) * sides + (j + 1) % sides
            tris += [[a, b, d], [a, d, c]]
    bot = len(verts); verts.append([0.0, 0.0, 0.0])
    top = len(verts); verts.append([0.0, 0.0, h])
    for j in range(sides):
        tris.append([bot, (j + 1) % sides, j])
        tris.append([top, storeys * sides + j,
                     storeys * sides + (j + 1) % sides])
    return verts, tris


def _prog(verts, tris, category="generic_model", name="меш", oid="D1"):
    return {"ir_version": "1.0", "intent": "t",
            "ops": [{"op": "create_directshape", "id": oid,
                     "mesh": {"vertices_mm": verts, "triangles": tris},
                     "category": category, "name": name}]}


def _codes(mesh, **contract) -> list:
    """The law's verdict. `contract` is passed into `validate_mesh` as-is: the caller's
    contract is part of the subject, not a detail of the helper."""
    diags: list = []
    out = validate_mesh(mesh, "D1", "mesh", diags, **contract)
    return [out, [d.code for d in diags]]


def _diags(mesh, **contract) -> list:
    diags: list = []
    validate_mesh(mesh, "D1", "mesh", diags, **contract)
    return diags


def склеенные_тела() -> dict:
    """A SEAM BUILT BY PROD CODE, NOT BY HAND.

    Two `extrude` calls stacked on each other are exactly what our own decompile step
    does — «combined multiple geometry parts through their exact Gm fallbacks»:
    the same plane arrives twice, each time facing OUT of its OWN solid, i.e. with
    opposing winding. A hand-written fixture would be guarding itself here: it
    reproduces the shape the test's author invented, not the one the
    product produces.
    """
    from kir.mesh import extrude
    низ = extrude([[0, 0], [1000, 0], [1000, 1000], [0, 1000]], 1000,
                  base_z_mm=0)
    верх = extrude([[0, 0], [1000, 0], [1000, 1000], [0, 1000]], 1000,
                   base_z_mm=1000)
    сдвиг = len(низ["vertices_mm"])
    return {"vertices_mm": низ["vertices_mm"] + верх["vertices_mm"],
            "triangles": низ["triangles"]
                         + [[i + сдвиг for i in t] for t in верх["triangles"]]}


# ── shape laws: every refusal is NAMED, the input is not silently patched ────────────────

class MeshLawsRefuseByName(unittest.TestCase):

    def test_valid_mesh_passes_unchanged(self):
        v, t = tetra()
        out, codes = _codes({"vertices_mm": v, "triangles": t})
        self.assertEqual(codes, [])
        self.assertEqual(out["triangles"], t)
        self.assertEqual(len(out["vertices_mm"]), 4)

    def test_index_out_of_range_is_named_not_clamped(self):
        v, t = tetra()
        out, codes = _codes({"vertices_mm": v, "triangles": t + [[0, 1, 99]]})
        self.assertIsNone(out)
        self.assertEqual(codes, [MESH_INDEX_RANGE])

    def test_repeated_index_is_degenerate(self):
        v, _ = tetra()
        out, codes = _codes({"vertices_mm": v, "triangles": [[0, 1, 1]]})
        self.assertIsNone(out)
        self.assertEqual(codes, [MESH_DEGENERATE])

    def test_collinear_triangle_is_degenerate(self):
        # long edges, zero area — caught by area, not by the edge
        out, codes = _codes({"vertices_mm": [[0, 0, 0], [1000, 0, 0],
                                             [2000, 0, 0]],
                             "triangles": [[0, 1, 2]]})
        self.assertIsNone(out)
        self.assertEqual(codes, [MESH_DEGENERATE])

    def test_short_edge_is_degenerate(self):
        out, codes = _codes({"vertices_mm": [[0, 0, 0], [0.2, 0, 0],
                                             [0, 1000, 0]],
                             "triangles": [[0, 1, 2]]})
        self.assertIsNone(out)
        self.assertEqual(codes, [MESH_DEGENERATE])

    # 🔴 THERE USED TO BE ONE TEST HERE, `test_duplicate_face_is_named`, AND IT CODIFIED
    # THE WRONG LAW. It added to the tetrahedron `[2, 1, 0]` — the REVERSED winding of
    # face `[0, 1, 2]` — and demanded `KIR-M005`, calling this a "duplicated
    # face". A corpus measurement on 02.09.2026 showed that among such pairs in geometry read
    # from Revit, 78 of 78 are a SEAM from gluing two closed
    # solids together, i.e. a normal shape, not corruption. The earlier test was not deleted or
    # silently rewritten: it is split into TWO with named subjects, because
    # what gets overturned is NAMED as wrong, not erased.
    #
    # The argument for why resolution follows the observational path while the prohibition follows
    # the author's, lives in the header of mesh.py, section "ABOUT THE SEAM", together with the
    # offline authority (`TessellatedShapeBuilder.AddFace` does not document such an exception,
    # but there is `TessellatedBuildIssueType.EdgeTwiceUsedByFace` and a remedy at
    # assembly time).

    def test_duplicate_face_is_named(self):
        """The AUTHOR'S contract: an opposing pair is a refusal, and it is named a SEAM.

        This is the same input as the earlier test's, and its verdict is the SAME. What changed
        is exactly one thing: the refusal no longer lies about the kind. A single DirectShape is built
        from one connected set of faces, and an author who described the same plane
        twice has glued two solids together — and that is what they are told.
        """
        v, t = tetra()
        out, codes = _codes({"vertices_mm": v, "triangles": t + [[2, 1, 0]]})
        self.assertIsNone(out)
        self.assertEqual(codes, [MESH_DUPLICATE_FACE])
        diag = _diags({"vertices_mm": v, "triangles": t + [[2, 1, 0]]})[0]
        self.assertEqual(diag.got["род"], "шов", diag.message_ru)
        self.assertIn("ВСТРЕЧНАЯ", diag.message_ru)

    def test_the_same_reverse_wound_face_is_ACCEPTED_when_observed(self):
        """The OBSERVATIONAL contract: the SAME input must pass.

        The profile of a foreign document has no right to be stricter than the registry: everything
        that Revit creates legally must be readable (form 49). Without this
        test the split would have been declared, not built.
        """
        v, t = tetra()
        out, codes = _codes({"vertices_mm": v, "triangles": t + [[2, 1, 0]]},
                            allow_seam_faces=True)
        self.assertEqual(codes, [], "шов отвергнут на наблюдательном пути")
        self.assertIsNotNone(out)

    def test_a_duplicate_face_is_caught_through_twin_vertices(self):
        """🔴 A DUPLICATED FACE IS A PROPERTY OF POINTS, NOT OF VERTEX NUMBERS.

        Soup export gives each face ITS OWN vertices, so one and the same
        physical face arrives twice under DIFFERENT numbers. A guard that
        compared raw numbers accepted such a pair, while the very same input,
        recorded with shared numbers, rejected it — two answers to one question about
        GEOMETRY. The merge that knows geometric identity lives in
        the same file and was applied one line below, for connectivity — that knowledge
        never reached the duplicate guard.

        The second outcome (that the guard does not call every pair duplicated) is held by
        `test_triangle_soup_is_connected_geometrically`: it has TWELVE
        twin vertices and not a single repeated face.
        """
        A, B, C = [0., 0., 0.], [1000., 0., 0.], [0., 1000., 0.]
        out, codes = _codes({"vertices_mm": [A, B, C, A, B, C],
                             "triangles": [[0, 1, 2], [3, 4, 5]]})
        self.assertIsNone(
            out, "та же грань, описанная через вершины-двойники, ПРИНЯТА")
        self.assertEqual(codes, [MESH_DUPLICATE_FACE])

    def test_unused_vertex_is_named_not_dropped(self):
        v, t = tetra()
        out, codes = _codes({"vertices_mm": v + [[9000, 9000, 9000]],
                             "triangles": t})
        self.assertIsNone(out)
        self.assertEqual(codes, [MESH_UNUSED_VERTEX])

    def test_disconnected_mesh_is_named_with_component_count(self):
        v, t = tetra()
        far = [[p[0] + 500_000, p[1], p[2]] for p in v]
        out, codes = _codes({
            "vertices_mm": v + far,
            "triangles": t + [[i + 4 for i in tri] for tri in t]})
        self.assertIsNone(out)
        self.assertEqual(codes, [MESH_DISCONNECTED])

    def test_triangle_soup_is_connected_geometrically(self):
        """Each face with its own vertices — by index, 4 pieces, physically
        one. Refusing such an input would mean refusing the most ordinary
        export; connectivity is computed from coordinate coincidence."""
        v, t = tetra()
        soup_v, soup_t = [], []
        for tri in t:
            base = len(soup_v)
            soup_v += [list(v[i]) for i in tri]
            soup_t.append([base, base + 1, base + 2])
        out, codes = _codes({"vertices_mm": soup_v, "triangles": soup_t})
        self.assertEqual(codes, [])
        self.assertIsNotNone(out)

    def test_over_the_measured_ceiling_is_refused(self):
        v, t = tetra()
        out, codes = _codes({"vertices_mm": v,
                             "triangles": t * (MAX_TRIANGLES // 4 + 1)})
        self.assertIsNone(out)
        self.assertTrue(codes)

    def test_non_finite_coordinate_is_refused(self):
        v, t = tetra()
        bad = [list(p) for p in v]
        bad[0][2] = float("inf")
        out, codes = _codes({"vertices_mm": bad, "triangles": t})
        self.assertIsNone(out)
        self.assertTrue(codes)

    def test_extra_field_is_refused(self):
        v, t = tetra()
        out, codes = _codes({"vertices_mm": v, "triangles": t, "colour": "red"})
        self.assertIsNone(out)
        self.assertTrue(codes)


class ШовПротивДубля(unittest.TestCase):
    """🔴 TWO FACES ON THE SAME POINTS — TWO DIFFERENT KINDS, DISTINGUISHED BY WINDING.

    Before 02.09.2026 the face key was taken as `tuple(sorted(...))`, which DISCARDED the winding
    before comparison — in that sorting the two subjects merged into one. The distinguisher
    here is a PROPERTY OF THE VALUE ("opposing winding on matching points"), not
    the place the value came from: what must be asked is the property, not the appearance of
    the first case (form 54). The caller's contract decides exactly one thing —
    whether a SEAM is tolerated; a true DUPLICATE is red on both paths.
    """

    def test_a_seam_is_accepted_on_the_observed_contract(self):
        """Two glued solids are read. That is exactly the corpus's 42 elements."""
        out, codes = _codes(склеенные_тела(), allow_seam_faces=True)
        self.assertEqual(codes, [], "склейка двух тел отвергнута при чтении")
        self.assertIsNotNone(out)

    def test_the_same_seam_is_refused_on_the_authored_contract(self):
        """🔴 THE STRICTNESS OF THE AUTHOR'S PATH IS PRESERVED — otherwise the split would be
        not a split but a repeal of the law."""
        diags = _diags(склеенные_тела())
        self.assertEqual([d.code for d in diags], [MESH_DUPLICATE_FACE])
        self.assertEqual(diags[0].got["род"], "шов")

    def test_a_same_wound_double_is_refused_on_BOTH_contracts(self):
        """🔴 A REAL DEFECT MUST STAY CAUGHT. This is a verbatim repro
        of the twin-vertices finding: A,B,C,A,B,C with a SINGLE winding. In the corpus
        (1137 meshes) this has never once occurred, and that is exactly why it
        cannot be permitted along with the seam."""
        A, B, C = [0., 0., 0.], [1000., 0., 0.], [0., 1000., 0.]
        дубль = {"vertices_mm": [A, B, C, A, B, C],
                 "triangles": [[0, 1, 2], [3, 4, 5]]}
        for контракт in ({}, {"allow_seam_faces": True}):
            with self.subTest(контракт=контракт or "авторский"):
                diags = _diags(дубль, **контракт)
                self.assertEqual([d.code for d in diags], [MESH_DUPLICATE_FACE])
                self.assertEqual(diags[0].got["род"], "дубль",
                                 diags[0].message_ru)

    def test_a_mesh_carrying_BOTH_kinds_is_refused_as_the_double(self):
        """A mesh with both kinds at once: the seam passes, the duplicate is caught BY NAME.

        Without this case the split would rest on inputs where there is exactly
        one kind, and "we accept the seam" would be indistinguishable from "we stopped looking".
        """
        оба = склеенные_тела()
        оба["triangles"] = оба["triangles"] + [list(оба["triangles"][0])]
        diags = _diags(оба, allow_seam_faces=True)
        self.assertEqual([d.code for d in diags], [MESH_DUPLICATE_FACE])
        self.assertEqual(diags[0].got["род"], "дубль", diags[0].message_ru)
        # while on the author's contract the SEAM is the first to go red — it comes earlier in the traversal
        self.assertEqual(_diags(оба)[0].got["род"], "шов")

    def test_the_authored_constructors_never_produce_a_seam(self):
        """🔴 A SECOND OUTCOME for strictness: if `extrude`/`sweep` produced
        a seam themselves, the prohibition on the author's path would break the product's own output.
        This is verified by execution, not by argument."""
        from kir.mesh import extrude, sweep
        случаи = {
            "коробка": lambda: extrude([[0, 0], [6000, 0], [6000, 4000],
                                        [0, 4000]], 3000),
            "коробка с дырой": lambda: extrude(
                {"outer": [[0, 0], [10000, 0], [10000, 8000], [0, 8000]],
                 "holes": [[[2000, 2000], [4000, 2000], [4000, 4000],
                            [2000, 4000]]]}, 3000),
            "поручень": lambda: sweep([[-30, -20], [30, -20], [30, 20],
                                       [-30, 20]],
                                      [[0, 0, 0], [4000, 0, 0], [4000, 0, 3000]]),
        }
        for имя, построить in случаи.items():
            with self.subTest(случай=имя):
                тело = построить()          # strict contract inside
                self.assertEqual(_codes(тело)[1], [], имя)

    def test_the_observed_door_actually_passes_the_contract(self):
        """🔴 WIRING: the substitution goes WHERE DISPATCH ACTUALLY LOOKS, PLUS A COUNTER.

        `materialize` holds the name `validate_mesh` in ITS OWN namespace
        (`from kir.mesh import validate_mesh` at module level), so what must be patched
        is that name, not `kir.mesh.validate_mesh` — otherwise the substitution reaches
        nowhere and green means nothing. The counter proves that
        the call ACTUALLY HAPPENED, not that it did not.

        Without this test the split could live in the law and not be
        wired to the door — fixed code can be unreachable (form 53).
        """
        from kir.decompile import materialize as M
        from kir.decompile.geom_extract import (
            ExtractedGeometryTier, GeometryIndexRecord)
        from kir.decompile.recompile import GmMesh
        шов = склеенные_тела()
        mesh = GmMesh(
            vertices_mm=tuple(tuple(p) for p in шов["vertices_mm"]),
            triangles=tuple(tuple(t) for t in шов["triangles"]))

        class _Геометрия:
            def world_fallback_mesh_for_record(self, record):
                return mesh

        запись = GeometryIndexRecord(
            element_id="12345", category="OST_Stairs",
            tier=ExtractedGeometryTier.GM, geo_hash="de" * 32,
            transform=(1., 0., 0., 0., 0., 1., 0., 0.,
                       0., 0., 1., 0., 0., 0., 0., 1.))
        лист = {"_id": "n1", "source_element_id": "12345", "kind": "atom",
                "category": "OST_Stairs", "type_name": "T",
                "level_name": None, "anchor_mm": None}
        видено: list = []
        настоящий = M.validate_mesh

        def шпион(*args, **kwargs):
            видено.append(dict(kwargs))
            return настоящий(*args, **kwargs)

        M.validate_mesh = шпион
        try:
            op, кандидат, пропуск = M._atom_escrow_op(
                лист, _Геометрия(), запись, None)
        finally:
            M.validate_mesh = настоящий
        self.assertEqual(len(видено), 1, "закон не был позван ВООБЩЕ")
        self.assertEqual(видено[0], {"allow_seam_faces": True},
                         "дверь разбора зовёт закон авторским контрактом")
        self.assertIsNone(пропуск, getattr(пропуск, "reason", None))
        self.assertIsNotNone(кандидат)
        self.assertEqual(op["op"], "create_directshape")


class СклейкаСвариваетЦЕПОЧКУ(unittest.TestCase):
    """🔴 MERGING FOR CONNECTIVITY IS A RELATION, NOT A ROLL-CALL AGAINST A REPRESENTATIVE.

    Tolerance is not an equivalence relation: A and B are closer than the tolerance, B and C
    are closer than the tolerance, but A and C are not. The answer must therefore be a CLOSURE, and
    then it is unique; comparing only against the FIRST item that lands in a cell gave an answer
    that depended on vertex order, and broke the chain in the middle. The cost was
    the KIR-M006 refusal «меш распадается» on a LEGAL input, i.e. the worst
    kind of error: not letting an invalid input through, but refusing a valid one.
    """

    #: A and C are 0.18 mm apart at a tolerance of 0.1 — connected only through B.
    ЦЕПОЧКА = [[0., 0., 0.], [0.09, 0., 0.], [0.18, 0., 0.]]

    @staticmethod
    def _разбиение(weld, порядок):
        """Merge classes as a set of sets of ORIGINAL vertex numbers."""
        groups: dict = {}
        for позиция, w in enumerate(weld):
            groups.setdefault(w, set()).add(порядок[позиция])
        return frozenset(frozenset(g) for g in groups.values())

    def test_a_chain_connected_by_tolerance_welds_into_one_point(self):
        from kir.mesh import _WELD_TOL_MM, _weld_map
        weld = _weld_map(self.ЦЕПОЧКА)
        self.assertEqual(
            len(set(weld)), 1,
            f"цепочка с шагом 0.09 мм при допуске {_WELD_TOL_MM} мм дала "
            f"{len(set(weld))} точек вместо одной: {weld}")

    def test_the_weld_does_not_depend_on_the_order_of_the_vertices(self):
        """Vertex order is not a property of geometry. An answer that depends on it
        is wrong in one of two directions, and which one is never stated anywhere."""
        from kir.mesh import _weld_map
        n = len(self.ЦЕПОЧКА)
        прямо = self._разбиение(_weld_map(self.ЦЕПОЧКА), list(range(n)))
        назад = self._разбиение(_weld_map(list(reversed(self.ЦЕПОЧКА))),
                                list(reversed(range(n))))
        self.assertEqual(прямо, назад,
                         f"вперёд {sorted(map(sorted, прямо))}, "
                         f"назад {sorted(map(sorted, назад))}")

    def test_without_the_middle_point_the_ends_stay_apart(self):
        """🔴 THE SECOND OUTCOME. Without it, a "weld everything" fix would pass both
        checks above: 0.18 mm at a tolerance of 0.1 are TWO points, and they must
        remain two."""
        from kir.mesh import _weld_map
        weld = _weld_map([[0., 0., 0.], [0.18, 0., 0.]])
        self.assertEqual(len(set(weld)), 2, f"склейка дала {weld}")

    def test_a_mesh_bridged_only_by_the_chain_is_accepted(self):
        """The same law through the PRODUCT, not through a helper: three faces whose
        only bridge is a tolerance chain. Today such a mesh gets
        KIR-M006 on a valid input."""
        verts = [[0., 0., 0.], [0., 100., 0.], [-100., 0., 0.],
                 [0.09, 0., 0.], [0.09, -100., 0.], [109., -100., 0.],
                 [0.18, 0., 0.], [0.18, 200., 0.], [200.18, 200., 0.]]
        out, codes = _codes({"vertices_mm": verts,
                             "triangles": [[0, 1, 2], [3, 4, 5], [6, 7, 8]]})
        self.assertEqual(codes, [], "законный связный меш отвергнут")
        self.assertIsNotNone(out)


# ── the operation as a whole ────────────────────────────────────────────────────────

class OpRefusesToImpersonate(unittest.TestCase):

    def test_wall_category_is_not_offered(self):
        """A mesh in the wall category reads as a wall in every spec, without
        being anything a wall actually is. The category is not in the enumeration."""
        choices = {p.name: p.choices for p in
                   spec.OPS["create_directshape"].params}["category"]
        for impersonation in ("walls", "floors", "roofs", "columns",
                              "structural_framing", "ceilings", "stairs"):
            self.assertNotIn(impersonation, choices)

    def test_wall_category_is_a_typed_refusal_not_a_crash(self):
        v, t = tetra()
        out = compile_program(_prog(v, t, category="walls"),
                              revit_version="2023", snapshot={"levels": []})
        self.assertFalse(out.ok)
        self.assertTrue(out.diagnostics)

    def test_op_declares_geometry_not_element(self):
        op = spec.OPS["create_directshape"]
        self.assertEqual(op.capability, (("create", "geometry"),))

    def test_op_grounds_nothing_because_there_is_no_type(self):
        self.assertEqual(spec.OPS["create_directshape"].grounded, ())

    def test_name_is_required(self):
        v, t = tetra()
        prog = _prog(v, t)
        del prog["ops"][0]["name"]
        out = compile_program(prog, revit_version="2023",
                              snapshot={"levels": []})
        self.assertFalse(out.ok)


class EmissionSaysWhatItBuilt(unittest.TestCase):

    def test_compiles_on_all_six_versions_offline(self):
        v, t = tetra()
        for ver in spec.REVIT_VERSIONS:
            with self.subTest(ver=ver):
                out = compile_program(_prog(v, t), revit_version=ver,
                                      snapshot={"levels": []})
                self.assertTrue(out.ok, [d.message_ru for d in out.diagnostics])

    def test_measured_api_names_are_the_ones_emitted(self):
        v, t = tetra()
        cs = compile_program(_prog(v, t), revit_version="2026",
                             snapshot={"levels": []}).csharp
        self.assertIn("DirectShape.CreateElement(doc, __cat_D1)", cs)
        self.assertIn("new TessellatedFace(", cs)
        # THE ONLY pair, of the supported ones, that yields a mesh. RevitAPI.xml
        # (the note on TessellatedShapeBuilder.Build, identical in 2021 and
        # 2026): only Solid/Abort, AnyGeometry/Mesh, and
        # Mesh/Salvage are supported. Mesh/Abort compiles 6/6 and is NOT supported — this
        # test stands here so that no one "fixes" Salvage back to Abort
        # by the same straightforward reasoning that picked it in the first place.
        self.assertIn("TessellatedShapeBuilderTarget.Mesh", cs)
        self.assertIn("TessellatedShapeBuilderFallback.Salvage", cs)
        self.assertNotIn("TessellatedShapeBuilderFallback.Abort", cs)
        # the four-argument overload does not exist on any version
        self.assertNotIn('CreateElement(doc, __cat_D1, "', cs)

    def test_salvage_silence_is_closed_by_the_triangle_witness(self):
        """Salvage stays silent about discarded faces; the only thing that makes
        this loud is comparing the face count against the BUILT element. If the
        witness disappears, silent truncation will return."""
        v, t = tetra()
        cs = compile_program(_prog(v, t), revit_version="2023",
                             snapshot={"levels": []}).csharp
        self.assertIn("NumTriangles", cs)
        self.assertIn(f"!= {len(t)}", cs)

    def test_receipt_carries_the_honest_label(self):
        v, t = tetra()
        cs = compile_program(_prog(v, t), revit_version="2023",
                             snapshot={"levels": []}).csharp
        for field in ("bim_semantics", "has_type",
                      "schedulable_as_building_element", "human_editable",
                      "honest_label_written", "warning"):
            self.assertIn(field, cs)
        self.assertIn("геометрия без BIM-смысла", cs)

    def test_witness_reads_the_result_not_the_call(self):
        v, t = tetra()
        cs = compile_program(_prog(v, t), revit_version="2023",
                             snapshot={"levels": []}).csharp
        # the bounding box and face count are read back FROM THE ELEMENT
        self.assertIn("get_BoundingBox(null)", cs)
        self.assertIn("NumTriangles", cs)
        self.assertIn("get_Geometry(new Options())", cs)

    def test_z_extent_is_witnessed_too(self):
        """A witness must sign only the axis it actually read. For a mesh, Z is a
        full-fledged input coordinate, and an XY witness for floors would here be
        signing geometry it never looked at."""
        v, t = tetra()
        cs = compile_program(_prog(v, t), revit_version="2023",
                             snapshot={"levels": []}).csharp
        self.assertIn("Min.Z", cs)
        self.assertIn("Max.Z", cs)

    def test_post_declared_variables_survive_per_op_scope(self):
        v, t = tetra()
        for isolation in ("atomic", "per_op"):
            with self.subTest(isolation=isolation):
                out = compile_program(_prog(v, t), revit_version="2024",
                                      snapshot={"levels": []},
                                      isolation=isolation)
                self.assertTrue(out.ok)
                # both variables are declared BEFORE the creation block
                head = out.csharp.split("using (Transaction")[0]
                self.assertIn("DirectShape __el_D1 = null;", head)
                self.assertIn("bool __lbl_D1 = false;", head)


class RoundTripThroughTheArtefact(unittest.TestCase):
    """Mesh -> op -> emission -> DECOMPILE OF THE EMITTED C# -> the same mesh.

    The comparison closes on the text that will actually go to Revit, not on the
    Python structure we generated it from in the first place: otherwise the test would be
    checking a variable against itself.
    """

    def _roundtrip(self, verts, tris, tol=0.01):
        out = compile_program(_prog(verts, tris), revit_version="2026",
                              snapshot={"levels": []})
        self.assertTrue(out.ok)
        back = parse_emitted_mesh(out.csharp, "D1")
        self.assertEqual(back["triangles"], tris)
        self.assertEqual(len(back["vertices_mm"]), len(verts))
        worst = 0.0
        for a, b in zip(verts, back["vertices_mm"]):
            for ca, cb in zip(a, b):
                worst = max(worst, abs(float(ca) - float(cb)))
        self.assertLessEqual(worst, tol)
        return worst

    def test_tetra_roundtrips_within_named_tolerance(self):
        v, t = tetra()
        self.assertLessEqual(self._roundtrip(v, t), 0.01)

    def test_twisted_tower_roundtrips_within_named_tolerance(self):
        """The 0.01 mm tolerance is exactly the rounding of a coordinate to two decimal
        places at emission, and nothing beyond that. It is named by a number, not by "approximately"."""
        v, t = twisted_tower()
        self.assertLessEqual(self._roundtrip(v, t), 0.01)

    def test_triangle_indices_survive_exactly(self):
        v, t = twisted_tower()
        out = compile_program(_prog(v, t), revit_version="2021",
                              snapshot={"levels": []})
        back = parse_emitted_mesh(out.csharp, "D1")
        self.assertEqual(back["triangles"], t)


# ── the SURFACE witness (09.08.2026) ───────────────────────────────────────

def _flat_grid(n: int = 2, step: float = 1000.0) -> tuple[list, list]:
    """A flat n×n grid of squares: it has INTERIOR vertices.

    It is precisely an interior vertex that sets the new witness apart from the two earlier ones: it
    can be moved anywhere without touching either the bounding box (held by the corners) or
    the face count.
    """
    w = n + 1
    verts = [[i * step, j * step, 0.0] for i in range(w) for j in range(w)]
    tris = []
    for i in range(n):
        for j in range(n):
            a, b = i * w + j, i * w + j + 1
            c, d = (i + 1) * w + j, (i + 1) * w + j + 1
            tris += [[a, b, c], [b, d, c]]
    return verts, tris


def _expected_payload(verts, tris) -> str:
    """The preimage the witness must demand — via the same canonicalizer."""
    from kir.decompile.geometry_acceptance import mesh_surface_payload
    from kir.decompile.recompile import GmMesh
    from kir.shape_emit import _emitted_vertices

    emitted = _emitted_vertices(verts)
    return mesh_surface_payload(GmMesh(
        vertices_mm=tuple(tuple(v) for v in emitted),
        triangles=tuple(tuple(t) for t in tris)))


class SurfaceWitnessIsTheExactPredicate(unittest.TestCase):
    """The face count closes Salvage's silence only halfway.

    A reassembly that preserved the face COUNT while shifting a vertex passed both
    the bounding box and the counter — and from the outside that is a success. The exact predicate had
    existed since the first day of Tier-G (`mesh_surface_payload`), but the author's branch never
    called it through a single import. The tests below hold both ends: that the predicate is
    the right one, and that it can REFUSE.
    """

    def test_the_emitter_uses_the_tier_g_canonicaliser_itself(self):
        """Not "the same kind" but THE SAME: the expectation in C# is a byte-for-byte preimage
        of `mesh_surface_payload`, whose SHA-256 is exactly `mesh_surface_digest`."""
        import hashlib

        from kir.decompile.geometry_acceptance import (
            mesh_surface_digest, mesh_surface_payload)
        from kir.decompile.recompile import GmMesh
        from kir.emit_utils import cs_string_literal
        from kir.shape_emit import _emitted_vertices

        v, t = tetra()
        cs = compile_program(_prog(v, t), revit_version="2026",
                             snapshot={"levels": []}).csharp
        self.assertIn(cs_string_literal(_expected_payload(v, t)), cs)
        gm = GmMesh(
            vertices_mm=tuple(tuple(x) for x in _emitted_vertices(v)),
            triangles=tuple(tuple(x) for x in t))
        self.assertEqual(
            hashlib.sha256(mesh_surface_payload(gm).encode("utf-8")).hexdigest(),
            mesh_surface_digest(gm))

    def test_the_expectation_is_taken_from_the_EMITTED_vertices(self):
        """The expectation must be computed from the vertices that will actually be sent out.

        A coordinate that lands closer than 0.005 mm to a canon cell boundary changes
        cells when rounded to hundredths. An expectation computed from the RAW
        input would demand from Revit a cell that no one ever sent it —
        a false refusal on a correctly built mesh.
        """
        from kir.decompile.geometry_acceptance import mesh_surface_payload
        from kir.decompile.recompile import GmMesh
        from kir.emit_utils import cs_string_literal

        # 🔴 THE NUMBER WAS RE-DERIVED BY MEASUREMENT ON 21.08.2026, AND IT IS NOW STRONGER.
        # This used to be 1000.2451 with the argument "in C# it will come out as 1000.25 -> cell 2001,
        # raw -> 2000". The argument was correct as long as `_emitted_vertices` consisted of
        # ONE stage — printing with `_EMITTED_DECIMALS`. On 20.08 a second stage was added,
        # `_as_revit_stores`: Revit stores mesh vertices in SINGLE
        # precision, and 1000.25 comes back as 1000.2499923706055. The cell
        # on both sides became 2000, the premise stopped holding, and the test
        # went red from that day on ON ITS OWN PREMISE, not on the subject.
        #
        # 1000.2501 keeps the discrepancy AFTER both stages:
        #     raw       1000.2501            -> cell 2001
        #     emission  1000.2499923706055   -> cell 2000
        # and it requires BOTH: remove `_as_revit_stores` — the emission becomes 1000.25,
        # cell 2001, and the premise fails again. The old number checked
        # only the first stage; this one checks the whole chain.
        v, t = tetra()
        v = [list(p) for p in v]
        v[1][0] = 1000.2501
        raw = mesh_surface_payload(GmMesh(
            vertices_mm=tuple(tuple(x) for x in v),
            triangles=tuple(tuple(x) for x in t)))
        emitted = _expected_payload(v, t)
        self.assertNotEqual(raw, emitted, "предпосылка теста: ячейки разошлись")
        cs = compile_program(_prog(v, t), revit_version="2026",
                             snapshot={"levels": []}).csharp
        self.assertIn(cs_string_literal(emitted), cs)
        self.assertNotIn(cs_string_literal(raw), cs)

    def test_a_relocated_interior_vertex_is_invisible_to_the_older_witnesses(self):
        """The exact case the witness was written for.

        The bounding box is held by the corners, the face count does not change — both earlier witnesses
        STAY SILENT. The surface preimage changes.
        """
        from kir.mesh import mesh_bbox

        v, t = _flat_grid(2)
        moved = [list(p) for p in v]
        moved[4][0] += 400.0                     # interior vertex
        tol = spec.OPS["create_directshape"].tolerances["bbox_mm"]
        self.assertFalse(
            any(abs(a - b) > tol
                for a, b in zip(mesh_bbox(v), mesh_bbox(moved))),
            "габарит обязан остаться в допуске — иначе тест не о том")
        # The face count is equal BY CONSTRUCTION: both meshes share ONE AND THE
        # SAME list `t`. The old `len(t) == len(t)` proved the silence of the
        # face-count witness by the absence of a competitor — that is, it
        # proved nothing. What must be asserted here is the test's premise:
        # the vertex ACTUALLY moved, otherwise the silence is trivial.
        self.assertNotEqual(v, moved,
                            "вершина не сдвинулась — тест не о том")
        self.assertNotEqual(_expected_payload(v, t),
                            _expected_payload(moved, t))

    def test_the_canon_grid_is_the_tolerance_and_it_is_derived(self):
        """The tolerance is the grid step, and it is NOT derived here.

        `surface_canon_mm` must equal `GEOM_CANON_MM` — the frozen
        Tier-G grid that the content-addressed geometry store and the live
        post-commit rig predicate already stand on. Should they drift apart, the
        witness would be comparing two different canons without saying so.
        """
        from kir.decompile.schema import GEOM_CANON_MM

        self.assertEqual(
            spec.OPS["create_directshape"].tolerances["surface_canon_mm"],
            GEOM_CANON_MM)

    def test_mutation_above_the_grid_fires_and_below_it_does_not(self):
        """The detectability boundary, both sides, IN NUMBERS.

        The canon cell is exactly `GEOM_CANON_MM` wide; the coordinate 1000.0 mm is
        its center. From this, without inventing anything: a shift ≥ the step ALWAYS changes
        the cell number, a shift < half the step from the center NEVER changes it.

        🔴 EXACTLY HALF A STEP WAS REMOVED FROM THE LAW ON 21.08.2026, AND THIS IS A REFINEMENT,
        NOT A WEAKENING. This used to be `(GEOM_CANON_MM / 2.0, True)` with a
        caption of "exactly the cell edge". The edge is a TIE, and the tie's outcome is decided
        not by the grid but by the storage model: Revit stores mesh vertices in single
        precision (`shape_emit._as_revit_stores`, measured live on 20.08), and
        1000.25 comes back as 1000.2499923706055 — i.e. it falls BELOW
        the edge. A measurement of both sides (21.08):

            +0.50 -> 2001 FIRED         +0.26 -> 2001 FIRED
            +0.25 -> 2000 silent        +0.24 -> 2000 silent
            -0.25 -> 2000 silent        -0.26 -> 1999 FIRED

        The law that holds is about the STRICT sides: more than half fires,
        less than half stays silent. The tie is named as a separate
        assertion below, BY MEASUREMENT, not declared as a law: declaring it a
        law would mean demanding of the instrument a behavior it does not
        have, and the very first test at a different coordinate would refute it.
        """
        from kir.decompile.schema import GEOM_CANON_MM

        v, t = tetra()
        v = [list(p) for p in v]
        v[1] = [1000.0, 0.0, 0.0]        # the cell center on all three axes
        base = _expected_payload(v, t)
        for delta, must_fire in (
            (GEOM_CANON_MM, True),               # 0.5 — the grid step
            (0.26, True),                        # slightly MORE than half
            (0.24, False),
            (0.2, False),
            (-0.2, False),
            (-0.24, False),
            (-0.26, True),                       # and in the other direction
            (5.0, True),                         # the bounding-box tolerance — and it stays silent
        ):
            with self.subTest(delta=delta):
                moved = [list(p) for p in v]
                moved[1][0] += delta
                fired = _expected_payload(moved, t) != base
                self.assertEqual(must_fire, fired)

    def test_exactly_half_a_step_is_a_TIE_and_the_storage_model_decides(self):
        """A tie at the cell edge. What is asserted is a MEASUREMENT, not a law.

        A shift of exactly `GEOM_CANON_MM / 2` places the coordinate on the boundary between two
        cells. From there it is not the grid that decides but the value's path: printing with
        `_EMITTED_DECIMALS`, then Revit's single-precision storage. At
        1000.0 both halves fall BELOW the edge and the witness stays silent.

        This test does not declare the silence correct — it PINS it down. If
        the storage model ever changes, it will go red and demand
        remeasurement, rather than silently changing the meaning of the neighboring law.
        """
        from kir.decompile.schema import GEOM_CANON_MM

        v, t = tetra()
        v = [list(p) for p in v]
        v[1] = [1000.0, 0.0, 0.0]
        base = _expected_payload(v, t)
        for delta in (GEOM_CANON_MM / 2.0, -GEOM_CANON_MM / 2.0):
            with self.subTest(delta=delta):
                moved = [list(p) for p in v]
                moved[1][0] += delta
                self.assertEqual(
                    base, _expected_payload(moved, t),
                    "ничья на краю ячейки перестала молчать — модель "
                    "хранения сменилась, перемерь обе стороны закона выше")

    def test_the_witness_is_constructible_only_with_a_verdict(self):
        """The surface witness must be in the obligations registry and
        discharge by KEY, not by substring."""
        from kir.translation_cert import (
            _ensure_table, audit_registry_coverage)

        spec_row = _ensure_table()["create_directshape"]
        self.assertEqual("model", spec_row.witness_source)
        self.assertIn("surface", {o.key for o in spec_row.obligations})
        self.assertEqual(
            (), tuple(p for p in audit_registry_coverage()
                      if "directshape" in p))

    def test_surface_check_reads_the_same_geometry_as_the_count(self):
        """The order of checks is LOAD-BEARING: the surface witness reads `__ge_`,
        declared by the face-count witness. Swap them and the user gets
        CS0103, not us."""
        from kir.shape_emit import emit_directshape

        v, t = tetra()
        op = {"id": "D1", "mesh": {"vertices_mm": v, "triangles": t},
              "category": "mass", "name": "меш"}
        _d, _c, checks, _r = emit_directshape(op, "2026", "kir:test")
        keys = [c.obligation_key for c in checks]
        self.assertEqual(["bbox", "triangles", "surface"], keys)
        declares = [c for c in checks if "var __ge_D1 =" in c.reader_cs]
        self.assertEqual(1, len(declares))
        self.assertEqual("triangles", declares[0].obligation_key)
        self.assertLess(keys.index("triangles"), keys.index("surface"))

    def test_no_hash_is_emitted_because_the_client_cannot_bind_one(self):
        """Measurement :52412 (09.08): `System.Security.Cryptography.SHA256` gives
        CS1069 on 2025 and 2026 — the type is forwarded to an assembly outside the closure
        of the client's references. The hash cannot be emitted; the preimage is compared instead."""
        v, t = tetra()
        cs = compile_program(_prog(v, t), revit_version="2026",
                             snapshot={"levels": []}).csharp
        self.assertNotIn("Cryptography", cs)
        self.assertNotIn("SHA256", cs)
        self.assertIn("__KirCanonPayload(", cs)

    def test_the_helper_is_absent_when_nothing_calls_it(self):
        """Absence stays absence: a program without a mesh must remain
        byte-for-byte the same as before (the same law as for `__ClassName`)."""
        wall = {"ir_version": "1.0", "intent": "t",
                "ops": [{"op": "create_wall", "id": "W1", "p0_mm": [0, 0],
                         "p1_mm": [6000, 0], "height_mm": 3000,
                         "level": {"by": "element_id", "value": 42}}]}
        cs = compile_program(wall, revit_version="2026",
                             snapshot={"levels": []}).csharp
        self.assertNotIn("__KirCanonUnit", cs)
        self.assertNotIn("__KirCanonPayload", cs)

    def test_a_face_that_the_emission_grid_collapses_is_a_typed_refusal(self):
        """Rounding to hundredths can COLLAPSE a sliver that mesh.py's laws
        let through (min edge 1 mm, min area 1 mm²). Such a mesh would arrive at
        Revit as a degenerate face — here it gets a named refusal, not a silent loss
        of the witness."""
        # base 1000 mm, height 0.002 mm: area 1 mm², min edge ~500 mm
        verts = [[0.0, 0.0, 0.0], [1000.0, 0.0, 0.0], [500.0, 0.002, 0.0],
                 [500.0, 400.0, 800.0]]
        tris = [[0, 1, 2], [0, 1, 3], [0, 2, 3], [1, 2, 3]]
        diags: list = []
        self.assertIsNotNone(
            validate_mesh({"vertices_mm": verts, "triangles": tris},
                          "D1", "mesh", diags),
            "предпосылка теста: законы формы этот меш ПРОПУСКАЮТ")
        out = compile_program(_prog(verts, tris), revit_version="2026",
                              snapshot={"levels": []})
        self.assertFalse(out.ok)
        self.assertEqual([MESH_DEGENERATE], [d.code for d in out.diagnostics])
        self.assertEqual("D1", out.diagnostics[0].op_id)


if __name__ == "__main__":
    unittest.main()
