"""THE COVERAGE PERCENTAGE TRAVELS WITH ITS OWN CONDITIONS, OR IT IS
UNINTERPRETABLE.

THE OCCASION IS THE MEASUREMENT OF 12.08.2026, AND IT HITS THE PROJECT'S
MAIN SHOWCASE. Two revisions of ONE façade, with the compiler not changed
by a single line between them:

    sob62_fas_r23_v12   63.80%      read 5 095, scanned 14 categories
    sob62_fas_r23_v19   91.23%      read 5 218, scanned 15

27 points. What makes them is NOT expressiveness and not the volume of
reading in the naive sense (+2.4% of elements). One extra category read —
122 curtain-wall grids — let the lifter RECOGNIZE 1 264 panels and mullions
as children generated by the curtain wall; `generator_child` is excluded
from the honest figure, so the DENOMINATOR dropped (4 205 -> 2 942), while
the numerator barely moved (2 683 -> 2 806). **123 read elements
reclassified 1 264 others.**

NOT ONE EXISTING FLAG CAUGHT THIS: both runs have `census_balanced: true`,
`errors: []`, `done: 1`, `is_partial_read: false`,
`generator_children_assumption_broken: false`. The only thing that told
them apart was `categories_scanned`, which was never compared against
anything.

THE CONSEQUENCE THAT MATTERS MORE THAN THE CASE ITSELF: the published
96.13% was taken WITHOUT these conditions alongside it. The number is not
"wrong" — it is UNINTERPRETABLE, and the difference between those two
words is exactly the project's honesty.

THE SIGNAL WAS NOT INVENTED FROM SCRATCH, BUT ASKED OF THE AUTHORITIES: the
extraction table knows what we're able to read; the §18.1 census knows
what's in the document; `L0` knows what was read. `category_outside_table`
is deliberately NOT included in the conditions: it's a known gap, and the
metric exists to describe exactly it.
"""
import json
import os
import pathlib
import sys
import tempfile
import unittest

from kir.instruments import content_coverage as CC  # noqa: E402


os.environ.setdefault("KIR_REJECTIONS_PATH",
                      os.path.join(tempfile.gettempdir(),
                                   "kir_test_coverage_conditions.jsonl"))

#: 🔴 THE ROOT AFTER THE SPLIT (28.08.2026). `parents[3]` from
#: `kir/kir/tests/x.py` gives `/opt` — the directory where our package sits
#: next to other trees. Before 27.08 the same count from
#: `backend/kukai/ir/tests/x.py` gave the install root. The right root is
#: the one the package is INSIDE of.
_TOOLS = pathlib.Path(__file__).resolve().parents[2] / "tools"
if str(_TOOLS) not in sys.path:
    sys.path.insert(0, str(_TOOLS))



#: A full set of side indexes is the default for both reports, so the
#: first condition's tests don't fall apart on the second.
_ALL_SIDES = ["annotation", "curtain", "curve", "dimension",
              "family_placement", "group", "mep_system", "sketch", "tag"]


def _report(unread: dict[str, int], scanned: int,
            sides: list[str] | None = None) -> dict:
    """A skeleton report: the test is about CONDITIONS, not coverage arithmetic."""
    return {"conditions": {"table_available": True,
                           "categories_scanned": scanned,
                           "in_table_unread": dict(unread),
                           "in_table_unread_elements": sum(unread.values()),
                           "side_indexes": list(
                               _ALL_SIDES if sides is None else sides)}}


class TwoReportsAreComparableOnlyOnEqualReads(unittest.TestCase):

    def test_control_a_report_is_comparable_with_itself(self):
        """PASS CONTROL. Without it the refusal below would mean nothing: a
        rule that rejects EVERYTHING doesn't distinguish comparable from
        incomparable."""
        one = _report({"OST_Dimensions": 426}, scanned=14)
        ok, why = CC.comparable(one, one)
        self.assertTrue(ok, why)
        self.assertEqual(why, "")

    def test_one_extra_unread_category_makes_them_incomparable(self):
        """FAIL CONTROL. Exactly the case of the two façade revisions: the
        sets differ by ONE category, and that's enough."""
        left = _report({"OST_Dimensions": 426, "OST_CurtainGridsWall": 122},
                       scanned=14)
        right = _report({"OST_Dimensions": 426}, scanned=15)
        ok, why = CC.comparable(left, right)
        self.assertFalse(ok)
        self.assertIn("OST_CurtainGridsWall", why)
        self.assertIn("несопоставимы", why)

    def test_the_refusal_names_both_sides(self):
        """A refusal that names a code without the data makes the reader do
        the work — the same defect as a refusal with no next move."""
        left = _report({"OST_A": 1}, scanned=14)
        right = _report({"OST_B": 2}, scanned=14)
        ok, why = CC.comparable(left, right)
        self.assertFalse(ok)
        self.assertIn("OST_A", why)
        self.assertIn("OST_B", why)

    def test_unknown_conditions_refuse_rather_than_assume_equality(self):
        """The absence of conditions is NOT "the conditions are the same."
        An empty dict would read as "everything was read" — that is, as the
        most favorable outcome."""
        ok, why = CC.comparable({"conditions": {"table_available": False}},
                                _report({}, scanned=15))
        self.assertFalse(ok)
        self.assertIn("неизвестны", why)

    def test_equal_sets_with_different_counts_stay_comparable(self):
        """Comparability is decided by the SET of categories, not their
        sizes: two buildings legitimately have different element counts in
        one category, and forbidding such a comparison would mean
        forbidding variance altogether."""
        ok, why = CC.comparable(_report({"OST_Dimensions": 426}, 14),
                                _report({"OST_Dimensions": 9}, 14))
        self.assertTrue(ok, why)


class SideIndexesAreAConditionOfTheSameRank(unittest.TestCase):
    """THE SECOND CONDITION, CLOSED ON 12.08.2026 BEFORE THE FIRST LIVE COMPARISON.

    The census can be complete on both runs, while the lifter on one of
    them has NOTHING TO LIFT WITH: the side index decides the very
    POSSIBILITY of lifting. Without `family_placement` every family
    instance is an atom; without `dimension` dimensions never get lifted at
    all.

    THE OCCASION IS NAMED BEFORE THE BITE, NOT AFTER. `k2_ar_rd_v15`, the
    run all our coverage numbers were taken from, finished with
    `stage="error"` and WITHOUT `mep_system`, `tag`, `dimension`. A live
    decompile runs with all stages. Comparing the two would have passed the
    old `comparable()` (the unread categories match, the census is complete
    on both) and would have shown a difference that would be read as a
    compiler win — when it is in fact a difference in RUN COMPLETENESS. The
    same defect that cost 27 points on the two façade revisions, and this
    time in the single most important comparison.
    """

    def test_same_indexes_stay_comparable(self):
        """PASS CONTROL: a rule that rejects EVERYTHING doesn't distinguish
        comparable from incomparable."""
        ok, why = CC.comparable(_report({}, 44), _report({}, 44))
        self.assertTrue(ok, why)

    def test_a_missing_side_index_makes_them_incomparable(self):
        left = _report({}, 44, sides=["curve", "sketch"])
        right = _report({}, 44, sides=["curve", "sketch", "dimension"])
        ok, why = CC.comparable(left, right)
        self.assertFalse(ok)
        self.assertIn("dimension", why)
        self.assertIn("боковых индексов", why)

    def test_the_refusal_explains_that_it_is_not_the_compiler(self):
        """A refusal must name the MECHANISM, or it will be read as
        nitpicking and worked around: a difference in run completeness
        reads easily as a compiler difference, which is exactly what the
        lock is set up against."""
        ok, why = CC.comparable(_report({}, 44, sides=["curve"]),
                                _report({}, 44, sides=["curve", "tag"]))
        self.assertFalse(ok)
        self.assertIn("НЕ потому, что компилятор хуже", why)

    def test_unknown_side_indexes_refuse_rather_than_assume_equality(self):
        """A report taken by the instrument before 12.08 carries no set. An
        empty list would read as "there were no indexes" — the most
        favorable outcome."""
        stale = {"conditions": {"table_available": True,
                                "in_table_unread": {},
                                "categories_scanned": 44}}
        ok, why = CC.comparable(stale, _report({}, 44))
        self.assertFalse(ok)
        self.assertIn("неизвестен", why)

    def test_the_list_comes_from_the_loader_not_a_second_copy(self):
        """A hand-rolled list of names would diverge from the loader at the
        first new stage, and would diverge SILENTLY: a missing name would
        look like "the run doesn't have this index"."""
        import sys
        sys.path.insert(0, str(_TOOLS))
        from kir.instruments.relift_offline import _SIDE_INDEX_FILES
        self.assertEqual(tuple(CC._SIDE_INDEX_NAMES), tuple(_SIDE_INDEX_FILES))


class TheConditionsLineAlwaysSaysWhatItKnows(unittest.TestCase):

    def test_it_names_the_unread_categories(self):
        text = CC._conditions_line(
            _report({"OST_CurtainGridsWall": 122}, 14)["conditions"])
        self.assertIn("OST_CurtainGridsWall", text)
        self.assertIn("ТОЛЬКО с прогоном", text)

    def test_an_empty_set_still_states_the_condition(self):
        """An empty set is the CONDITION "everything we're able to read was
        read," not the absence of a condition; silence here would read as
        "compare against anything at all"."""
        text = CC._conditions_line(_report({}, 15)["conditions"])
        self.assertIn("Сопоставим только", text)

    def test_a_missing_table_says_so_instead_of_printing_zero(self):
        text = CC._conditions_line({"table_available": False})
        self.assertIn("УСЛОВИЯ НЕИЗВЕСТНЫ", text)


if __name__ == "__main__":
    unittest.main()
