"""Does the DAG check see EVERY reference physically present in the program.

WHY THIS WAS SET UP NOW. Ops are becoming a BACK-END part: they will be
generated by an intent-unfolding pass, not by hand and not by the lifter. The
edge walk in ``compiler._parse_and_check_internal`` is **NOT generic**: it
looks at the TOP level of the parameter value plus two NAMED deep cases (the
selector's second stage ``by:face`` -> ``of``; the RELATE address
``at_element``). The comment right there states plainly what this risks: a
reference that moved deeper would become invisible, and KIR-L003/L004 would
stop firing SILENTLY, and the emitter would reference a C# variable with no
guarantee that the producing op sits above it.

THE INSTRUMENT DOES NOT COPY THE WALKER. Two copies of one rule are
guaranteed to diverge (the predicate "this is a compile error" has already
lived in our codebase twice with different content). So the test ASKS THE
AUTHORITY: it uses a generic walk to find every ``{"by": "ref"}`` at ANY
depth, breaks the target one at a time, and demands a KIR-L003/L004
diagnostic from ``plan_program``. The generic walk is exactly what
completeness means here: it does not know the list of legal depths, so a new
depth falls under the check on its own.

MEASURED 2026-08-12 on this tree:

    programs in PROGRAMS               58
    plan cleanly                        51   (7 fail KIR-P003 before mutation)
    reference sites via generic walk    41
    seen by the DAG check               41   silently accepted 0

**THE BOUNDARY THIS GREEN DOES NOT CLOSE, AND IT MUST BE READ ALONGSIDE IT.**
All 45 reference sites in the corpus (41 among the planning ones + 4 among
the failing ones) are TOP-LEVEL. Deep ones — **ZERO**. That is, both deep
branches of the walker are NOT EXERCISED BY THE CORPUS AT ALL: they are
written, commented as load-bearing, and confirmed by not a single checkable
golden. The green below proves the top level and says nothing about depth —
exactly the kind of list that must be declared, not assumed.

MEASURED IN PASSING, AND THIS IS STRONGER THAN THE TEST: the schema is
CLOSED. An attempt to place a reference under its own key
(``{"by": "name", "__nested__": {"by": "ref", ...}}``) is rejected by
``KIR-T001`` BEFORE any question of depth arises — that is, "remove the
possibility" is already in place here, and a machine-generated unfolding
cannot invent an arbitrary depth. Exactly two LEGAL deep forms remain
unclosed.

═══════════════════════════════════════════════════════════════════════════
DEBT D-GATE-1 · opened 2026-08-12 · with a COST and a TRIGGER CONDITION
═══════════════════════════════════════════════════════════════════════════

**THE DEBT'S WORDING CHANGED FROM THE ORIGINAL, AND THAT IS THE MAIN POINT OF
THIS RECORD.** The debt used to read as "extract the built-in reference
walker so there is ONE walker." The 2026-08-12 measurement refutes that
wording: there are not two identical walkers but two DIFFERENT ones, and they
cannot be merged without first merging the dialects.

    compiler.py:881-935      PROGRAM dialect   {"by":"ref","value":<op id>}
                             NOT generic: top level `sel`/`target_w`,
                             `refs_w` elements, the selector's second stage
                             `by:face`->`of`, plus RELATE `at_element` as a
                             separate list
    materialize.py:1156      L1 dialect        {"ref": <l1 _id>}
                             GENERIC (recurses over everything), but with an
                             early exit on the `by` key — deliberately does
                             NOT enter selectors

The first enumerates depths, the second recurses; and that is not sloppiness
but a consequence of the dialects. `{"ref": …}` cannot collide with a
selector, so recursion there is safe. `{"by":"ref"}` lives INSIDE selectors,
so blind recursion in the program is a different decision, not the same one.

**THE COST OF LEAVING IT (measured, not estimated).** All 45 reference sites
in the corpus are TOP-LEVEL, deep ones ZERO. So both deep branches of the
compiler are exercised by NOT A SINGLE checkable golden: they are written,
commented as load-bearing, and confirmed by nothing. If an unfolding pass
that generates ops by machine places a reference into a legal deep form, and
the branch has drifted — KIR-L003/L004 will stop firing SILENTLY, and the
emitter will reference a C# variable with no guarantee that the producing op
sits above it. This is a cardinal invariant, not a convenience. The
mitigating factor must be read alongside it: the schema is CLOSED
(`KIR-T001`), so exactly TWO legal forms are at risk, not an arbitrary depth.

**THE COST OF PAYING IT (and why it is higher than it looks).** The change is
on the order of 54 lines. But its CORRECTNESS is unprovable today: there is
nothing to check the new behavior against, because the corpus has zero deep
sites. There is nothing to buy confidence with — the only option is to
rewrite the code and hope, and that is exactly what we do not do. **So the
debt is not that the work is undone, but that there is nothing to accept it
with.**

**THE TRIGGER CONDITION — not a date but an event, and it is checkable:**
the debt comes due on the day the corpus gains its FIRST deep reference site.
The check costs one call: ``ref_sites`` below already counts depth, and the
test's ``MIN_SITES`` line prints the denominator. While deep sites are 0,
there is nothing to pay; as soon as they are ≥1, the cost of paying drops to
the ordinary one, because something to check against appears.

**WHAT THIS RECORD DOES NOT CLAIM.** That the two walkers agree. The
measurement only says that on TODAY'S corpus they give one answer (41 of
41), and the corpus contains no depth. This is "they do not diverge where we
looked," not "they do not diverge."
"""
from __future__ import annotations

import copy
import unittest
from typing import Any, Iterator

from kir.compiler import plan_program
from kir.diag import KirRefusal
from kir.tests.test_emitter_scope_contract import PROGRAMS

#: A target guaranteed not to be in any program.
MISSING = "__ZZZ_NOT_AN_OP__"

#: Non-emptiness threshold. Lower — means the corpus or the walker has
#: drifted from the instrument, and green stopped asserting anything.
#: Measured 08-12: 41.
MIN_SITES = 30


def ref_sites(node: Any, path: tuple = ()) -> Iterator[tuple]:
    """(path, node) for every ``{"by": "ref"}`` at ANY depth.

    The generic walk is the whole point: it does NOT know the list of legal
    depths, so a depth added tomorrow falls under the check without a code
    change.
    """
    if isinstance(node, dict):
        if node.get("by") == "ref" and isinstance(node.get("value"), str):
            yield path, node
        for key, value in node.items():
            yield from ref_sites(value, path + (key,))
    elif isinstance(node, list):
        for index, item in enumerate(node):
            yield from ref_sites(item, path + (index,))


def _at(root: Any, path: tuple) -> Any:
    cur = root
    for step in path:
        cur = cur[step]
    return cur


def _dag_refuses(program: Any) -> bool:
    """Whether the program failed SPECIFICALLY on a reference (L003/L004)."""
    try:
        plan_program(program, bulk=True)
    except KirRefusal as exc:
        return bool({"KIR-L003", "KIR-L004"} & {d.code for d in exc.diagnostics})
    return False


def _plans(program: Any) -> bool:
    try:
        plan_program(program, bulk=True)
    except Exception:  # noqa: BLE001 — only the fact of failure matters here
        return False
    return True


def _programs() -> Iterator[tuple[str, dict]]:
    for name, raw in sorted(PROGRAMS.items()):
        prog = raw.get("program", raw) if isinstance(raw, dict) else raw
        yield name, prog


class EveryRefIsVisibleToTheDagCheck(unittest.TestCase):

    def test_every_ref_in_the_corpus_is_seen(self):
        """A broken target must give L003/L004 at EVERY site.

        A silently built plan with a dangling reference is exactly the
        defect this test was written for: the emitter would reference a
        nonexistent C# variable, and the compiler would stay silent.
        """
        checked = 0
        for name, prog in _programs():
            if not _plans(copy.deepcopy(prog)):
                continue  # a failure BEFORE mutation would mean measuring the wrong thing
            for path, _ in list(ref_sites(prog)):
                checked += 1
                with self.subTest(program=name, path=".".join(map(str, path))):
                    mutated = copy.deepcopy(prog)
                    _at(mutated, path)["value"] = MISSING
                    self.assertTrue(
                        _dag_refuses(mutated),
                        f"{name}: ссылка по пути {path} НЕ ВИДНА DAG-проверке — "
                        f"план строится с висячей целью")
        self.assertGreaterEqual(
            checked, MIN_SITES,
            f"площадок найдено {checked} — прибор ничего не мерил, "
            f"зелёный вакуумный")

    def test_the_probe_can_say_no_in_both_directions(self):
        """A FAIL control and a PASS control on the mutation itself.

        A mutation that breaks ANY program proves no more than a mutation
        that breaks none: what matters is that the probe did exactly what
        was declared.
        """
        sample = None
        for _name, prog in _programs():
            if not _plans(copy.deepcopy(prog)):
                continue
            sites = list(ref_sites(prog))
            if sites:
                sample = (prog, sites[0][0])
                break
        self.assertIsNotNone(sample, "в корпусе не нашлось ни одной ссылки")
        prog, path = sample

        # PASS control: the unmutated program plans successfully
        self.assertTrue(_plans(copy.deepcopy(prog)))
        # FAIL control: the broken target goes red
        broken = copy.deepcopy(prog)
        _at(broken, path)["value"] = MISSING
        self.assertTrue(_dag_refuses(broken))
        # the flip side: a LEGAL target must not produce L003 —
        # otherwise the check fires unconditionally and distinguishes nothing
        intact = copy.deepcopy(prog)
        self.assertFalse(
            _dag_refuses(intact),
            "L003 срабатывает на неповреждённой программе — проверка не "
            "различает верную ссылку от висячей")

    def test_the_schema_forbids_inventing_a_new_depth(self):
        """"Remove the possibility" ranks ABOVE the walk: a key outside the
        schema is rejected.

        A machine-generated unfolding cannot place a reference under its own
        key — the rejection comes on the unknown field, BEFORE any question
        of depth. This is a case where the strongest medicine is already
        applied; guarding the walk is needed exactly for LEGAL deep forms,
        not for arbitrary ones.
        """
        prog = {
            "ir_version": "1.0",
            "ops": [
                {"op": "create_level", "id": "L1", "name": "Э1", "elev_mm": 0},
                {"op": "create_wall", "id": "W1",
                 "p0_mm": [0, 0], "p1_mm": [4000, 0], "height_mm": 3000,
                 "level": {"by": "ref", "value": "L1"},
                 "type": {"by": "name", "value": "Стена",
                          "__nested__": {"by": "ref", "value": MISSING}}},
            ],
        }
        with self.assertRaises(KirRefusal) as ctx:
            plan_program(prog, bulk=True)
        self.assertIn("KIR-T001",
                      {d.code for d in ctx.exception.diagnostics})


class ARefThatSilentlyFindsAnotherOp(unittest.TestCase):
    """F-022: the id was accepted VERBATIM (`compiler.py`, taking `op["id"]`),
    while the reference path `.strip()`-ed it (`authoring_validation.py` and
    five other places).

    Related to `EveryRefIsVisibleToTheDagCheck`, but the question is
    DIFFERENT: there it is "DOES the check SEE the reference," here it is
    "does it find THE RIGHT target." The second question is more expensive:
    an invisible reference produces a failure, while a visible one pointing
    at the wrong place produces a wrong building without a single word said.

    MEASURED 2026-08-30, a program with two LEGAL and DIFFERENT ids — `'W1'`
    (wall at x=0) and `' W1'` (wall at x=20000), the marker references the
    second:

        BEFORE  ok=True, 0 diagnostics, in C# `__tg_T1 = (Element)__el_W1`
                — twenty meters off, silently
        AFTER   ok=False, KIR-T001, and the refusal names the AUTHOR'S value

    The id cannot be trimmed on the author's behalf: two legal DIFFERENT ids
    would become one, and we, not the author, would be the ones deciding
    which one is real.
    """

    ЛЬВЛ = {"by": "name", "value": "Этаж 1"}

    def _стена(self, oid, x):
        return {"op": "create_wall", "id": oid, "p0_mm": [x, 0],
                "p1_mm": [x + 6000, 0], "level": self.ЛЬВЛ}

    def test_краевой_пробел_в_id_отвергается_поимённо(self):
        """All six characters that `str.strip()` removes are one class."""
        for пробел, имя in ((" ", "обычный"), ("\t", "таб"), ("\n", "перевод"),
                            ("\u00a0", "NBSP"), ("\u202f", "узкий NBSP"),
                            ("\u3000", "идеографический")):
            for oid in (пробел + "W1", "W1" + пробел):
                with self.subTest(символ=имя, id=oid):
                    with self.assertRaises(KirRefusal) as ctx:
                        plan_program({"ir_version": "1.0",
                                      "ops": [self._стена(oid, 0)]}, bulk=True)
                    коды = {d.code for d in ctx.exception.diagnostics}
                    self.assertIn("KIR-T001", коды)

    def test_отказ_называет_АВТОРСКОЕ_значение_а_не_обрезанное(self):
        """🔴 HALF OF THE FINDING WAS EXACTLY THIS. The earlier KIR-L003
        failure printed `got='W1'` for the author's `' W1 '` — that is, it
        showed an already-normalized value and HID its own cause."""
        with self.assertRaises(KirRefusal) as ctx:
            plan_program({"ir_version": "1.0",
                          "ops": [self._стена(" W1 ", 0)]}, bulk=True)
        свои = [d for d in ctx.exception.diagnostics if d.code == "KIR-T001"]
        self.assertTrue(свои, "отказа по составу id нет")
        d = свои[0]
        self.assertEqual(d.got, " W1 ",
                         "отказ показывает обрезанное значение и прячет причину")
        self.assertEqual(d.expected, "W1")
        self.assertIn("СЛЕДУЮЩИЙ ХОД", d.message_ru,
                      "отказ не называет, что делать дальше")

    def test_ссылка_больше_не_уезжает_на_соседний_оп(self):
        """The main case: TWO legal DIFFERENT ids differing only at the edge."""
        prog = {"ir_version": "1.0", "ops": [
            self._стена("W1", 0),
            self._стена(" W1", 20000),
            {"op": "create_tag", "id": "T1",
             "in_view": {"by": "element_id", "value": 9001},
             "target": {"by": "ref", "value": " W1"}, "at": [3000, 800]}]}
        with self.assertRaises(KirRefusal) as ctx:
            plan_program(prog, bulk=True)
        self.assertIn("KIR-T001",
                      {d.code for d in ctx.exception.diagnostics})

    def test_пробел_ВНУТРИ_id_остаётся_законным(self):
        """THE SECOND HALF (rule 2). Without it the fix would be
        indistinguishable from "forbid whitespace in ids altogether," and
        `str.strip()` does not touch internal ones — so such an op can still
        be referenced, and there is nothing to forbid it for."""
        for oid in ("W 1", "W\t1", "W\u00a01", "W\u30001"):
            with self.subTest(id=oid):
                план = plan_program({"ir_version": "1.0",
                                     "ops": [self._стена(oid, 0)]}, bulk=True)
                self.assertIsNotNone(план)

    def test_мера_взята_у_того_кто_её_применяет(self):
        """The list of whitespace characters is NOT rewritten by hand: it
        must match exactly what `str.strip()` removes. A hand-rolled list
        would drift from Python at its very first revision — the same kind
        of defect as "a dictionary is not a mechanism."
        """
        for c in (" ", "\t", "\n", "\r", "\v", "\f",
                  "\u00a0", "\u202f", "\u3000", "\u2007"):
            with self.subTest(символ=repr(c)):
                if (c + "W1") != (c + "W1").strip():
                    with self.assertRaises(KirRefusal):
                        plan_program({"ir_version": "1.0",
                                      "ops": [self._стена(c + "W1", 0)]},
                                     bulk=True)


if __name__ == "__main__":
    unittest.main()
