"""Why an instance has NO insertion point — and why a transform will not become one.

MEASUREMENT 2026-07-29 (four documents, 55 saved decompiles,
``coverage_matrix_2026-07-29.json``). The reason "FamilyInstance has no
captured LocationPoint and rotation" stood against 7,083 elements, and
the theory "these are face-hosted / work-plane-based families, their
position lives in GetTransform()" was NOT confirmed. A by-name breakdown
of all four documents (the lift run live against frozen L0s):

    446 + 600 + 5880 + 157 = 7083 — and EVERY SINGLE ONE OST_CurtainWallPanels.

Not one face-hosted, not one work-plane-based. Moreover: in K2, all
5,060 ``WorkPlaneBased`` instances DO HAVE a point — meaning the class
the theory called a hole is, in fact, fully readable.

From this follow two obligations that this file guards:

1. A curtain-wall panel has no insertion point BY CONSTRUCTION: its
   position is generated by the host's cut grid, and it is placed not by
   ``NewFamilyInstance`` but by assigning a type to a cell. Substituting
   a free point from ``GetTransform()`` for it would mean passing off a
   silent loss of binding as success (§18.1).
2. The absence of a point must NAME ITSELF. "Failed to read" and "does
   not exist here" are different claims, and only the second says
   anything about the model.

That is why the transform is read as a THIRD SOURCE, but is placed into
fields that do not pretend to be an insertion point, and the record's
invariant forbids a row from carrying both a point and a transform at
the same time — one cannot be substituted for the other structurally.
"""

from __future__ import annotations

import json
import pathlib
import unittest

from kir.decompile.family_placement_extract import (
    FamilyPlacementPayloadError,
    FamilyPlacementRecord,
    FamilyPlacementType,
    LocationAbsence,
    build_family_placement_extract_cs,
    parse_family_placement_index,
)
from kir.decompile.snapshot_io import (
    open_snapshot,
    snapshot_file_exists,
)
# 2026-08-27: the HOST's availability is taken from the PORT. There are
# deliberately no stubs — a test that needs a host must be SKIPPED with a
# named reason, not green by construction.
from kir import ports as _порты

try:
    wrap_user_code = _порты.need(_порты.EXECUTION).wrap_user_code
    _НЕТ_ХОСТА = ""
except _порты.PortMissing as _exc:                          # pragma: no cover
    wrap_user_code = None
    _НЕТ_ХОСТА = str(_exc)
from kir.code_safety import validate_code_safety
from kir.install_paths import install_data_path


def _read_index(path) -> dict:
    """🔴 ONE READER FOR BOTH TESTS — BECAUSE THERE WERE TWO AND THEY DIVERGED.

    Measurement 2026-08-22, running the suite piece by piece: both tests
    in this file are red, from ONE cause in two forms. `snapshot_file_exists`
    was called by both, but imported only by the second — locally, inside
    its own body. The first failed with `NameError`. And both read
    `path.read_text()` raw, even though the cleanup job had compressed
    `sklnk_eom_r26_v7`: the guard sees `.json.gz` and says "exists," while
    a raw read looks for `.json` and says "no such file" — that is, OUR
    blindness disguised as a fact about the corpus. This is a recorded
    defect class ("reading a frozen copy with a raw open"), and here it
    was paid for again, by both halves at once.
    """
    with open_snapshot(path, "rt", encoding="utf-8") as handle:
        return json.load(handle)["family_placement_index"]


def _raw(element_id: str = "10", **overrides) -> dict:
    """A raw row WITHOUT a point — exactly the case this file is about."""
    row = {
        "element_id": element_id,
        "symbol_id": "800",
        "type_name": "С остеклением",
        "family_name": "Системная панель",
        "placement_type": "OneLevelBased",
        "in_place": False,
        "mirrored": False,
        "hand_flipped": False,
        "facing_flipped": False,
        "super_component_id": None,
        "group_id": None,
        "host_id": "900",
        "host_class": "Wall",
        "hand_orientation": [1.0, 0.0, 0.0],
        "facing_orientation": [0.0, 1.0, 0.0],
        "status": "ok",
    }
    row.update(overrides)
    return row


class TheAbsenceOfAPointNamesItself(unittest.TestCase):
    """An empty point is a typed reason, not silence."""

    def test_curtain_panel_absence_is_typed(self) -> None:
        record = FamilyPlacementRecord.from_raw(
            _raw(location_absence="curtain_grid_generated"))
        self.assertIs(
            record.location_absence, LocationAbsence.CURTAIN_GRID_GENERATED)
        self.assertFalse(record.placement_available)
        self.assertIsNone(record.point_mm)
        self.assertIsNone(record.rotation_deg)

    def test_every_absence_spelling_is_accepted(self) -> None:
        for spelling in ("curtain_grid_generated", "face_hosted",
                         "work_plane_based", "unreadable"):
            with self.subTest(spelling=spelling):
                record = FamilyPlacementRecord.from_raw(
                    _raw(location_absence=spelling))
                self.assertEqual(record.location_absence.value, spelling)

    def test_an_unknown_absence_is_refused(self) -> None:
        # An unfamiliar word is NOT "probably unreadable": a reason we do
        # not know how to read must fail, not be silently coarsened.
        with self.assertRaises(FamilyPlacementPayloadError):
            FamilyPlacementRecord.from_raw(
                _raw(location_absence="probably_fine"))

    def test_an_available_placement_explains_nothing(self) -> None:
        # There is a point — nothing to explain. A row carrying both
        # means the emitter contradicts itself.
        with self.assertRaises(FamilyPlacementPayloadError):
            FamilyPlacementRecord.from_raw(_raw(
                point_ft=[1.0, 2.0, 3.0], rotation_rad=0.0,
                location_absence="face_hosted"))

    def test_a_legacy_row_without_the_cause_still_loads(self) -> None:
        # A frozen copy of the corpus was taken with a schema that did
        # not read reasons. Such a row must load, and None here means
        # EXACTLY "did not look," not "there is no reason" — a
        # distinction the lift builds its wording on.
        record = FamilyPlacementRecord.from_raw(_raw())
        self.assertIsNone(record.location_absence)
        self.assertFalse(record.placement_available)


class ATransformIsNeverAnInsertionPoint(unittest.TestCase):
    """The file's main guard: a transform cannot become a point."""

    def test_transform_is_read_but_kept_out_of_the_point(self) -> None:
        record = FamilyPlacementRecord.from_raw(_raw(
            location_absence="face_hosted",
            transform_origin_ft=[1.0, -2.0, 3.5],
            transform_basis_x=[1.0, 0.0, 0.0],
            transform_basis_y=[0.0, 1.0, 0.0],
            transform_basis_z=[0.0, 0.0, 1.0],
        ))
        self.assertIsNotNone(record.transform_origin_mm)
        # RAW feet are converted to mm with the same factor as the point.
        self.assertAlmostEqual(record.transform_origin_mm[0], 304.8, places=6)
        # ...and did not become an insertion point in the process.
        self.assertIsNone(record.point_mm)
        self.assertIsNone(record.rotation_deg)
        self.assertFalse(record.placement_available)

    def test_a_row_cannot_carry_both_a_point_and_a_transform(self) -> None:
        # A structural prohibition on substitution: as long as these two
        # fields cannot stand side by side, no code branch can silently
        # promote a transform into a point — to do that it would first
        # have to break the invariant.
        with self.assertRaises(FamilyPlacementPayloadError):
            FamilyPlacementRecord(
                element_id="10", symbol_id="800", type_name="t",
                family_name="f",
                placement_type=FamilyPlacementType.ONE_LEVEL_BASED,
                in_place=False, mirrored=False, hand_flipped=False,
                facing_flipped=False, super_component_id=None, group_id=None,
                host_id=None, host_class=None,
                hand_orientation=(1.0, 0.0, 0.0),
                facing_orientation=(0.0, 1.0, 0.0),
                placement_available=True,
                point_mm=(1.0, 2.0, 3.0), rotation_deg=0.0,
                transform_origin_mm=(1.0, 2.0, 3.0),
                transform_basis_x=(1.0, 0.0, 0.0),
                transform_basis_y=(0.0, 1.0, 0.0),
                transform_basis_z=(0.0, 0.0, 1.0),
            )

    def test_an_origin_without_a_basis_is_refused(self) -> None:
        # Half a transform is not a transform: without a basis there is
        # nothing to recover the orientation from, and "there is an
        # origin, no rotation" looks like a point.
        with self.assertRaises(FamilyPlacementPayloadError):
            FamilyPlacementRecord.from_raw(_raw(
                location_absence="face_hosted",
                transform_origin_ft=[1.0, -2.0, 3.5]))

    def test_a_degenerate_basis_is_refused(self) -> None:
        with self.assertRaises(FamilyPlacementPayloadError):
            FamilyPlacementRecord.from_raw(_raw(
                location_absence="face_hosted",
                transform_origin_ft=[1.0, -2.0, 3.5],
                transform_basis_x=[1.0, 0.0, 0.0],
                transform_basis_y=[1.0, 0.0, 0.0],
                transform_basis_z=[0.0, 0.0, 1.0]))


class TheProbeReadsTheThirdSourceUnderItsOwnGuard(unittest.TestCase):
    """Every optional read is under ITS OWN guard."""

    @classmethod
    def setUpClass(cls) -> None:
        cls.body = build_family_placement_extract_cs(["1", "2"])

    def test_the_transform_member_is_the_one_that_exists(self) -> None:
        # MEASURED against the member index (35,516 members, six
        # versions): ``FamilyInstance.GetTransform`` DOES NOT EXIST. The
        # member is declared on Autodesk.Revit.DB.Instance (all six
        # versions, since 2012). The test pins down the actual call, not
        # a name pulled from memory.
        self.assertIn("GetTransform()", self.body)

    def test_the_third_source_never_writes_the_point(self) -> None:
        # No row puts a transform into point_ft/rotation_rad.
        for forbidden in ('__row["point_ft"] = __fpRawPoint(__xf',
                          '__row["point_ft"] = __fpRawPoint(__transform',
                          '__row["rotation_rad"] = __xf'):
            with self.subTest(forbidden=forbidden):
                self.assertNotIn(forbidden, self.body)
        self.assertIn('__row["transform_origin_ft"]', self.body)

    def test_each_optional_read_has_its_own_catch(self) -> None:
        # A single try around the whole element is exactly the shape of
        # the bug (see 12,369 rooms, cb9c3b65). New reads must fail individually.
        for guarded in ("__fpTryHostFace", "__fpTryTransform",
                        "__fpTryLocation"):
            with self.subTest(guarded=guarded):
                self.assertIn(guarded, self.body)

    def test_the_curtain_panel_test_is_structural(self) -> None:
        # A curtain-wall panel is recognized by the CLASS
        # Autodesk.Revit.DB.Panel, not by the family name or the
        # category name: a name lies easily.
        self.assertIn("Autodesk.Revit.DB.Panel", self.body)
        self.assertNotIn("Системная панель", self.body)
        self.assertNotIn("System Panel", self.body)

    def test_the_probe_is_still_shippable(self) -> None:
        # 🔴 THE SKIP WAS WIRED UP ON 2026-08-28, AND THE MARKER HAD BEEN
        # WAITING FOR IT SINCE THE START. The file's header requires: "a
        # test that needs a host must be SKIPPED with a named reason,
        # not green by construction." `_НЕТ_ХОСТА` was set up and read
        # by NO ONE — without a host the test failed with
        # `TypeError: NoneType is not callable`, that is, a failure
        # about US, spoken in the voice of an assertion about the
        # probe's fitness. The requirement stood in the prose and did
        # not stand in the code — the second such case this shift.
        if wrap_user_code is None:
            self.skipTest("обёртка исполнения — у хоста: " + _НЕТ_ХОСТА)
        validate_code_safety(self.body)
        # The wrapper INDENTS every line of the body, so what is checked
        # is the first line, not the first forty characters: forty
        # characters now step over a line break (the body begins with
        # the source binding ``Document __src = ...``), and the test
        # would be measuring the indentation, not the delivery.
        self.assertIn(self.body.strip().splitlines()[0],
                      wrap_user_code(self.body))


#: 🔴 THE CORPUS BELONGS TO THE INSTALLATION (2026-08-28). It used to be
#: `parents[4] / "backend" / "data" / "decompile"` — before the split, an
#: address inside the installation; now the same count gives
#: `/opt/backend/data/decompile`, which does not exist. It is addressed
#: by the installation's authority; no installation — no corpus, and
#: this shows up as a skip, not a guess.
_CORPUS = (install_data_path("decompile")
           or pathlib.Path("<установка не названа>") / "decompile")
#: One decompile for each of the four documents that gave 7,083.
_MEASURED = ("k2_ar_rd_v6", "sklnk_eom_r26_v7", "sklnk_eom_r26_v8",
             "sob62_fas_r23_v2")


class TheMeasuredGapIsNotFaceHosted(unittest.TestCase):
    """A refutation of the theory, fixed on the data.

    If one day this test fails, it will mean a document has appeared
    where a NON-curtain-wall instance has no point — and only then will
    the third source finally get an addressee. Until then it is read for
    diagnosis, not for a point.
    """

    def test_no_point_less_instance_is_work_plane_based(self) -> None:
        seen_any = False
        for name in _MEASURED:
            path = _CORPUS / name / "family_placement.index.json"
            if not snapshot_file_exists(path):
                continue
            seen_any = True
            index = _read_index(path)
            offenders = {
                key: row for key, row in index.items()
                if row.get("point_mm") is None
                and row.get("placement_type") == "WorkPlaneBased"
            }
            with self.subTest(snapshot=name):
                self.assertEqual(
                    offenders, {},
                    f"{name}: появился work-plane-based экземпляр без точки — "
                    "версию о face-hosted пора перемерить")
        if not seen_any:
            self.skipTest("замороженные разборы недоступны")

    def test_the_point_less_rows_are_curtain_panels(self) -> None:
        # Not the family name, but STRUCTURE: a curtain-wall panel
        # always has a host (Wall/CurtainSystem), and not one of them
        # has a point.
        for name in _MEASURED:
            path = _CORPUS / name / "family_placement.index.json"
            if not snapshot_file_exists(path):
                continue
            index = _read_index(path)
            hostless = [
                key for key, row in index.items()
                if row.get("point_mm") is None
                and row.get("placement_type") in (
                    "OneLevelBased", "OneLevelBasedHosted")
                and row.get("host_id") is None
            ]
            with self.subTest(snapshot=name):
                self.assertEqual(
                    hostless, [],
                    f"{name}: точечный экземпляр без точки И без носителя — "
                    "это уже не витражная панель")


if __name__ == "__main__":
    unittest.main()
