"""Two lifter seams found by the reasons map of 29.07 across four
buildings.

SEAM 1 — HOSTED PLACEMENT. ``_lift_family_fallback`` already knows how to
place a family ON A HOST: it assembles ``hosted_ref`` and passes it into
``place_family`` through the same overload,
``NewFamilyInstance(point, symbol, HOST, level, …)``, that places doors
and windows (measured live on 28.07 on the elevator). But two lines above
stands the gate ``placement_type is not ONE_LEVEL_BASED``, and it cuts off
exactly the placement type that MEANS "hosted" — ``OneLevelBasedHosted``.
The host branch remained reachable only for the ``OneLevelBased`` row,
which happened to have a host by accident.

Measurement of 29.07 across the side indexes (all rows are NOT nested,
i.e. not generated by a parent): ``OneLevelBasedHosted`` is present in
FOUR documents — demo 3122, 13A-RD-AR-K2_v33 2053, SOB6.2_AR 184,
SOB6.2_FAS 14 — and EVERY SINGLE ONE has a point, a rotation, and a
``host_id``. The reason is structural: the op learned about the host, the
lifter's gate was not widened to match.

SEAM 2 — A STAGE'S SILENCE IS NOT A FACT ABOUT THE ELEMENT. §18.2 already
distinguishes an EMPTY placement index from an ABSENT one: a stage cut off
entirely by budget must not be shown as "no lifter." But the distinction
was made ABOUT THE WHOLE DOCUMENT, not about the element: as soon as the
stage has processed even one row, a ceiling or a stair railing — that is,
an element that was NEVER a FamilyInstance and could never have ended up
in the placement index — gets "element is absent from the family
placement side index." This reads as "the extractor lost it," whereas the
truth is "we have no operation for its category."

The cost of the error is visible in the reasons map itself: the same
population stands in it twice under different names — 28926 elements
"category is outside the … lifter table" (snapshots where the stage did
not run) and 8207 elements "absent from the family placement side index"
(the same categories where the stage did run). The reasons ranking is
what decides what to build next; a duplicate in it costs more than any
percentage of coverage.

The rule is therefore generalized from the document to the ELEMENT: if
the stage has NEITHER A ROW NOR A RECEIPT for this element, it has said
nothing about it, and its silence cannot be evidence against it. The old
condition remains a special case of the new one (an empty index with no
receipts = silence about every element).
"""
import unittest

from kir.decompile.family_placement_extract import (
    FAMILY_PLACEMENT_INDEX_SCHEMA_VERSION,
)
from kir.decompile.lift import lift_document
from kir.decompile.schema import (
    GeometryKind,
    L0Document,
    L0Element,
    LevelInfo,
    ProjectInfo,
)

_HOSTED_ROW = {
    "placement_type": "OneLevelBasedHosted",
    "placement_available": True,
    "point_mm": [1500.0, 2500.0, 3000.0],
    "family_name": "Оборудование_настенное",
    "host_id": "900",
    "host_class": "Wall",
    "group_id": None,
    "in_place": False,
    "mirrored": False,
    "hand_flipped": False,
    "facing_flipped": False,
    "hand_orientation": [0.0, 1.0, 0.0],
    "facing_orientation": [-1.0, 0.0, 0.0],
    "rotation_deg": 0.0,
    "super_component_id": None,
    "symbol_id": "77",
    "type_name": "Тип оборудования",
}


def _wall(eid="900"):
    return L0Element(
        element_id=eid, category="OST_Walls", category_ru="Стены",
        type_id="20", type_name="Стена 200",
        level_id="10", level_name="L1",
        geom_kind=GeometryKind.CURVE,
        p0_mm=(0.0, 0.0, 0.0), p1_mm=(6000.0, 0.0, 0.0),
        rotation_deg=None, bbox_min_mm=None, bbox_max_mm=None,
        host_id=None, params={})


def _equipment(eid="500", category="OST_MechanicalEquipment"):
    """A category WITHOUT its own lifter — the generic placement path."""
    return L0Element(
        element_id=eid, category=category, category_ru="Оборудование",
        type_id="77", type_name="Тип оборудования",
        level_id="10", level_name="L1",
        geom_kind=GeometryKind.POINT,
        p0_mm=(1500.0, 2500.0, 3000.0), p1_mm=None, rotation_deg=0.0,
        bbox_min_mm=None, bbox_max_mm=None, host_id="900", params={})


def _ceiling(eid="700"):
    """An element that cannot be in the placement index — it is NOT a
    FamilyInstance and has NO lifter of its own.

    AREA (wave/arch, 29.07): "Ceilings" used to stand here. The example
    had to be replaced because the ceiling NOW HAS an operation and a
    lifter (create_ceiling), and its atom no longer reads as "no lifter"
    — it reads as "no sketch profile," i.e. a reason from its OWN path.
    This is exactly §18.2 in a stronger form than when the test was
    written, but there is no longer anything to check "stage silence =
    no_lifter" on for such an element.

    "Area" (OST_Areas) was taken instead — a category that on 29.07 still
    has no operation (on K2 that is 213 elements, the largest one left
    without an op). The meaning of the test has not changed by a single
    letter: the placement stage's silence about an element is not
    evidence against the element. The function's name was left unchanged
    so the diff reads as a swap of the example, not as a new check."""
    return L0Element(
        element_id=eid, category="OST_Areas", category_ru="Зоны",
        type_id="30", type_name="Зона 100",
        level_id="10", level_name="L1",
        geom_kind=GeometryKind.BBOX_ONLY,
        p0_mm=None, p1_mm=None, rotation_deg=None,
        bbox_min_mm=(0.0, 0.0, 0.0), bbox_max_mm=(1.0, 1.0, 1.0),
        host_id=None, params={})


def _doc(*elements):
    return L0Document(
        doc_name="hosted", revit_version="2023", units="mm", change_stamp="t",
        levels=(LevelInfo("10", "L1", 1800.0),), grids=(), rooms=(),
        project_info=ProjectInfo(), elements=elements)


def _nodes(doc, index):
    return {n["source_element_id"]: n for n in lift_document(doc, None, index)}


class HostedPlacementTypeIsPlaceable(unittest.TestCase):
    """``OneLevelBasedHosted`` is a host in the op, not a refusal."""

    def test_hosted_instance_becomes_place_family_on_its_host(self):
        nodes = _nodes(
            _doc(_wall(), _equipment()), {"500": dict(_HOSTED_ROW)})
        node = nodes["500"]
        self.assertEqual(node["kind"], "op", node["reason"]["detail"] if node["kind"] == "atom" else None)
        self.assertEqual(node["op_name"], "place_family")

    def test_hosted_instance_keeps_the_binding_to_its_host(self):
        nodes = _nodes(
            _doc(_wall(), _equipment()), {"500": dict(_HOSTED_ROW)})
        host_node = nodes["900"]
        self.assertEqual(
            nodes["500"]["params"]["host"], {"ref": host_node["_id"]},
            "закреплённое семейство обязано нести ссылку на свой хост")

    def test_hosted_instance_without_a_host_id_stays_an_atom(self):
        """Hosted WITHOUT a host is a lost binding, not a free point."""
        row = dict(_HOSTED_ROW, host_id=None, host_class=None)
        nodes = _nodes(_doc(_wall(), _equipment()), {"500": row})
        node = nodes["500"]
        self.assertEqual(node["kind"], "atom")
        self.assertEqual(node["reason"]["code"], "missing_reference")

    def test_hosted_instance_whose_host_is_not_lifted_stays_an_atom(self):
        """Placing on something that is not in the program is not
        allowed (behavior preserved)."""
        nodes = _nodes(_doc(_equipment()), {"500": dict(_HOSTED_ROW)})
        node = nodes["500"]
        self.assertEqual(node["kind"], "atom")
        self.assertEqual(node["reason"]["code"], "missing_reference")

    def test_unhosted_one_level_based_is_untouched(self):
        row = dict(_HOSTED_ROW, placement_type="OneLevelBased",
                   host_id=None, host_class=None)
        node = _nodes(_doc(_equipment()), {"500": row})["500"]
        self.assertEqual(node["kind"], "op", node["reason"]["detail"] if node["kind"] == "atom" else None)
        self.assertEqual(node["op_name"], "place_family")

    def test_placement_types_that_are_not_point_placed_still_refuse(self):
        """The gate narrows, it does not disappear: CurveDrivenStructural
        is not a point."""
        row = dict(_HOSTED_ROW, placement_type="CurveDrivenStructural")
        node = _nodes(_doc(_wall(), _equipment()), {"500": row})["500"]
        self.assertEqual(node["kind"], "atom")
        self.assertEqual(node["reason"]["code"], "unsupported_forward_signature")


class StageSilenceIsNotEvidenceAboutTheElement(unittest.TestCase):
    """The placement stage said nothing about the ceiling — meaning
    there is no lifter."""

    def _envelope(self, index, failures):
        return {
            "schema_version": FAMILY_PLACEMENT_INDEX_SCHEMA_VERSION,
            "family_placement_index": index,
            "failures": failures,
        }

    def test_element_the_stage_never_mentioned_reads_as_no_lifter(self):
        envelope = self._envelope({"500": dict(_HOSTED_ROW)}, [])
        node = _nodes(
            _doc(_wall(), _equipment(), _ceiling()), envelope)["700"]
        self.assertEqual(node["kind"], "atom")
        self.assertEqual(
            node["reason"]["code"], "no_lifter",
            "молчание стадии об элементе — не улика против элемента")

    def test_element_with_a_receipt_still_reports_the_receipt(self):
        """The receipt exists — the reason must come FROM IT (§18.2/M5)."""
        envelope = self._envelope(
            {"500": dict(_HOSTED_ROW)},
            [{"element_id": "700", "reason": "not a FamilyInstance: Area",
              "typed_reason": "element_kind_mismatch", "elapsed_ms": None}])
        node = _nodes(
            _doc(_wall(), _equipment(), _ceiling()), envelope)["700"]
        self.assertEqual(node["kind"], "atom")
        self.assertEqual(node["reason"]["code"], "placement_kind_unknown")
        self.assertIn("element_kind_mismatch", node["reason"]["detail"])

    def test_stage_that_never_ran_keeps_its_old_answer(self):
        """The old §18.2 condition is a special case of the new one, not
        an exception."""
        node = _nodes(_doc(_ceiling()), None)["700"]
        self.assertEqual(node["kind"], "atom")
        self.assertEqual(node["reason"]["code"], "no_lifter")


if __name__ == "__main__":
    unittest.main()
