"""Coverage across EVERY persisted model at once — cause vs symptom.

A fix measured on one building teaches you nothing about the next one.  The
demo flattered us: 92.8% there, 64.9% on the first real production model we
pointed the lifter at.  Chasing whichever atom that particular file happened to
produce is how a compiler ends up tuned to one project.

So the unit of measurement here is not a model, it is a REASON.  Every
persisted decompile is re-lifted with the current lifter and the atom reasons
are pooled:

  * a reason seen in SEVERAL documents is structural — a rule of ours that is
    wrong in general, and fixing it moves every model;
  * a reason seen in ONE document is a candidate symptom — possibly a genuine
    edge of that project, and worth suspicion before anyone spends a day on it.

The spread of per-model coverage is the headline number: a compiler that is
worth trusting gives a STABLE percentage on documents it has never seen, and a
wide spread means the number quoted for any single model is not a property of
the compiler at all.

    python tools/coverage_matrix.py
    python tools/coverage_matrix.py --root backend/data/decompile --json out.json
"""

from __future__ import annotations

import argparse
import collections
import json
import pathlib
import re
import sys

_TOOLS = pathlib.Path(__file__).resolve().parent
if str(_TOOLS.parent) not in sys.path:
    sys.path.insert(0, str(_TOOLS.parent))

from relift_offline import relift  # noqa: E402


# A refusal detail often carries the INSTANCE inside the sentence: which two
# edges self-intersect, which parent generated the child, which element id was
# missing.  Pooled verbatim, one cause shatters into a row per instance and
# reads as a long tail of unrelated single-model oddities — exactly the illusion
# this tool exists to dispel.  Numbers and quoted ids are therefore folded away,
# leaving the SHAPE of the sentence, which is the rule that refused.
_VARIABLE = (
    (re.compile(r"'[^']*'"), "'…'"),
    (re.compile(r'"[^"]*"'), '"…"'),
    # Digits only where they are a standalone number.  Without the letter
    # guard "frozen L0" folds to "frozen LN" and the report misquotes the very
    # code it is describing.
    (re.compile(r"(?<![A-Za-z])\d+(?:[.,]\d+)?"), "N"),
)


def _cause(detail: str) -> str:
    for pattern, placeholder in _VARIABLE:
        detail = pattern.sub(placeholder, detail)
    return detail


def _documents(root: pathlib.Path) -> list[pathlib.Path]:
    return sorted(
        (d for d in root.iterdir() if d.is_dir() and (d / "L0.jsonl").is_file()),
        key=lambda d: d.name)


def build(root: pathlib.Path, min_elements: int) -> dict:
    per_model: list[dict] = []
    for directory in _documents(root):
        try:
            report = relift(directory)
        except SystemExit as exc:            # a run that died before its header
            per_model.append({"directory": directory.name, "skipped": str(exc)})
            continue
        except Exception as exc:             # noqa: BLE001 — a crash is data too
            per_model.append({"directory": directory.name,
                              "error": f"{type(exc).__name__}: {exc}"})
            continue
        if report["elements"] < min_elements:
            report["small"] = True
        per_model.append(report)

    # Pool by reason DETAIL: the detail is what names the rule that refused,
    # the bare reason code is too coarse to act on.
    # The same building is often on disk several times (successive decompile
    # runs of one document).  Summing across them triples the element counts
    # and makes a cause look bigger the more often somebody re-ran the
    # extractor — so a cause's weight is the WORST single document, never the
    # sum.  The affected-document count keys on doc_name and was already
    # immune; the element count was not.
    docs_by_detail: dict[str, set[str]] = collections.defaultdict(set)
    per_doc_count: dict[str, dict[str, int]] = collections.defaultdict(dict)
    for report in per_model:
        if "atom_details" not in report:
            continue
        key = report.get("doc_name") or report["directory"]
        # Fold this run's detail variants into causes FIRST.  Within one run
        # the variants of a cause add up ("generated by parent A" + "…by B");
        # only across repeated runs of the SAME document does max apply.
        # Taking max over variants too collapsed 35 170 generated children
        # into 19 — the instrument understating by three orders of magnitude.
        per_run: collections.Counter[str] = collections.Counter()
        for detail, count in report["atom_details"].items():
            per_run[_cause(detail)] += count
        for cause, count in per_run.items():
            docs_by_detail[cause].add(key)
            seen = per_doc_count[cause]
            seen[key] = max(seen.get(key, 0), count)
    count_by_detail = {
        cause: sum(by_doc.values()) for cause, by_doc in per_doc_count.items()
    }

    scored = sorted(
        (
            {"detail": detail,
             "documents": sorted(docs_by_detail[detail]),
             "document_count": len(docs_by_detail[detail]),
             "elements": count_by_detail[detail]}
            for detail in docs_by_detail
        ),
        key=lambda row: (-row["document_count"], -row["elements"]),
    )

    real = [r for r in per_model
            if "honest_pct" in r and not r.get("small")]
    # Spread is measured on the HONEST figure: the raw one moves with how many
    # nested families a project happens to use, which is a property of the
    # project, not of the compiler.
    #
    # ...and it is measured PER DOCUMENT, not per directory.  The same lesson
    # already fixed on the cause axis ("вес причины = ХУДШИЙ документ, не
    # сумма") was left standing here: one building lies on disk in several
    # extracts, so counting directories let repeated extraction of ONE model
    # masquerade as a spread across MANY.  Measured 2026-07-27: six extracts of
    # SOB6.2 printed «разброс по 7 зданиям 73.57…93.28% (19.71 п.п.)» while
    # only two distinct buildings were on disk — and the low extracts were of a
    # model actively being polluted with test elements, so the figure described
    # the measurer, not the compiler.  Worst-per-document keeps the pessimism
    # (a bad extract still counts) without inventing buildings.
    worst_per_doc: dict[str, dict] = {}
    for report in real:
        doc = report.get("doc_name") or report["directory"]
        if (doc not in worst_per_doc
                or report["honest_pct"] < worst_per_doc[doc]["honest_pct"]):
            worst_per_doc[doc] = report
    real = sorted(worst_per_doc.values(), key=lambda r: r["honest_pct"])
    percentages = [r["honest_pct"] for r in real]

    # Число покрытия обязано нести с собой СОСТАВ ВЫБОРКИ.
    #
    # 27.07 эта карта замерила два документа, оба архитектурные, и на этом
    # основании было заявлено «покрытие стабильно между зданиями, размах
    # 0.45 п.п.» — утверждение о компиляторе, сделанное по свойству выборки.
    # На первой же не-АР модели (ЭОМ) оно рухнуло с ~93% до 67.7%. Карта не
    # врала: ей просто не задавали вопрос, на который отвечали её числом.
    #
    # Поэтому «разброс» теперь ОТКАЗЫВАЕТСЯ считаться, пока в выборке меньше
    # двух разделов, и вместо числа печатает причину отказа. Утверждение о
    # межмодельной стабильности на односоставной выборке становится
    # невыразимым — тем же способом, каким компилятор делает невыразимым
    # молчаливо-неверный результат.
    by_discipline: dict[str, list[float]] = collections.defaultdict(list)
    for report in real:
        by_discipline[report.get("discipline", "shared")].append(
            report["honest_pct"])
    disciplines_measured = sorted(by_discipline)
    enough = len(disciplines_measured) >= 2

    spread: dict = {
        "documents_measured": len(real),
        "disciplines_measured": disciplines_measured,
        "per_discipline": {
            d: {"documents": len(v), "min_pct": min(v), "max_pct": max(v)}
            for d, v in sorted(by_discipline.items())
        },
    }
    if enough and percentages:
        spread.update({
            "min_pct": min(percentages),
            "max_pct": max(percentages),
            "spread_pp": round(max(percentages) - min(percentages), 2),
        })
    else:
        spread["refused"] = (
            "разброс не считается: в выборке "
            f"{len(disciplines_measured)} раздел(ов) — "
            f"{', '.join(disciplines_measured) or 'ни одного'}. "
            "Число по одному разделу нельзя читать как свойство компилятора.")
    return {"models": per_model, "reasons": scored, "spread": spread}


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--root", type=pathlib.Path,
                        default=pathlib.Path("backend/data/decompile"))
    parser.add_argument("--json", type=pathlib.Path, default=None)
    parser.add_argument("--min-elements", type=int, default=100,
                        help="below this a run is a hand-made scene, not a "
                             "building; it still reports but is excluded from "
                             "the spread")
    args = parser.parse_args(argv)

    matrix = build(args.root, args.min_elements)

    print("=== покрытие по моделям ===")
    for report in matrix["models"]:
        if "lifted_pct" not in report:
            note = report.get("skipped") or report.get("error") or "?"
            print(f"  {report['directory']:26s}  — {str(note)[:60]}")
            continue
        mark = "  (сцена)" if report.get("small") else ""
        # §18.1: не молчать о непрочитанном. «Честное покрытие» здесь честно
        # ровно по одной оси — оно исключает порождаемых детей; знаменателем
        # у него по-прежнему остаётся ПРОЧИТАННОЕ. Пока рядом не стоит число
        # непрочитанного, эта колонка выглядит утверждением о здании, а
        # является утверждением о выборке таблицы категорий.
        if report.get("census_present"):
            census = (f"  не читалось {report['unscanned_elements']:>7d} "
                      f"({report['categories_scanned']}/"
                      f"{report['categories_in_model']} кат.)")
        else:
            census = "  переписи нет"
        print(f"  {report['doc_name'][:24]:24s} R{report['revit_version']}  "
              f"{str(report.get('discipline', '?'))[:13]:13s} "
              f"{report['elements']:7d} эл.  "
              f"сырое {report['lifted_pct']:6.2f}%  "
              f"честное {report['honest_pct']:6.2f}%{census}{mark}")

    spread = matrix["spread"]
    print(f"\n  выборка: {spread['documents_measured']} документ(ов), "
          f"разделы: {', '.join(spread['disciplines_measured']) or '—'}")
    for disc, row in spread["per_discipline"].items():
        print(f"    {disc:14s} документов {row['documents']}  "
              f"честное {row['min_pct']}% … {row['max_pct']}%")
    if "refused" in spread:
        print(f"\n  {spread['refused']}")
    else:
        print(f"\n  разброс по {spread['documents_measured']} документам: "
              f"{spread['min_pct']}% … {spread['max_pct']}%  "
              f"(размах {spread['spread_pp']} п.п.)")

    print("\n=== причины отказа, по числу ЗАТРОНУТЫХ ДОКУМЕНТОВ ===")
    print("    (несколько документов = структурная причина; "
          "один = кандидат в симптомы)")
    for row in matrix["reasons"][:25]:
        scope = "СТРУКТУРНАЯ" if row["document_count"] > 1 else "одна модель"
        print(f"  [{scope:11s}] {row['elements']:6d} эл.  "
              f"{row['detail'][:88]}")

    if args.json:
        args.json.write_text(
            json.dumps(matrix, ensure_ascii=False, indent=1), encoding="utf-8")
        print(f"\nотчёт: {args.json}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
