"""COMPILER STATE, GENERATED DIRECTLY INTO `kir/CLAUDE.md`.

    PYTHONPATH=/opt/kir python3.12 tools/kir_canon_state.py            # print
    PYTHONPATH=/opt/kir python3.12 tools/kir_canon_state.py --write    # write in

🔴 THIS FILE IS NOT A COPY OF THE OWNER'S INSTRUMENT, BUT ITS REPAIR (2026-08-27).

The instrument of the same name IN THE OWNER'S TREE is today BROKEN AT HOME,
and this is measured by a run, not assumed:

    ls <owner's tree>/kukai/ir              ->  No such file or directory
    PYTHONPATH=. python3.12 tools/kir_canon_state.py
        ->  ModuleNotFoundError: No module named 'kir'

The 27.08 split removed the area from the product tree and made the language
a separate package. The instrument's imports MADE IT through the move
(`from kir import spec`), but the paths did not: it reads `BACKEND/kukai/ir`,
which no longer exists, and tries to import `kir` where the package is not
installed. That is, it works NEITHER HERE NOR THERE; its real home is this
repository, and moving it here completes a relocation already begun, not a
copy.

WHY `tools/`, AND NOT INSIDE THE PACKAGE. The instrument EDITS A FILE OF THE
WORKING REPOSITORY (`kir/CLAUDE.md`). Having shipped in the wheel, it would
edit a copy in `site-packages`, that is, it would do nothing meaningful.
`pyproject` packages `kir*` — meaning `tools/` correctly stays outside the
distribution. Instruments that READ the language and belong with whoever
installed it live in `kir/instruments/`; this one is not among them.

WHY AT ALL, AND THIS IS A MEASUREMENT, NOT TASTE (2026-08-15). The KIR canon
was stale in at least five places, ALL in the direction of UNDERSTATING
capability:

    the canon said                      measured on 15.08
    ────────────────────────────────────────────────────────────
    device id «в двух местах»           27 occurrences in 24 files
    «41 оп с живым свидетельством»      64 of 69
    «27 пишущих не доехали до Ревита»   5
    «корпус кончается 04.08»            runs through 15.08 09:27
    traversal «911 модулей / 368 живых» 1154 / 425

The cost of this is not inaccuracy but the "already built" mistake: FOUR
times in one session, and THREE of those times what was already done turned
out BETTER than what was planned. The canon gets read before the code
because it is more convenient, and an understated number reads as "this
doesn't exist".

🔴 THE SEPARATION EVERYTHING RESTS ON: FORMS SEPARATE, STATE SEPARATE.

* **FORMS** (55+ named defect forms) remain PROSE and do not rot: the form
  «прибор не называет свой вызов» is true a year from now too. They do not
  need to be generated.
* **STATE** — everything that carries a NUMBER — is generated by the
  instrument and lives under the ratchet
  (`kir/tests/test_kir_canon_state_is_current.py`). It can lie only until
  the next run of the suite.

Nobody mutates the prose: no run turns red because a description lies. The
generated block mutates.

🔴 WHAT IS NOT HERE AND WHY — THIS IS PART OF THE CONTRACT, NOT A CAVEAT.
Numbers that require a CORPUS or a LIVE SERVICE are NOT carried over here:
they are a property of the MACHINE, and the canon must read the same for
everyone. Instead of the number, the COMMAND that takes it is printed. This
is the difference between "we don't know" and "here it's zero" — the very
one because of which three headline percentages were recalled.
"""
# 🔴 PROVENANCE MOVED OUT OF THE DOCSTRING ON 2026-09-01 — DOOR VS. JOURNAL.
# The module docstring is a PUBLIC DOOR: `help()` prints it to the reader of
# the published package, and our machine's address tells them nothing. The
# knowledge is not erased — it is here, in the journal, where it belongs:
#     owner's instrument  /opt/kukai-rebuild1/backend/tools/kir_canon_state.py
#     its refusal at home  ls /opt/kukai-rebuild1/backend/kukai/ir
#                     ->  No such file or directory
from __future__ import annotations

import os
import re
import subprocess
import sys

#: The REPOSITORY root and the PACKAGE root are two different quantities,
#: and they must not be confused.
#:
#: 🔴 TAKEN FROM `kir.__file__`, NOT BY STEPS UPWARD FROM THIS FILE (2026-08-28).
#: Two `dirname`s used to stand here — correct as long as the instrument
#: lived in `tools/`. The move to `kir/instruments/` (for the sake of
#: decoupling the boundary) shifted the count by one step, and the
#: instrument went looking for `/opt/kir/kir/kir/CLAUDE.md`. The same class
#: this very instrument measures; counting steps upward is correct for
#: exactly one layout, while the root does not depend on the PACKAGE's
#: location, wherever the instrument itself might move to.
import kir as _kir_pkg

PKG_DIR = os.path.dirname(os.path.abspath(_kir_pkg.__file__))
REPO = os.path.dirname(PKG_DIR)
if REPO not in sys.path:
    sys.path.insert(0, REPO)

PKG = os.path.join(REPO, "kir")
CANON = os.path.join(PKG, "CLAUDE.md")

BEGIN = "<!-- СОСТОЯНИЕ КОМПИЛЯТОРА: НАЧАЛО. Порождается tools/kir_canon_state.py. Не править руками -->"
END = "<!-- СОСТОЯНИЕ КОМПИЛЯТОРА: КОНЕЦ -->"

#: Ceiling of the block. State that does not fit in one's head gets read
#: selectively — and selective reading is exactly the mode in which
#: "already built" goes unnoticed. The instrument REFUSES on overflow
#: rather than truncating.
CHAR_BUDGET = 24000

#: A SAMPLE device id, NOT THE id ITSELF — and this is not a style choice
#: but a fix for the leak that the guard against the leak itself
#: introduced (2026-08-27).
#:
#: 🔴 THE FIRST EDITION OF THIS INSTRUMENT CARRIED THE LITERAL `\ba6d7…ca0\b`
#: and excluded itself from the count. Measured: there were THREE files
#: with this literal in the repository, and the instrument printed TWO —
#: the third was itself. That is, the guard measuring the leak in a
#: repository under Apache-2.0 BECAME A CARRIER OF IT ITSELF and subtracted
#: itself from its own count. The form at home: "a guard whose own
#: existence provides the thing it guards against".
#:
#: 🔴 AND A SECOND REASON, MORE EXPENSIVE THAN THE FIRST (form 54). The
#: literal pins down the SHAPE OF THE FIRST CASE: a SECOND device id
#: landing in the source tomorrow is NEVER found by searching for the
#: first one, and a green result from such a guard reads as "the class is
#: closed". What is being asked is a PROPERTY — "a 32-character hex
#: literal lies in the source outside a digest context" — not the form in
#: which it first appeared.
#:
#: THE COST OF THE SAMPLE IS NAMED, NOT KEPT QUIET: it also catches
#: synthetic test literals (`0123…`), so the count is printed as TWO
#: numbers — code and tests separately. A single number would mix the leak
#: with the fixture, and fixture growth would read as leak growth.
DEVICE_RE = re.compile(r"\b[0-9a-f]{32}\b")

#: Context in which a 32-character hex is a LEGITIMATE digest, not a secret.
_DIGEST_CTX = re.compile(r"sha\d*|digest|hash|md5|blake|checksum|oid|commit",
                         re.IGNORECASE)


def _is_test_path(rel: str) -> bool:
    """Whether this is a test path. ONE holder of the rule for the whole instrument."""
    parts = rel.replace(os.sep, "/").split("/")
    return any(p == "tests" for p in parts) or parts[-1].startswith("test_")


class CanonStateError(RuntimeError):
    """State cannot be issued: either the instrument refused, or the ceiling was breached."""


#: (traversal class, ready graph). The key is the CLASS: a substitution of
#: `capability_graph.Graph` in the control must miss the cache, otherwise
#: the control would be checking the cache.
_GRAPH_CACHE: tuple[type, object] | None = None


def _interpreter() -> str:
    return "%d.%d.%d" % sys.version_info[:3]


def _git(*args: str) -> str:
    try:
        return subprocess.run(("git", *args), cwd=REPO, timeout=10,
                              capture_output=True, text=True,
                              check=True).stdout.strip()
    except Exception:  # noqa: BLE001
        return "?"


def _tree_id() -> str:
    """The BRANCH, and only that. A NUMBER WITHOUT A TREE IS NOT A NUMBER.

    🔴 THE COMMIT WAS REMOVED FROM HERE ON PURPOSE, and this is a fix for a
    ratchet that could never be satisfied. The block LIVES in the file that
    commits it: rewrite the block, commit — and HEAD becomes something
    else, while the block records the previous one. Measured on 15.08:
    recorded `bc6781f3`, HEAD after the commit `3deec0f7`. The ratchet was
    NEVER once green in committed form.

    A red that cannot be cleared stops being read after two or three
    runs — and then the NUMBERS it was set up for quietly rot behind it
    (form 1).
    """
    return _git("rev-parse", "--abbrev-ref", "HEAD")


#: The provenance line — the one that starts with «Снято прибором».
_PROVENANCE_MARK = "Снято прибором"


def comparable(block: str | None) -> str | None:
    """The block WITHOUT the provenance line — what the ratchet is allowed to compare.

    The block has TWO jobs, and only one is subject to guarding: NUMBERS
    (diverged from the code → red) and PROVENANCE (documentation of the
    last run; must be visible and must update, but its movement is not a
    divergence of state).

    That the provenance does not get silently cut out is held by a
    separate test: the line must EXIST and must name the tree.
    """
    if block is None:
        return None
    return "\n".join(line for line in block.splitlines()
                     if not line.startswith(_PROVENANCE_MARK))


def head_short() -> str:
    """The live `HEAD` — for the ratchet's REFUSAL TEXT, not for the block."""
    return _git("rev-parse", "--short", "HEAD")


def _size() -> list[str]:
    """Size of the compiler. It is computed, not rewritten.

    The definition is the same as the canon's before the split, with the
    root swapped: it used to be
    `find kukai/ir -name '*.py' -not -path '*/tests/*'`, now it is the same
    over `kir/`. A definition of its own would give a number of its own,
    and "did it grow" would become indistinguishable from "we measured
    differently".
    """
    lines = files = tests = 0
    for base, dirs, names in os.walk(PKG):
        dirs[:] = [d for d in dirs if d != "__pycache__"]
        in_tests = os.sep + "tests" + os.sep in base + os.sep
        for name in names:
            if not name.endswith(".py"):
                continue
            if in_tests:
                tests += 1
                continue
            files += 1
            with open(os.path.join(base, name), encoding="utf-8",
                      errors="replace") as handle:
                lines += sum(1 for _ in handle)
    # 🔴 THE GRAIN IS DELIBERATELY COARSE. The exact line changes with EVERY
    # edit — and a ratchet that turns red on any edit teaches people to
    # regenerate the block WITHOUT READING it, and thereby kills itself.
    # The signal here is the ORDER OF MAGNITUDE and the NUMBER OF FILES;
    # both survive an edit and turn red on the appearance of a module.
    return ["| размер `kir/` | **~%d тыс. строк** в %d нетестовых `.py`, "
            "плюс %d тестовых (зерно грубое намеренно: точная строка красила "
            "бы храповик на каждую правку) |"
            % (round(lines / 1000), files, tests)]


def _registry() -> list[str]:
    """The registry — belongs to the registry ITSELF, not to its consumers."""
    from kir import spec
    ops = spec.OPS
    writing = [o for o in ops.values() if o.writes_model]
    # 🔴 THE ABSENCE OF AN ANSWER DOES NOT WEAR THE COSTUME OF AN ANSWER
    # (form 29). `except Exception: plural = []` used to stand here, and
    # it printed **0** where the truth was **12**. Now the source is in
    # the REGISTRY, and its absence is a NAMED refusal in the cell itself,
    # not a number.
    kinds = getattr(spec, "PLURAL_OPERAND_KINDS", None)
    if kinds is None:
        plural_cell = ("🔴 НЕ ПОСЧИТАНО: реестр не объявил "
                       "`PLURAL_OPERAND_KINDS` — это не ноль")
    else:
        plural = [o for o in ops.values()
                  if any(p.kind in kinds for p in o.params)]
        plural_cell = "**%d**" % len(plural)
    no_disc = spec.ops_without_discipline(writes=True)
    rows = [
        "| операций в реестре | **%d**, из них пишущих **%d** |" % (len(ops), len(writing)),
        "| с множественным операндом (один оп → много элементов) | %s |" % plural_cell,
        "| видов параметра (`PARAM_KINDS`, закрыт) | **%d** |" % len(spec.PARAM_KINDS),
        "| соло-опов (своя транзакция, `KIR-L002`) | **%d**: %s |"
        % (len(spec.SOLO_OPS), ", ".join("`%s`" % n for n in sorted(spec.SOLO_OPS))),
        "| версионно-хрупких пар (оп, поле) | **%d** |" % len(spec.VERSION_FRAGILE),
        "| пишущих опов БЕЗ выведенного раздела | **%d из %d** |" % (len(no_disc), len(writing)),
    ]
    by_disc = spec.ops_by_discipline(writes=True)
    rows.append("| пишущих по разделам | %s |"
                % " · ".join("%s %d" % (d, len(names)) for d, names in by_disc))
    return rows


def _refusals() -> list[str]:
    """Refusal codes `KIR-*` — BELONG TO THE DISPATCHER, not among the module's attributes.

    🔴 ATTRIBUTE ENUMERATION OVER CAPITALIZED `diag` CONSTANTS USED TO
    STAND HERE, AND THE GAP WAS ONE-SIDED (2026-09-02). Measured on the
    day the dispatcher was set up:

        diag.CODES (registry)             106
        capitalized module constants       67
        in the registry WITHOUT a module constant   39
        constant exists, not in the registry         0

    The zero in the reverse direction is the evidence: attribute
    enumeration is not "slightly behind", it is BLIND TO AN ENTIRE KIND.
    Code registered through `register()` and living as a constant in ITS
    OWN module (`mesh`, `surface`, `ops_boolean`, `ground`, …) is invisible
    to the canon BY CONSTRUCTION, and the gap grows with every new code —
    that is, the block would lie ever more confidently.

    The NAKAZ's point 4, verbatim: a table required to agree with the
    registry must BE the registry from a different angle. A generated
    thing does not need a ratchet — a handwritten one does; here the
    generated thing had stopped being handwritten.

    Found not by me: a neighboring session cross-checked the canon's cell
    against `diag.CODES` right after a restart and filed `E-102`. I
    confirmed all four numbers with my own run before fixing it.
    """
    from kir import diag
    return ["| кодов отказа `KIR-*` у распорядителя | **%d** |" % len(diag.CODES)]


def _atoms() -> list[str]:
    """Reasons an element did not come up. A closed list — reading it is
    faster than guessing what the compiler "cannot do"."""
    from kir.decompile.l1_schema import AtomReason
    members = [m for m in dir(AtomReason) if not m.startswith("_")
               and isinstance(getattr(AtomReason, m), AtomReason)]
    return ["| причин атома (`AtomReason`, закрыт) | **%d** |" % len(members)]


#: A NAMED REACHABILITY REFUSAL. There is one line and it lives here
#: because TWO readers read it: the block itself and the ratchet (which
#: must tell "not counted" apart from a number and must not demand a
#: regeneration for the sake of this cell moving).
REACH_UNAVAILABLE = ("🔴 НЕ ПОСЧИТАНО ЗДЕСЬ: обход достижимости не переведён "
                     "на раскладку `/opt/kir` — это не ноль")


def _reachability() -> list[str]:
    """Reachability — by traversal, and the traversal NAMES ITS OWN CALL (form 26).

    🔴 THE MAIN FIX OF THE PORT, AND IT WAS PAID FOR BY THE 2026-08-27 RUN.

    The owner's instrument called `cg.Graph()` and trusted its
    `disqualified()`. In this tree such trust is FALSE:
    `kir/instruments/capability_graph.py` looks for the roots
    `("kukai", "tools", "scripts")` INSIDE `kir/`, where none of them
    exist — and yet it returns

        modules 123 · alive 0 · disqualified() == ''

    That is, fail-open in its purest form (form 34): a refusal wearing the
    costume of a measurement. Porting it "as is" would have written
    "reachable 0%" into the language canon, and the ratchet would have
    pinned that as the reference — and the next reader would read that
    NOTHING is reachable in the compiler.

    So what is asked here is not the traversal's opinion of itself but a
    CHECKABLE condition: do the roots it is about to traverse exist, and
    did it find even one live point. Not satisfied — a NAMED REFUSAL IN
    THE CELL, not a number.

    The cell will stop refusing on its own on the day the traversal is
    switched over to the package layout. No separate action is needed for
    that, and this is deliberate: an instrument must not require that it
    be remembered.
    """
    cell_missing = ["| модулей проиндексировано / достижимо от точек входа | %s |"
                    % REACH_UNAVAILABLE,
                    "| ворот `*_enabled()` в дереве | %s |" % REACH_UNAVAILABLE]
    try:
        from kir.instruments import capability_graph as cg
    except Exception:  # noqa: BLE001
        return cell_missing

    roots = getattr(cg, "_SOURCE_ROOTS", ())
    base = getattr(cg, "BACKEND", None)
    if not roots or base is None or not any(
            os.path.isdir(os.path.join(str(base), r)) for r in roots):
        # The traversal looks into directories that do not exist in this
        # layout. Its number is a fact about a MISS, not about the tree.
        return cell_missing

    global _GRAPH_CACHE
    if _GRAPH_CACHE is not None and _GRAPH_CACHE[0] is cg.Graph:
        graph = _GRAPH_CACHE[1]
    else:
        graph = cg.Graph()
        _GRAPH_CACHE = (cg.Graph, graph)
    why = graph.disqualified()
    if why:
        raise CanonStateError("состояние не может быть выдано: %s" % why)
    live = graph.live()
    if not live:
        # Zero alive with a non-empty index — either the tree is truly
        # dead (impossible: the language is importable), or the entry
        # points were not ported. The second is more likely, and a silent
        # zero here is more costly than a refusal.
        return cell_missing
    gates: set[str] = set()
    for _name, mod in graph.modules.items():
        if not mod.is_test:
            gates |= set(mod.gate_flags or {})
    return [
        "| модулей проиндексировано / достижимо от точек входа | **%d / %d** (%d%%) |"
        % (len(graph.modules), len(live), 100 * len(live) // max(len(graph.modules), 1)),
        "| ворот `*_enabled()` в дереве | **%d** |" % len(gates),
    ]


#: DIRECTORIES THAT ARE NOT SOURCE. The list is CLOSED: a new runtime
#: directory must be added here by a decision, not leak into the number.
#:
#: 🔴 WHAT THIS COST, 2026-08-18. The traversal picked up `data/`, WHERE
#: THE SERVICE WRITES, and the number grew because the service WRITES,
#: without a single code edit: the ratchet was measuring the MACHINE and
#: turned red on the difference between machines, reading as "the code
#: moved ahead".
#:
#: `build/` and `*.egg-info` were added during the move: `pip install`
#: places a FULL COPY of the package together with the canon into
#: `/opt/kir/build/lib/kir/`, and a repository traversal would count every
#: file TWICE. This is the same class — the count grows from a runtime
#: action (installation), not from a code edit.
_NOT_SOURCE = frozenset({
    "__pycache__", "venv", ".git", "node_modules",
    # below — what the runtime WRITES, not the author
    "data", "runs", ".backups", "logs", "htmlcov", ".pytest_cache",
    "build", "dist", "kir.egg-info",
    # 🔴 `obj/` and `bin/` ARE WRITTEN BY THE .NET BUILD (2026-09-07). On
    # the development machine, `connector/revit/tests/*/obj/Release/…`
    # gave "72 files scanned" (json/cs build artifacts), on a clean clone
    # — 0: a canon taken on one machine turned red on another, reading as
    # "the code moved ahead". Tracked files under `obj/` and `bin/` in the
    # tree: 0 (`git ls-files`), no source lives here.
    "obj", "bin",
    # `test-results/` was written by the Playwright browser acceptance suite
    # (`frontend/standalone/test-results/.last-run.json`) — the same class: a
    # trace of a run, not source. 🔴 13.09.2026: the browser window and that
    # whole tree were removed by the owner's word, so nothing writes this name
    # in the repository today. The entry STAYS: it costs one string, and a
    # directory called `test-results` is a run trace wherever it appears —
    # dropping it would only move the risk to the next tool that writes one.
    "test-results",
    # 🔴 THE SHIFTS' WORKING DIRECTORY. It is not the product and does not
    # ship under the license; see `_is_scratch` — it also explains why
    # this name alone is NOT ENOUGH.
    ".work",
})

#: Names by which a directory is recognized as a FOREIGN environment, not as source.
_VENV_MARKERS = ("pyvenv.cfg",)
_VENV_DIRS = frozenset({"site-packages", "dist-packages", "node_modules", ".venv"})


def _is_environment(base: str) -> bool:
    """Whether this is a foreign environment. What is asked is the KIND, not the name.

    🔴 WHY NOT A LIST OF NAMES (measured 2026-09-07). `_NOT_SOURCE` caught
    `venv` and let `venv-clean` through: a name-based filter misses on the
    very first neighbor that named its directory differently — and the
    vendored `pip/_vendor` went into the traversal whole. An environment
    is recognized by a trait it carries ITSELF: a `pyvenv.cfg` next to it.
    Package directories are cut separately, by `_VENV_DIRS`.
    """
    return any(os.path.exists(os.path.join(base, marker)) for marker in _VENV_MARKERS)


def _tracked_files() -> frozenset | None:
    """Git-tracked files — the definition of the PRODUCT. `None` — git did not answer.

    🔴 WHY A SEPARATE DEFINITION, NOT "EVERYTHING THAT ISN'T SCRATCH". The
    product is what SHIPS, and what ships is the tracked set. Everything
    else (shift scratch, foreign environments, frozen copies of the tree)
    does not go into the license, and counting it together with the
    product means answering the wrong question. `None` is not replaced by
    a guess: the traversal then honestly says it split by PATH, not by
    git.
    """
    # `--cached --others --exclude-standard` — tracked PLUS new files not
    # yet added, but also not ignored. Plain `ls-files` would count a new
    # product file as scratch right up to the commit, meaning a leak in a
    # fresh file would miss the product count exactly when it is
    # introduced. Ignored paths (`.work/`, builds, environments) do not
    # enter here by construction.
    listed = _git("ls-files", "--cached", "--others", "--exclude-standard")
    if listed == "?" or not listed:
        return None
    return frozenset(line for line in listed.splitlines() if line)


#: How many files the traversal must SEE for its zero to be about the
#: tree, not about itself. Measured 2026-08-30: 1010 of the matching kind
#: in `REPO` and 274 `.py` in `PKG`, unreadable 0 and 0. The threshold is
#: set with a fourfold margin downward: it guards against "the traversal
#: did not happen at all" (a torn-off root, an empty filter), not against
#: tree growth, otherwise it would turn red on every test weeding.
_OSS_WALK_FLOOR = 250


def oss_boundary_walk() -> dict:
    """The open-source boundary traversal — and a REPORT ON WHAT WAS NOT WALKED, on a par with what was.

    🔴 PAID FOR BY THE 2026-08-30 AUDIT (E-51): A SKIP SILENTLY SHRANK THE
    DENOMINATOR. The previous edition carried `except OSError: continue`,
    and an unreadable file dropped out of the traversal without a trace.
    The canon's line "id-like literals outside tests: 0" became a fact
    about WHAT COULD BE READ, and read as a fact about the LEAK. Exactly
    the class that has run through the whole marathon: a law converges on
    its own subject and is therefore blind to the neighboring one, and a
    zero looks measured.

    The same rule as the one written for population enumeration:
    "enumerate the population" is useless if the traversal silently skips
    its members. A traversal must report on what it did not walk the same
    way it reports on what it did.

    🔴 THE SECOND TRAVERSAL IS FIXED BY THE SAME MOVE, AND THIS IS NOT
    "WHILE WE'RE AT IT". In `PKG` the file was opened with a BARE `open`
    and no guard: there, an unreadable file brought down the CONSTRUCTION
    OF THE WHOLE CANON, i.e. the same road failed in the opposite extreme
    — not by silence, but by a crash. Both ends are reduced to one rule:
    the name gets recorded, the number gets named, the traversal runs to
    completion.

    Today unreadable is 0 in both, and the skip is therefore inert — the
    guard is set up on the zero on purpose.

    🔴 A THIRD FIX OF THE SAME SPOT, AND IT IS ABOUT THE DENOMINATOR
    (2026-09-07). The traversal went over the WHOLE `REPO` and cut
    directories BY NAME. Measured: 19,346 files, inside `.work/` —
    17,814 (**92.1%**), product — 1,532; `venv` was in the name list, but
    `venv-clean` slipped past it, and the vendored `pip/_vendor` went into
    the traversal whole. The threshold of 250 turned out to be overrun 77
    times over — by garbage, i.e. it had stopped guarding anything. Worse
    than the count was the CONSEQUENCE: the NUMERATOR was inflated too. In
    the non-test line, of 16 hits 11 came from `.work/`, and the one real
    leak (`docs/laws/KIR_MASTER_DESIGN.md:61`) drowned among the false
    ones; in the test line, of 36 hits only 6 were the product's, and 30
    were tree copies and foreign venvs. The instrument was RIGHT, and its
    truth could not be read. So the product and the scratch are counted
    SEPARATELY, and the product is defined by what ships — the git-tracked
    files.
    """
    tracked = _tracked_files()
    hits_all = 0
    files_all: set[str] = set()
    hits_tests = 0
    files_tests: set[str] = set()
    scratch_all = scratch_tests = 0
    scratch_files: set[str] = set()
    seen = seen_scratch = 0
    unreadable: list[str] = []

    def is_product(rel: str) -> bool:
        if tracked is not None:
            return rel in tracked
        # git did not answer — we split by PATH and say so in a report line.
        return not rel.replace(os.sep, "/").startswith(".work/")

    for base, dirs, names in os.walk(REPO):
        dirs[:] = [d for d in dirs
                   if d not in _NOT_SOURCE and d not in _VENV_DIRS]
        if _is_environment(base):
            # A foreign environment as a whole: it belongs to neither the denominator nor the numerator.
            dirs[:] = []
            continue
        for name in names:
            if not name.endswith((".py", ".md", ".json", ".cs")):
                continue
            path = os.path.join(base, name)
            rel = os.path.relpath(path, REPO)
            product = is_product(rel)
            if product:
                seen += 1
            else:
                seen_scratch += 1
            try:
                with open(path, encoding="utf-8", errors="replace") as handle:
                    lines = handle.read().splitlines()
            except OSError as exc:
                unreadable.append("%s (%s)" % (rel, type(exc).__name__))
                continue
            # Counted by LINES, not by the whole file: a digest is
            # filtered out on ITS OWN line, otherwise one `sha256` in the
            # header would amnesty the whole file.
            found = sum(len(DEVICE_RE.findall(line)) for line in lines
                        if not _DIGEST_CTX.search(line))
            if not found:
                continue
            if not product:
                scratch_files.add(rel)
                if _is_test_path(rel):
                    scratch_tests += found
                else:
                    scratch_all += found
            elif _is_test_path(rel):
                hits_tests += found
                files_tests.add(rel)
            else:
                hits_all += found
                files_all.add(rel)
    top_product: list[str] = []
    for base, dirs, names in os.walk(PKG):
        dirs[:] = [d for d in dirs
                   if d not in ("__pycache__", "tests") and d not in _VENV_DIRS]
        for name in names:
            if not name.endswith(".py"):
                continue
            path = os.path.join(base, name)
            seen += 1
            try:
                with open(path, encoding="utf-8", errors="replace") as handle:
                    numbered = list(enumerate(handle, 1))
            except OSError as exc:
                unreadable.append("%s (%s)" % (os.path.relpath(path, REPO),
                                               type(exc).__name__))
                continue
            for num, line in numbered:
                if re.match(r"^from kukai\b|^import kukai\b", line):
                    top_product.append("%s:%d"
                                       % (os.path.relpath(path, REPO), num))
    return {
        "seen": seen,
        "read": seen - len(unreadable),
        "unreadable": sorted(unreadable),
        "hits_all": hits_all, "files_all": sorted(files_all),
        "hits_tests": hits_tests, "files_tests": sorted(files_tests),
        "top_product": sorted(top_product),
        # Scratch is counted SEPARATELY and printed on its own line: it
        # does not ship under the license, and adding it to the product
        # means answering the wrong question. `tracked` = None means git
        # did not answer and the split was done by path.
        "seen_scratch": seen_scratch,
        "scratch_all": scratch_all, "scratch_tests": scratch_tests,
        "scratch_files": len(scratch_files),
        "product_by": "git ls-files" if tracked is not None else "путь (git не ответил)",
    }


def _oss_boundary() -> list[str]:
    """The open-source boundary — BY GREP, not by memory.

    🔴 THE LINE'S SUBJECT CHANGED ALONG WITH THE REPOSITORY, AND THIS IS
    NAMED, NOT LEFT UNSAID. In the owner's tree the traversal went over
    the WHOLE product tree and answered "how many in prod, and of those
    how many in the language area". Here the whole traversal IS the
    language, so the number answers a different, sharper question: **how
    many device identifiers ship under Apache-2.0**. The answer must be 0;
    any other value is a leak, not a debt.

    🔴 THE CAVEAT ABOUT THE UNREAD APPEARS ONLY WHEN IT HAS SOMETHING TO
    SAY (E-51). Zero unreadable is today's state, and printing it as a
    line would mean moving the canon's text for the sake of silence;
    non-zero is a leak the canon must shout about in the very same cell
    where "0" stands. The traversal's denominator does not stay silent
    meanwhile: it is queried as a number from
    `oss_boundary_walk()['seen']`, and a threshold `_OSS_WALK_FLOOR` stands
    against it.
    """
    walk = oss_boundary_walk()
    hits_all, files_all = walk["hits_all"], walk["files_all"]
    hits_tests, files_tests = walk["hits_tests"], walk["files_tests"]
    top_product = walk["top_product"]
    blind = walk["unreadable"]
    caveat = ""
    if blind:
        caveat = (" 🔴 НО ПРОЧИТАНО %d файлов из %d: этот ноль — факт о "
                  "ПРОЧИТАННОМ, а не об утечке. Не прочитаны: %s"
                  % (walk["read"], walk["seen"],
                     ", ".join("`%s`" % b for b in blind[:5])
                     + (" и ещё %d" % (len(blind) - 5) if len(blind) > 5
                        else "")))
    return [
        "| id-подобных литералов в НЕтестовом коде (уезжает под Apache-2.0) | **%d в %d файлах**%s%s |"
        % (hits_all, len(files_all),
           (": " + ", ".join("`%s`" % f for f in files_all)) if files_all else "",
           caveat),
        "| то же в ТЕСТАХ (образец ловит и синтетические — сверять глазами) | **%d в %d файлах**%s |"
        % (hits_tests, len(files_tests),
           (": " + ", ".join("`%s`" % f for f in files_tests)) if files_tests else ""),
        "| верхнеуровневых импортов продукта из `kir/` | **%d**%s |"
        % (len(top_product),
           (": " + ", ".join("`%s`" % t for t in top_product)) if top_product else ""),
        # 🔴 SCRATCH IS PRINTED ON ITS OWN LINE, NOT ADDED TO THE PRODUCT
        # (2026-09-07). While it sat in one number, of 16 non-test hits 11
        # came from `.work/`, and the ONE real leak drowned among the
        # false ones; in the test line, of 36 hits only 6 were the
        # product's. The instrument was right, and its truth could not be
        # read. The product here is what SHIPS (git: tracked plus new,
        # non-ignored files); everything else does not ship and therefore
        # is outside the licensing question.
        "| то же в СКРЭТЧЕ (не уезжает: рабочие каталоги, копии дерева, чужие "
        "окружения) | **%d вне тестов + %d в тестах**, файлов %d, просмотрено %d; "
        "продукт отделён по «%s» |"
        % (walk["scratch_all"], walk["scratch_tests"], walk["scratch_files"],
           walk["seen_scratch"], walk["product_by"]),
    ]


def _machine_dependent() -> list[str]:
    """🔴 NUMBERS DELIBERATELY NOT PRESENT HERE.

    Each one requires a corpus, a live service, or the OWNER'S TREE — that
    is, a property of the machine. The canon must read the same for
    everyone, so a COMMAND stands in place of the number. These are
    exactly the numbers that went stale in the prose — because they had
    been copied there.
    """
    return [
        "", "### Числа, которых здесь НЕТ — и это контракт, а не пробел", "",
        "Требуют КОРПУСА, ЖИВОЙ СЛУЖБЫ либо ДЕРЕВА ХОЗЯИНА. Канон обязан "
        "читаться одинаково у всех, поэтому вместо числа — команда. "
        "**Цитировать прозу вместо прогона нельзя: ровно эти числа протухли "
        "все пять раз.**", "",
        "```",
        "выбранный набор           cd /opt/kir && PYTHONPATH=/opt/kir python3.12 -m pytest -q \\",
        "                              $(python3.12 -c \"import json;print(' '.join('kir/'+p for p in json.load(open('kir/gate_manifest.json'))['набор']))\")",
        "ворота × 6 версий         PYTHONPATH=/opt/kir python3.12 -m kir.gate_runner",
        "                          (нужен ПОРТ ХОЗЯИНА llm.revit_execution_pipeline, не только :52412)",
        "живая доказанность опов   инструмент ХОЗЯИНА: backend/tools/live_op_rates.py",
        "покрытие здания           PYTHONPATH=/opt/kir python3.12 -m kir.instruments.content_coverage <разбор>",
        "офлайновые ворота         PYTHONPATH=/opt/kir python3.12 -m kir.instruments.compile_gate_offline <дир>",
        "состояние флагов в проде  свойство МАШИНЫ ХОЗЯИНА, здесь не спрашивается",
        "```",
    ]


def build() -> str:
    parts: list[str] = [
        BEGIN, "",
        "## СОСТОЯНИЕ КОМПИЛЯТОРА — порождается, руками не править", "",
        "🔴 **Этот блок мутирует, а проза — нет.** Храповик "
        "`kir/tests/test_kir_canon_state_is_current.py` краснеет, когда блок "
        "разошёлся с кодом. Всё, что выше и ниже блока, — ФОРМЫ дефекта: они "
        "не гниют и порождению не подлежат. Всё, что несёт ЧИСЛО, — здесь.", "",
        "Снято прибором `tools/kir_canon_state.py`, интерпретатор **Python %s**, "
        "дерево **%s**. Число без дерева и без вызова — не число (форма 26)."
        % (_interpreter(), _tree_id()), "",
        "| что | сколько |", "|---|---|",
    ]
    for section in (_size(), _registry(), _refusals(), _atoms(),
                    _reachability(), _oss_boundary()):
        parts.extend(section)
    parts.extend(_machine_dependent())
    parts += ["", END]
    text = "\n".join(parts)
    if len(text) > CHAR_BUDGET:
        raise CanonStateError(
            "состояние не помещается в бюджет: %d символов при потолке %d. "
            "Сокращать надо ФОРМУ строки, а не список." % (len(text), CHAR_BUDGET))
    return text


def current_block(path: str = CANON) -> str | None:
    """The block as it currently sits in the file. `None` — there is no block at all.

    A missing block and a matching block are DIFFERENT facts, and the
    first must be visible as a refusal, not as a silent "no discrepancies"."""
    try:
        with open(path, encoding="utf-8") as handle:
            text = handle.read()
    except OSError:
        return None
    if BEGIN not in text or END not in text:
        return None
    return BEGIN + text.split(BEGIN, 1)[1].split(END, 1)[0] + END


def write_into(path: str = CANON) -> bool:
    """Write the block in. `True` — the file changed.

    🔴 THE DIFF IS READ BEFORE `--write` (NAKAZ point 17). Regeneration
    destroys edits made outside the source and kills the signal in one
    move: if what comes with a `+` sign is something YOU measured TODAY,
    that is not a discrepancy, it is your loss.
    """
    block = build()
    with open(path, encoding="utf-8") as handle:
        text = handle.read()
    if BEGIN in text and END in text:
        head, rest = text.split(BEGIN, 1)
        _old, tail = rest.split(END, 1)
        new = head + block + tail
    else:
        # The first insertion is IMMEDIATELY AFTER the file header, before
        # RULE ZERO: state is read before the forms, and it must stand
        # where people look first.
        anchor = "\n---\n"
        if anchor in text:
            head, tail = text.split(anchor, 1)
            new = head + anchor + "\n" + block + "\n" + anchor + tail
        else:
            new = block + "\n\n" + text
    if new == text:
        return False
    with open(path, "w", encoding="utf-8") as handle:
        handle.write(new)
    return True


def main(argv: list[str]) -> int:
    if "--write" in argv:
        changed = write_into()
        print("состояние вписано" if changed else "состояние уже совпадает")
        return 0
    print(build())
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
