"""Content coverage: a denominator that does not lie in either direction.

Document coverage (§18.1) counts ops against ALL elements of the file: on
the RD tower, 29,848 of 310,558 = 9.61%. The number is honest, but it
answers a question nobody asked. Those 310 thousand contain 61,520 zone
boundaries, 38,093 sketch lines, and 19,547 auto-dimensions — traces of
construction that Revit generates ITSELF and that nobody ever "creates".
Counting them in the denominator is the same as measuring a compiler by
the number of temporary variables its own output generates.

You can err here in either direction, and both are expensive:

* leave the whole document as the denominator — and we understate
  ourselves fourfold, and worse, we get an incentive to "raise coverage"
  by starting to read garbage: read 61,520 zone boundaries, passed them
  off as ops — the number grew, the compiler did not move;
* throw everything inconvenient out of the denominator — and get whatever
  percentage you want. This is exactly how a "98% coverage" is born, one
  that later has to be publicly retracted.

So the classification here is a CLOSED TABLE IN CODE, one line per
category, and everything not in it falls LOUDLY into ``UNKNOWN`` (a
separate list with numbers in the report), instead of dissolving into a
convenient class. Disagree with a specific line — fix it and recompute;
you can argue with the classification, but you cannot fail to notice it.

    python tools/content_coverage.py backend/data/decompile/k2_ar_rd_v6
    python tools/content_coverage.py <dir> --json out.json

Three numbers come out, and each answers its OWN question:

* ``model_pct``    — of what IS the building, how much we express;
* ``content_pct``  — of the building and its annotation (both authorial);
* ``document_pct`` — of the whole file (the existing §18.1 metric, for
  cross-checking).

And separately — a breakdown of the gap into two FUNDAMENTALLY different
causes: what we do NOT READ (categories outside the table) and what we
read but CANNOT express. The first is fixed by a line in the category
table, the second by a lifter and an op. Mixing them into one percentage
means not knowing what to do tomorrow.
"""
from __future__ import annotations

import argparse
import collections
import dataclasses
import enum
import json
import pathlib
import sys
from typing import Any

_TOOLS = pathlib.Path(__file__).resolve().parent
if str(_TOOLS.parent) not in sys.path:
    sys.path.insert(0, str(_TOOLS.parent))


class ContentClass(str, enum.Enum):
    """Closed dictionary of category classes."""

    # Building. What KIR must be able to build: structural, envelope,
    # MEP, equipment, spaces, datums.
    MODEL = "model"
    # Annotation. Authorial documentation on top of the model: dimensions,
    # tags, text, details, revision clouds. Expressible in principle, some
    # ops already exist.
    DOCUMENTATION = "documentation"
    # Document organization: views, sheets, schedules, viewports.
    # Authorial, but it is neither the building nor its drawing — it is
    # the table of contents.
    VIEW = "view"
    # Derived. Generated by another element and does not exist
    # separately: sketches, cut-line diagrams, stair runs and landings,
    # the analytical model. Cannot be a denominator by construction — like
    # generator_child in atoms.
    DERIVED = "derived"
    # Service. Settings, project singletons, load definitions, materials
    # as elements, base points. Neither built nor drawn.
    SYSTEM = "system"
    # Not classified. Printed separately as a full list.
    UNKNOWN = "unknown"


_M = ContentClass.MODEL
_D = ContentClass.DOCUMENTATION
_V = ContentClass.VIEW
_G = ContentClass.DERIVED
_S = ContentClass.SYSTEM

# One line per category. Order — by class, alphabetical within a class,
# so an edit shows up in the diff as a single line, not as a reshuffle of
# the table.
#: How many "not classified" lines to print. Not a quality threshold but a
#: readability limit: the rest must be NAMED by a number, not disappear
#: silently.
_UNKNOWN_ROWS_SHOWN = 20

CATEGORY_CLASS: dict[str, ContentClass] = {
    # --- BUILDING ------------------------------------------------------------
    "OST_Areas": _M,
    "OST_Casework": _M,
    "OST_Ceilings": _M,
    "OST_Columns": _M,
    "OST_Conduit": _M,
    "OST_ConduitFitting": _M,
    "OST_CableTray": _M,
    "OST_CableTrayFitting": _M,
    "OST_CurtaSystem": _M,
    "OST_CurtainWallMullions": _M,
    "OST_CurtainWallPanels": _M,
    "OST_Doors": _M,
    "OST_DuctCurves": _M,
    "OST_DuctFitting": _M,
    "OST_DuctInsulations": _M,
    "OST_DuctLinings": _M,
    "OST_DuctTerminal": _M,
    "OST_ElectricalEquipment": _M,
    "OST_ElectricalFixtures": _M,
    "OST_FlexDuctCurves": _M,
    "OST_FlexPipeCurves": _M,
    "OST_FloorOpening": _M,
    "OST_Floors": _M,
    "OST_Furniture": _M,
    "OST_GenericModel": _M,
    "OST_Grids": _M,
    "OST_IOSModelGroups": _M,
    "OST_LightingDevices": _M,
    "OST_LightingFixtures": _M,
    "OST_Levels": _M,
    "OST_Mass": _M,
    "OST_MEPSpaces": _M,
    "OST_MechanicalEquipment": _M,
    "OST_PipeAccessory": _M,
    "OST_PipeCurves": _M,
    # A logical system is an authorial object, not graphics: it has its
    # own operation (create_pipe_system / route_duct_system), so it
    # belongs to the model.
    "OST_PipingSystem": _M,
    "OST_DuctSystem": _M,
    "OST_PlumbingEquipment": _M,
    "OST_PipeFitting": _M,
    "OST_PipeInsulations": _M,
    "OST_PlumbingFixtures": _M,
    "OST_Ramps": _M,
    "OST_Roofs": _M,
    "OST_Rooms": _M,
    # A room separator is drawn by hand, and without it the room cannot be
    # reproduced — this is authorial geometry, not a trace of construction.
    "OST_RoomSeparationLines": _M,
    "OST_SpecialityEquipment": _M,
    "OST_Sprinklers": _M,
    "OST_Stairs": _M,
    "OST_StairsRailing": _M,
    "OST_StructConnections": _M,
    "OST_StructuralColumns": _M,
    "OST_StructuralFoundation": _M,
    "OST_StructuralFraming": _M,
    "OST_StructuralTruss": _M,
    "OST_TelephoneDevices": _M,
    "OST_Topography": _M,
    "OST_Walls": _M,
    "OST_Windows": _M,
    # --- ANNOTATION ------------------------------------------------------------
    "OST_AreaTags": _D,
    "OST_CeilingTags": _D,
    "OST_DetailComponents": _D,
    "OST_Dimensions": _D,
    "OST_DoorTags": _D,
    # DEPENDENCIES (зависимости). The line used to stand in DERIVED and
    # was refuted by the 2026-08-22 measurement, where it was up against
    # `tools/production_technique.py:17,42` («зависимости — прямая
    # параметрика проекта»). The second source won:
    #
    #   * 156 of 156 cached censuses (`data/model_cache/*.census.json`)
    #     give `OST_Constraints.cat_type == "Annotation"`, and for 156 of
    #     156 `types_top` are DimensionType names; for 109 of 156 the
    #     types match the OST_Dimensions types of the SAME document
    #     (`ADSK_Основной_2.5 мм`, `ГОСТ_2_Фон`). The dimension style is
    #     set by the designer, not by Revit;
    #   * the MIRROR-RATIO test — the one and only method by which the
    #     DERIVED class is justified below for centerlines (3051 pipe /
    #     3051 centerline) — does NOT pass for this category: equality
    #     with OST_Dimensions zero times out of 156, MORE dimensions in 38
    #     of 156, maximum ratio 17.756. A generated thing is never, by
    #     construction, sixteen times larger than its carrier;
    #   * on MNVNK, 1,256 dependencies against 745 dimensions (1.686), on
    #     K2 — 867 against 13,905 (0.062). A 27-fold spread between two
    #     buildings is the author's signature, not Revit's mechanics.
    #
    # THE COST OF THE FIX IS NAMED: on MNVNK the CONTENT denominator grows
    # 33,360 -> 34,616, content coverage falls 57.08% -> 55.01%
    # (−2.07 p.p.), the line «оформление не читается вовсе» grows 924 ->
    # 2,180.
    #
    # WHAT THIS LINE DOES NOT CLAIM: how many of the 1,256 actually HOLD
    # geometry (`Dimension.IsLocked`, `References` to model elements).
    # Identifiers of these elements are not in the decompile at all — the
    # category is not in `EXTRACT_CATEGORIES` — so the question is
    # settled by one live query, not from here. `IsLocked` is never read
    # in `kukai/` (0 occurrences).
    "OST_Constraints": _D,
    "OST_EditCutProfile": _D,
    "OST_FloorTags": _D,
    "OST_GenericAnnotation": _D,
    "OST_IOSDetailGroups": _D,
    # 2026-08-22: the third group category. There was no line, and 52 of
    # its MNVNK elements were printed into UNKNOWN — even though
    # `group.index.json` reads them ON A PAR with its two neighbors
    # (575 instances = 368 + 155 + 52, an exact match). Same class as
    # `OST_IOSDetailGroups`: an attached detail group consists of detail
    # elements, not of the building.
    "OST_IOSAttachedDetailGroups": _D,
    "OST_LegendComponents": _D,
    # Detail lines and model lines in one category. Classified as
    # annotation by majority use in real construction drawings; if a model
    # MODELS with lines, the line must be edited — that's exactly what
    # having a line (in the table) is for.
    "OST_Lines": _D,
    "OST_MaterialTags": _D,
    "OST_MEPSpaceTags": _D,
    "OST_PipeTags": _D,
    "OST_PlumbingEquipmentTags": _D,
    "OST_MechanicalEquipmentTags": _D,
    "OST_MultiCategoryTags": _D,
    "OST_RasterImages": _D,
    "OST_RevisionClouds": _D,
    "OST_RevisionCloudTags": _D,
    "OST_RoomTags": _D,
    "OST_SpotElevations": _D,
    "OST_SpotSlopes": _D,
    "OST_StairsRailingTags": _D,
    "OST_StructuralFramingTags": _D,
    "OST_TextNotes": _D,
    "OST_TitleBlocks": _D,
    "OST_WallTags": _D,
    "OST_WindowTags": _D,
    # --- DOCUMENT ORGANIZATION --------------------------------------------
    "OST_BranchPanelScheduleTemplates": _V,
    "OST_Cameras": _V,
    "OST_ColorFillSchema": _V,
    "OST_DataPanelScheduleTemplates": _V,
    "OST_Elev": _V,
    "OST_GuideGrid": _V,
    "OST_HVAC_Load_Schedules": _V,
    "OST_PlanRegion": _V,
    "OST_Revisions": _V,
    "OST_RevisionNumberingSequences": _V,
    "OST_Schedules": _V,
    "OST_SectionBox": _V,
    "OST_Sheets": _V,
    "OST_SwitchboardScheduleTemplates": _V,
    "OST_Viewports": _V,
    "OST_Views": _V,
    "OST_VolumeOfInterest": _V,
    # --- DERIVED ---------------------------------------------------------------
    "OST_AnalyticalMember": _G,
    "OST_AnalyticalNodes": _G,
    "OST_AreaSchemeLines": _G,
    # CENTERLINES are pure mirrors: in the Snowdon sample there are
    # EXACTLY as many of them as carriers (3051 pipes / 3051 centerlines,
    # 2651 fittings / 2651 centerlines). Such a category cannot be
    # anything but derived, by construction: Revit draws it from the
    # carrier, and it has no operation of its own.
    "OST_PipeCurvesCenterLine": _G,
    "OST_PipeFittingCenterLine": _G,
    "OST_DuctCurvesCenterLine": _G,
    "OST_DuctFittingCenterLine": _G,
    "OST_FlexPipeCurvesCenterLine": _G,
    "OST_FlexDuctCurvesCenterLine": _G,
    "OST_ConduitCenterLine": _G,
    "OST_CableTrayCenterLine": _G,
    "OST_CurtainGrids": _G,
    "OST_CurtainGridsCurtaSystem": _G,
    "OST_CurtainGridsRoof": _G,
    "OST_CurtainGridsWall": _G,
    "OST_IOSSketchGrid": _G,
    "OST_PreviewLegendComponents": _G,
    "OST_RailingRailPathExtensionLines": _G,
    "OST_RailingTopRail": _G,
    "OST_ScheduleGraphics": _G,
    "OST_SketchLines": _G,
    "OST_StairsLandings": _G,
    "OST_StairsPaths": _G,
    "OST_StairsRailingBaluster": _G,
    "OST_StairsRuns": _G,
    "OST_StairsSketchBoundaryLines": _G,
    "OST_StairsSketchPathLines": _G,
    "OST_StairsSketchRiserLines": _G,
    "OST_TopographyContours": _G,
    "OST_Viewers": _G,
    "OST_WeakDims": _G,
    # --- SERVICE ---------------------------------------------------------------
    "OST_AreaSchemes": _S,
    "OST_CLines": _S,
    "OST_CoordinateSystem": _S,
    "OST_ElectricalDemandFactorDefinitions": _S,
    "OST_ElectricalLoadClassifications": _S,
    "OST_ElectricalLoadZoneType": _S,
    "OST_HVAC_Load_Building_Types": _S,
    "OST_HVAC_Load_Space_Types": _S,
    "OST_HVAC_Zones": _S,
    "OST_IOSArrays": _S,
    "OST_IOS_GeoLocations": _S,
    "OST_LoadCases": _S,
    "OST_Materials": _S,
    "OST_ParamElemElectricalLoadClassification": _S,
    "OST_Phases": _S,
    "OST_PipeSegments": _S,
    "OST_ProjectBasePoint": _S,
    "OST_ProjectInformation": _S,
    "OST_PropertySet": _S,
    "OST_RvtLinks": _S,
    "OST_SharedBasePoint": _S,
    "OST_SunStudy": _S,
    # AN ELEMENT WITHOUT A CATEGORY — THE DOCUMENT'S LARGEST LINE, AND NO
    # INSTRUMENT KNOWS WHAT IS IN IT (measured 2026-08-22).
    #
    # Here it used to say: «53 885 штук на РД-башне — виды изнутри,
    # эскизные плоскости, служебное». This was a GUESS labeled as a
    # composition, and the MNVNK census refutes it on both named kinds:
    # views have their own keys (`OST_Views` 157, `OST_Viewers` 31,
    # `OST_Viewports` 270), reference and sketch planes too (`OST_CLines`
    # 1,474, `OST_IOSSketchGrid` 140, `OST_SketchLines` 6,504). All these
    # elements HAVE a category, meaning they are not in `no_category`.
    #
    # WHAT IS MEASURED PRECISELY. MNVNK: 20,898 of 75,936 = 27.52% of the
    # document and 49.77% of everything unread — the largest key in the
    # census, 1.96 times larger than the walls. K2: 53,885 of 310,558 =
    # 17.35%. Across the corpus the share ranges from 14.52%
    # (`k4_geom_wave_15aug`) to 67.49% (`sklnk_eom_r26_v10`). The
    # `category_read_failed` key (introduced 12.08, `census.py:59`) is
    # ABSENT in these runs, meaning this is an honest "Revit has no
    # category here", not a swallowed access refusal.
    #
    # 🔴 A LIVE QUERY WAS MADE ON 2026-08-22, AND THE COMPOSITION IS
    # NAMED. The line above required holding UNKNOWN until it was done; it
    # was carried out on MNVNK
    # (`FilteredElementCollector.WhereElementIsNotElementType()`, grouped
    # by `GetType().Name` and `Name`), the answer's control check
    # matched: total 75,936, without category 20,898, `Element.Category`
    # never threw.
    #
    #    11,597  Element                 base class: settings and definitions
    #     4,869  SketchPlane             SKETCH PLANES
    #     2,576  GraphicsStyle
    #       735  Sketch
    #       307  SharedParameterElement · 278 FillPatternElement
    #       150  Family (definitions) · 121 ParameterFilterElement
    #        94  LinePatternElement · 61 AppearanceAssetElement · … 47 classes
    #
    # The samples are ids 0..14, the lowest in the document: «Информация о
    # стадии проекта», «Системные данные», «Параметры начального вида»,
    # «Параметры экрана совместной работы». This is Revit's machinery, not
    # content.
    #
    # 🔴 THE DECISIVE NUMBER IS NOT THE CLASS NAMES BUT A MECHANICAL
    # TRAIT: of the 20,898, only 22 (0.11%) CARRY GEOMETRY, 6,873 carry a
    # location (these are sketch planes, they have a plane). Classifying
    # by class name would be a judgment; "does the element have geometry"
    # is a measurement. The honest remainder of the question here is not
    # 20,898, but TWENTY-TWO.
    #
    # 🔴 AND ONE CORRECTION TO THE REFUTATION ABOVE. The earlier guess
    # named two kinds — «виды изнутри» and «эскизные плоскости». About the
    # views, the refutation is correct: they have their own keys. About
    # the sketch planes it is WRONG, and here is why: what was checked
    # were CATEGORIES (`OST_IOSSketchGrid`, `OST_SketchLines`), while a
    # sketch plane is the CLASS `SketchPlane`, which has no category at
    # all. It is indeed in `no_category`, second by count. The guess was
    # half right, and it was refuted by an instrument looking at the
    # wrong thing.
    #
    # Class SERVICE, not UNKNOWN: 20,876 of 20,898 carry no geometry at
    # all. The `content_pct_lower_bound` lower bound stops resting on the
    # unknown — it now rests on a measurement.
    "no_category": ContentClass.SYSTEM,

    # --- ADDED 2026-08-13 -----------------------------------------------
    # 68 names encountered in the corpus that had no line. Classified BY
    # EYE, not by suffix, and the suffix would have given a different
    # answer at least three times: `OST_AnalyticSurfaces` (3041) looks
    # like building surfaces, but it is the ANALYTICAL model, generated by
    # the physical one; `OST_RailingSupport` (2608) is not an independent
    # building element, it is part of the railing;
    # `OST_MEPLoadAreaSeparationLines` asks to be annotation by its
    # `Lines` suffix, but a precedent already stands in this same table —
    # `OST_RoomSeparationLines` is assigned to BUILDING because it is
    # drawn by hand and without it the space cannot be reproduced.
    # Disputed lines are fixed one at a time; that's exactly what lines
    # are for.
    # BUILDING
    "OST_Cornices": _M,
    "OST_DataDevices": _M,
    "OST_ElectricalCircuit": _M,
    "OST_ElectricalLoadZoneInstance": _M,
    "OST_Entourage": _M,
    "OST_FoodServiceEquipment": _M,
    "OST_Hardscape": _M,
    "OST_MEPLoadAreaSeparationLines": _M,
    "OST_MEPLoadAreas": _M,
    "OST_MEPSpaceSeparationLines": _M,
    "OST_MultistoryStairs": _M,
    "OST_Parking": _M,
    "OST_Planting": _M,
    "OST_RoofOpening": _M,
    "OST_SWallRectOpening": _M,
    "OST_ShaftOpening": _M,
    "OST_Site": _M,
    "OST_SiteProperty": _M,
    "OST_SitePropertyLineSegment": _M,
    "OST_VerticalCirculation": _M,
    "OST_Wire": _M,
    # ANNOTATION
    "OST_ConduitTags": _D,
    "OST_ELECTRICAL_AreaBasedLoads_Tags": _D,
    "OST_ElectricalEquipmentTags": _D,
    "OST_ElectricalFixtureTags": _D,
    "OST_GenericModelTags": _D,
    "OST_InsulationLines": _D,
    "OST_KeynoteTags": _D,
    "OST_LightingFixtureTags": _D,
    "OST_ParkingTags": _D,
    "OST_PathOfTravelLines": _D,
    "OST_PathOfTravelTags": _D,
    "OST_PlantingTags": _D,
    "OST_RoofTags": _D,
    "OST_SitePropertyLineSegmentTags": _D,
    "OST_SpecialityEquipmentTags": _D,
    "OST_SpotElevSymbols": _D,
    "OST_WireTags": _D,
    # DOCUMENT ORGANIZATION
    "OST_CalloutHeads": _V,
    "OST_ColorFillLegends": _V,
    "OST_ElevationMarks": _V,
    "OST_GridHeads": _V,
    "OST_LevelHeads": _V,
    "OST_PanelScheduleGraphics": _V,
    "OST_PanelSchedules": _V,
    "OST_ReferenceViewerSymbol": _V,
    "OST_SectionHeads": _V,
    "OST_ViewportLabel": _V,
    # DERIVED
    "OST_AdaptivePoints": _G,
    "OST_AnalyticSpaces": _G,
    "OST_AnalyticSurfaces": _G,
    "OST_CableTrayRun": _G,
    "OST_ConduitFittingCenterLine": _G,
    "OST_ConduitRun": _G,
    "OST_EdgeSlab": _G,
    "OST_ElectricalAnalyticalTransformer": _G,
    "OST_MEPAnalyticalBus": _G,
    "OST_Parts": _G,
    "OST_RailingHandRail": _G,
    "OST_RailingSupport": _G,
    "OST_StairsSketchLandingCenterLines": _G,
    "OST_StairsSketchRunLines": _G,
    "OST_StairsStringerCarriage": _G,
    # SERVICE
    "OST_DesignOptionSets": _S,
    "OST_DesignOptions": _S,
    "OST_Divisions": _S,
    "OST_ElectricalCircuitNaming": _S,
    "OST_ElectricalPowerSource": _S,
}

# Keys of the EXTRACTION table that are not in the census as separate
# categories: the census keys by BuiltInCategory, while these two
# collectors key by element class. Their elements are already counted by
# the census within their own categories, so they are not added to the
# denominator, but they must not get lost either.
COLLECTOR_ALIASES = {"DirectShape", "ImportInstance"}


def classify(key: str) -> ContentClass:
    return CATEGORY_CLASS.get(key, ContentClass.UNKNOWN)


#: 🔴 THE SNAPSHOT IS READ THROUGH `snapshot_io`, NOT A BARE `open`
#: (2026-08-19). The cleaner compresses SIX names
#: (`snapshot_janitor.SNAPSHOT_FILES`): `L0.jsonl` and five side indexes.
#: `status.json` and `tree.json` are NOT among them, so they are read as
#: before — a fix by the cleaner's list, not by habit.
#:
#: THE COST HERE IS WORSE THAN A REFUSAL, AND THAT IS WHY THIS IS NOT
#: COSMETIC. A compressed `L0.jsonl` would crash the instrument with a
#: `FileNotFoundError` — loudly. But a compressed SIDE INDEX would read as
#: ABSENT, that is, quietly: `side_indexes` is a condition for the
#: comparability of runs, and `comparable()` would declare two identical
#: runs incomparable, and an incomplete one complete. Exactly the disease
#: these conditions were set up against: 27 points of facade were a
#: difference in RUN COMPLETENESS, read as a compiler win.
#:
#: `touch=False`: by default `open_snapshot` writes `.last_access` into
#: the decompile directory, meaning the measurement would date the thing
#: being measured. Two of our censuses are already poisoned by this — the
#: scene cache and the corpus dating.
def _snap_open(path: pathlib.Path):
    from kir.decompile.snapshot_io import open_snapshot
    return open_snapshot(path, "rt", encoding="utf-8", touch=False)


def _snap_exists(path: pathlib.Path) -> bool:
    from kir.decompile.snapshot_io import snapshot_file_exists
    return snapshot_file_exists(path)


def _header(directory: pathlib.Path) -> dict[str, Any]:
    with _snap_open(directory / "L0.jsonl") as handle:
        return json.loads(handle.readline())


def _census(header: dict[str, Any], directory: pathlib.Path) -> list[dict[str, Any]]:
    census = header.get("document", {}).get("census")
    if not census:
        raise SystemExit(
            f"{directory.name}: переписи нет — слепок снят до §18.1, "
            "содержательное покрытие для него не определено")
    return census


def _extracted_by_collector(directory: pathlib.Path) -> dict[str, int]:
    """How many elements are actually read, by collector."""
    counts: collections.Counter[str] = collections.Counter()
    with _snap_open(directory / "L0.jsonl") as handle:
        handle.readline()
        for line in handle:
            # A cheap check before parsing: there are tens of thousands of
            # lines here.
            if '"record": "element"' not in line and '"record":"element"' not in line:
                continue
            record = json.loads(line)
            if record.get("record") != "element":
                continue
            counts[record.get("collector") or "no_category"] += 1
    return dict(counts)


# ═════════════════════════════════════════════════════════════════════════
# METRIC BLINDNESS: "READ" WAS ASKED OF ONE READER OUT OF TWO
#
# WHAT IT WAS. `_extracted_by_collector` counts as read ONLY what has an
# entry in `L0.jsonl` with a `collector` field. Side stages of the
# pipeline write their own indexes, and the metric never asked them at
# all. A category read entirely by a side stage looked like zero in the
# report — that is, exactly like "not read at all".
#
# THE COST WAS MEASURED ON MNVNK (2026-08-22), 623 elements, two exact
# matches:
#
#   OST_IOSModelGroups 368 + OST_IOSDetailGroups 155
#   + OST_IOSAttachedDetailGroups 52 = 575
#       sit in `group.index.json` -> group_index.instances = 575
#   OST_StairsRuns 48
#       sit in `sketch.index.json` -> stairs_run_path_index:
#       24 stairs, 48 runs
#
# The match is EXACT in both cases (575 = 575, 48 = 48), so nothing here
# is estimated or divided proportionally: attribution is either
# arithmetically unambiguous, or not done at all (see `attributed`).
#
# THREE LINES IN THE TREE WERE WRONG BECAUSE OF THIS, and this is not a
# typo but a consequence: an instrument that does not ask the second
# reader produces the prose "we don't read this" for anyone who looks at
# it.
#
# THE BOUNDARY. The unit here is not a category but a side stage's UNIT OF
# READING: `group_index.instances` does not store the instance's category
# at all (11 fields, none about category), so 575 instances belong to a
# TRIO of categories at once. Splitting them across three lines is
# possible exactly because the census sum over the trio equals 575
# exactly; if it does not match, the unit honestly stays unattributed
# (`attributed: false`), and this is printed, not smoothed over.
@dataclasses.dataclass(frozen=True)
class SideIndexRead:
    """One unit of reading for a side stage.

    `path` — path inside the decompiled json down to the CONTAINER of
    records. `key_level` — at what level the records themselves sit: 1 —
    the container's own keys (`{id: record}`), 2 — keys of nested dicts
    (`{owner: {id: ...}}`). The level is named by a number, not guessed
    from shape: a dict of dicts and a dict of records differ only in WHAT
    WE KNOW ABOUT THEM.
    """

    stage: str
    filename: str
    path: tuple[str, ...]
    key_level: int
    categories: tuple[str, ...]
    note: str


#: What the side stages read beyond L0. A line is added ONLY under a
#: measurement: each one below is checked against the MNVNK census by
#: exact equality.
SIDE_INDEX_READS: tuple[SideIndexRead, ...] = (
    SideIndexRead(
        stage="group", filename="group.index.json",
        path=("group_index", "instances"), key_level=1,
        categories=("OST_IOSModelGroups", "OST_IOSDetailGroups",
                    "OST_IOSAttachedDetailGroups"),
        note="экземпляры групп; категории в индексе нет, атрибуция держится "
             "на точном равенстве 368+155+52 = 575"),
    SideIndexRead(
        stage="sketch", filename="sketch.index.json",
        path=("stairs_run_path_index",), key_level=2,
        categories=("OST_StairsRuns",),
        note="пути маршей: {лестница: {марш: путь}}, 24 лестницы / 48 маршей"),
)


def _dig(payload: Any, path: tuple[str, ...]) -> Any:
    for key in path:
        if not isinstance(payload, dict):
            return None
        payload = payload.get(key)
    return payload


def _side_index_read_counts(
        directory: pathlib.Path, census: list[dict[str, Any]],
        extracted: dict[str, int],
) -> tuple[dict[str, int], list[dict[str, Any]]]:
    """{category: read by a side stage}, plus rows of reading units.

    Attribution by category is done ONLY when it is arithmetically
    unambiguous; in every other case the unit stays in the report as its
    own number with `attributed: false`. Not a single element split in
    half.
    """
    counts = {row["key"]: int(row.get("count", 0)) for row in census}
    by_category: dict[str, int] = {}
    units: list[dict[str, Any]] = []
    for unit in SIDE_INDEX_READS:
        path = directory / unit.filename
        row: dict[str, Any] = {
            "stage": unit.stage,
            "categories": list(unit.categories),
            "census": sum(counts.get(c, 0) for c in unit.categories),
            "note": unit.note,
        }
        if not _snap_exists(path):
            # "no index" and "index is empty" are different facts; a zero
            # here would mean "the stage read zero", while the stage never
            # ran.
            row.update({"present": False, "read": None, "attributed": False,
                        "why": "бокового индекса у прогона нет"})
            units.append(row)
            continue
        with _snap_open(path) as handle:
            payload = json.load(handle)
        container = _dig(payload, unit.path)
        if not isinstance(container, dict):
            row.update({"present": True, "read": None, "attributed": False,
                        "why": f"путь {'/'.join(unit.path)} не словарь"})
            units.append(row)
            continue
        if unit.key_level == 1:
            read = len(container)
        else:
            read = sum(len(v) for v in container.values()
                       if isinstance(v, dict))
        row.update({"present": True, "read": read})
        # THE OVERLAP WITH L0 IS NAMED, NOT ADDED. A category read by both
        # the collector and a side stage is the same elements counted
        # twice; a sum would silently inflate "read".
        overlapping = [c for c in unit.categories if extracted.get(c, 0) > 0]
        if overlapping:
            row.update({"attributed": False,
                        "why": "категории уже читаются коллектором L0 "
                               f"({', '.join(sorted(overlapping))}) — "
                               "складывать значило бы считать их дважды"})
            units.append(row)
            continue
        if len(unit.categories) == 1:
            category = unit.categories[0]
            # 🔴 THIS USED TO BE `min(read, counts.get(category, read))` —
            # A CLAMP AFTER WHICH THE INSTRUMENT COULD NEVER TURN RED (fix
            # 2026-08-29, F-100).
            #
            # `read > census` means a side unit read MORE elements than
            # the census says exist at all. This is a discrepancy BETWEEN
            # TWO SOURCES, and it demands eyes: either the census
            # understates, or the unit is counting the wrong thing. `min`
            # silently chose the census — and the coverage was printed as
            # exactly the number expected of it, no matter the overflow.
            #
            # The neighboring branch of the same `if/elif` ALREADY DOES
            # this check (`read == row["census"]`), meaning the author
            # knew the shape of the right answer and applied it to
            # multi-part units but not to single-part ones. Here is the
            # same answer, in the same shape: we do not attribute, and we
            # NAME it.
            census_here = counts.get(category)
            if census_here is None or read <= census_here:
                by_category[category] = read
                row.update({"attributed": True})
            else:
                row.update({"attributed": False,
                            "why": f"единица читает {read}, а перепись "
                                   f"категории «{category}» даёт "
                                   f"{census_here}: прочитано БОЛЬШЕ, чем "
                                   f"есть — это расхождение двух источников, "
                                   f"а не покрытие"})
        elif read == row["census"] and read > 0:
            for category in unit.categories:
                by_category[category] = counts.get(category, 0)
            row.update({"attributed": True})
        else:
            row.update({"attributed": False,
                        "why": f"единица читает {read}, а перепись по её "
                               f"{len(unit.categories)} категориям даёт "
                               f"{row['census']}: раскладывать нечем, кроме "
                               "догадки"})
        units.append(row)
    return by_category, units


def _side_index_names() -> tuple[tuple[str, str], ...]:
    """The list of side indexes — held by WHOEVER LOADS THEM, not a second
    copy of our own.

    `relift_offline._SIDE_INDEX_FILES` is the single place where this list
    is maintained, and the lift enters through exactly that. A list of our
    own here would diverge from it at the very first new stage, and it
    would diverge SILENTLY: a missing name would look like "this run has
    no such index".
    """
    from kir.instruments.relift_offline import _SIDE_INDEX_FILES
    return tuple(_SIDE_INDEX_FILES)


#: Read lazily, so that `content_coverage` stays importable without the
#: instruments nearby; an import error is an exception, not an empty
#: list.
_SIDE_INDEX_NAMES = _side_index_names()


def _conditions(directory: pathlib.Path, census: list[dict[str, Any]],
                extracted: dict[str, int]) -> dict[str, Any]:
    """The conditions under which this run's percentage is at all
    comparable to another's.

    We ask AUTHORITIES rather than add a field: the extraction table knows
    what we can read; the §18.1 census knows what is in the document; `L0`
    knows what was actually read. The intersection of the first two, minus
    the third, is exactly "we could read it, the document had it, we
    didn't read it".

    `category_outside_table` is deliberately excluded from here: it is a
    known and named gap, and this metric exists precisely to describe it.
    The dangerous case is the other one — a category that IS IN THE TABLE,
    and it was not visible anywhere before 12.08.
    """
    try:
        from kir.decompile.extract import _CATEGORY_SPECS
        table = {spec.name for spec in _CATEGORY_SPECS}
    except Exception:                                          # noqa: BLE001
        # There is no table — the conditions are UNKNOWN, and that is a
        # different fact from "there are no conditions". An empty dict
        # here would read as "everything was read".
        return {"table_available": False}
    unread = {row["key"]: int(row.get("count", 0)) for row in census
              if row.get("key") in table and int(row.get("count", 0)) > 0
              and extracted.get(row.get("key"), 0) == 0}
    status_path = directory / "status.json"
    scanned = None
    if status_path.is_file():
        try:
            scanned = int(json.loads(status_path.read_text(encoding="utf-8"))
                          .get("categories_scanned"))
        except Exception:                                      # noqa: BLE001
            scanned = None
    return {
        "table_available": True,
        "categories_scanned": scanned,
        "in_table_unread": dict(sorted(unread.items())),
        "in_table_unread_elements": sum(unread.values()),
        # ═══ SIDE INDEXES — A CONDITION OF THE SAME RANK AS UNREAD
        # CATEGORIES, and before 12.08 `comparable()` never looked at
        # them.
        #
        # They decide what the lifter CAN LIFT AT ALL: without
        # `family_placement.index.json` every family instance is an atom,
        # without `dimension.index.json` dimensions never come up at all.
        # A run that broke off during the side stages honestly passes the
        # check on unread categories (its census is complete!) while
        # expressing LESS — simply because the lifter has nothing to work
        # with.
        #
        # THE REASON IS NAMED IN ADVANCE, NOT AFTER THE BITE: `k2_ar_rd_v15`,
        # the run all our coverage numbers are taken from, finished with
        # `stage="error"` and WITHOUT `mep_system`, `tag`, `dimension`. A
        # live decompile runs to the end, through all stages. Comparing
        # the live one to `v15` would have passed the old `comparable()`
        # and shown a difference that would be read as a compiler win —
        # when it is a difference in RUN COMPLETENESS. Exactly 27 points
        # of facade, a second time, and in the most important comparison.
        "side_indexes": sorted(
            name for name, filename in _SIDE_INDEX_NAMES
            if _snap_exists(directory / filename)),
        # WHAT A MISSING INDEX COSTS — IN ELEMENTS, NOT IN THE BARE FACT
        # (2026-08-13). `comparable()` used to compare the PRESENCE of a
        # file and reject a run for a stage that was not run and had
        # NOTHING to capture: `snowdon_plumb_v4` has no `dimension`, and
        # `OST_Dimensions` has zero elements — "the stage was not run" and
        # "the stage had nothing to capture" are ONE fact, and telling
        # them apart means refusing on a trait that does not affect the
        # subject.
        #
        # `None` instead of zero where a stage has no line in
        # `_STAGE_CATEGORIES` (`geometry` — it writes a bundle, not an
        # index): an empty set of categories gives a zero
        # INDISTINGUISHABLE from "nothing to read", and that zero would
        # mean "comparable" out of sheer ignorance.
        "side_index_pending": _pending_by_stage(directory, census),
    }


def _pending_by_stage(directory: pathlib.Path,
                      census: list[dict[str, Any]]) -> dict[str, int | None]:
    """{stage without an index: how many elements of its categories ARE IN
    THE CENSUS}.

    `None` = the stage has no line in `_STAGE_CATEGORIES`, meaning what it
    reads is unknown, and a zero here would be an assertion, not a
    measurement.
    """
    from kir.decompile.pipeline import _STAGE_CATEGORIES

    counts = {row["key"]: row["count"] for row in census
              if isinstance(row.get("count"), int)}
    pending: dict[str, int | None] = {}
    for name, filename in _SIDE_INDEX_NAMES:
        if (directory / filename).is_file():
            continue
        cats = _STAGE_CATEGORIES.get(name)
        pending[name] = (None if not cats
                         else sum(counts.get(c, 0) for c in cats))
    return pending


def comparable(left: dict[str, Any], right: dict[str, Any]) -> tuple[bool, str]:
    """Whether two reports are comparable. A REFUSAL NAMES BOTH QUANTITIES.

    The spread across buildings is what speaks about the compiler; but it
    speaks about it ONLY if the runs read the same set of categories.
    Otherwise what is being compared is reading completeness under the
    compiler's name, and that is exactly the case that cost 27 points
    across two revisions of the same facade.
    """
    a = (left.get("conditions") or {}).get("in_table_unread")
    b = (right.get("conditions") or {}).get("in_table_unread")
    if a is None or b is None:
        return False, ("условия одного из отчётов неизвестны (нет таблицы "
                       "извлечения) — сравнивать нечего с чем")
    if set(a) != set(b):
        only_left = sorted(set(a) - set(b))
        only_right = sorted(set(b) - set(a))
        return False, (
            "прогоны прочитали РАЗНЫЕ множества категорий, поэтому их "
            "проценты несопоставимы: "
            f"не прочитано только у первого {only_left or '—'}, "
            f"только у второго {only_right or '—'}. "
            "Одна такая категория стоила 27 пунктов на двух ревизиях одного "
            "здания (12.08.2026): её элементы позволяют лифтеру опознать "
            "порождённых детей, которых честная цифра ИСКЛЮЧАЕТ, и падает "
            "ЗНАМЕНАТЕЛЬ, а не растёт числитель")
    # THE SECOND CONDITION, OF THE SAME RANK. The census may be complete
    # for both, while the lifter for one has nothing to work with: a side
    # index decides whether lifting is POSSIBLE AT ALL. A run that broke
    # off during the side stages honestly passes the first check and
    # expresses less — not because the compiler is worse.
    sa = (left.get("conditions") or {}).get("side_indexes")
    sb = (right.get("conditions") or {}).get("side_indexes")
    if sa is None or sb is None:
        return False, ("набор боковых индексов у одного из отчётов неизвестен "
                       "(снят прибором до 12.08) — сравнивать нечего с чем")
    # THE ABSENCE OF AN INDEX MATTERS ONLY IF THERE WAS SOMETHING TO READ
    # (2026-08-13). A stage without an index, whose categories the census
    # gives as ZERO, is equivalent to one that is present-and-empty — the
    # corpus has such an index (`mep_system` with zero lines) and its
    # comparison passes. Rejecting for it means refusing on a trait that
    # does not affect the subject.
    #
    # BOUNDARY: `None` (the stage has no line in `_STAGE_CATEGORIES`) is
    # NOT counted as empty. Not knowing what a stage reads is not proof
    # there was nothing to read.
    pa = (left.get("conditions") or {}).get("side_index_pending") or {}
    pb = (right.get("conditions") or {}).get("side_index_pending") or {}
    effective_a = set(sa) | {k for k, v in pa.items() if v == 0}
    effective_b = set(sb) | {k for k, v in pb.items() if v == 0}
    if effective_a != effective_b:
        # A refusal must name the COST, not just the name: "no dimension"
        # does not say whether the loss is large — 13,905 elements or
        # zero.
        def _cost(names, pending):
            return ", ".join(
                f"{n} ({pending.get(n)} эл. в переписи)"
                if pending.get(n) is not None
                else f"{n} (сколько читает — НЕИЗВЕСТНО, строки в "
                     f"_STAGE_CATEGORIES нет)"
                for n in sorted(names)) or "—"

        return False, (
            "у прогонов РАЗНЫЙ набор боковых индексов, и у отсутствующих было "
            "ЧТО читать, поэтому лифтер мог поднять разное: "
            f"только у первого {_cost(effective_a - effective_b, pb)}, "
            f"только у второго {_cost(effective_b - effective_a, pa)}. "
            "Индекс решает ВОЗМОЖНОСТЬ подъёма: без `family_placement` каждый "
            "экземпляр семейства — атом, без `dimension` размеры не "
            "поднимутся никогда. Прогон с оборванными побочными стадиями "
            "выражает меньше НЕ потому, что компилятор хуже")
    return True, ""


def build(directory: pathlib.Path, ops: int | None = None,
          generator_children: int | None = None,
          ops_by_category: dict[str, int] | None = None) -> dict[str, Any]:
    header = _header(directory)
    census = _census(header, directory)
    extracted = _extracted_by_collector(directory)
    # THE SECOND READER. Before 22.08, "read" was asked only of L0, and a
    # category read entirely by a side stage stood in the report as zero.
    side_read, side_units = _side_index_read_counts(directory, census,
                                                    extracted)

    if ops is None and ops_by_category is None:
        from kir.instruments.relift_offline import relift
        report = relift(directory)
        ops = int(report.get("op_total", 0))
        elements = int(report.get("elements", 0))
        ops_by_category = dict(report.get("ops_by_category") or {})
        if generator_children is None:
            generator_children = int(report.get("generator_children", 0))
    else:
        if ops_by_category is not None:
            ops = sum(ops_by_category.values()) if ops is None else ops
        elements = sum(extracted.values())
        generator_children = generator_children or 0

    # The numerator is broken down by the SAME class as the denominator,
    # and by the same closed table — by the CATEGORY of the source
    # element, not by the op's name. The list of ops moves every week, the
    # element's category is a fact about the model. While there was no
    # breakdown, `create_text`/`create_tag` fell into the "building"
    # numerator, whose denominator excludes annotation: a measurement on
    # 10.08 on `snowdon_plumb_v4` gave 100.07%, and on the RD tower the mix
    # cost +9.38 p.p. (v7 85.23% without the annotation stage versus v8
    # 94.61% with it, on the same 115,880 read elements).
    ops_by_class: dict[str, int] = {cls.value: 0 for cls in ContentClass}
    if ops_by_category:
        for key, count in ops_by_category.items():
            ops_by_class[classify(key).value] += int(count)
        ops_class_source = "по категории элемента-источника"
    else:
        # Silence is forbidden here: "no breakdown" and "there are no
        # annotation ops" are different facts, and the second must not be
        # substituted for the first.
        ops_by_class[ContentClass.MODEL.value] = ops or 0
        ops_class_source = "разбивки нет: числитель отнесён к зданию"
    ops_model = ops_by_class[ContentClass.MODEL.value]

    per_class: dict[str, dict[str, Any]] = {
        cls.value: {"census": 0, "read": 0, "categories": 0, "rows": []}
        for cls in ContentClass
    }
    unknown_rows: list[dict[str, Any]] = []

    for row in census:
        key = row["key"]
        count = int(row["count"])
        cls = classify(key)
        # TWO READERS, TWO COLUMNS, ONE SUM. The terms stay separate:
        # "read by the L0 collector" and "read by a side stage" are fixed
        # by different work, and a merged number would hide that. There is
        # no overlap between them by construction —
        # `_side_index_read_counts` refuses to attribute a category L0
        # already reads.
        read_l0 = extracted.get(key, 0)
        read_side = side_read.get(key, 0)
        read = read_l0 + read_side
        bucket = per_class[cls.value]
        bucket["census"] += count
        bucket["read"] += read
        bucket["categories"] += 1
        bucket["rows"].append({
            "category": key,
            "category_ru": row.get("name", ""),
            "census": count,
            "read": read,
            "read_l0": read_l0,
            "read_side": read_side,
        })
        if cls is ContentClass.UNKNOWN:
            unknown_rows.append(bucket["rows"][-1])

    for bucket in per_class.values():
        bucket["rows"].sort(key=lambda r: -r["census"])

    census_total = sum(int(r["count"]) for r in census)
    model = per_class[ContentClass.MODEL.value]["census"]
    model_read = per_class[ContentClass.MODEL.value]["read"]
    documentation = per_class[ContentClass.DOCUMENTATION.value]["census"]
    unknown = per_class[ContentClass.UNKNOWN.value]["census"]
    content = model + documentation

    def pct(numerator: int, denominator: int) -> float | None:
        if denominator <= 0:
            return None
        return round(100.0 * numerator / denominator, 2)

    # Generated elements (curtain wall panels, mullions, nested shared
    # families) sit INSIDE the "building" class: they are model elements
    # that by construction have no operation of their own — another
    # operation creates them. As long as they are in the denominator,
    # "building coverage" measures not the compiler but the share of
    # generated content in the project.
    #
    # The assumption is named and checkable: all generated elements must
    # be part of the model. If this breaks (say, generated annotations),
    # the run WILL SAY SO rather than silently fudge the subtraction.
    assumption_broken = generator_children > model_read
    authored_model = max(model - generator_children, 0)
    authored_model_read = max(model_read - generator_children, 0)
    authored_content = authored_model + documentation
    # A second assumption, named alongside the first on its own model: the
    # numerator cannot exceed the denominator. As long as it holds, "how
    # much is not expressed" is computable; if it breaks, the instrument
    # REFUSES to compute rather than fudging it.
    numerator_exceeds_read = ops_model > authored_model_read

    # Alias collectors read elements already counted by the census under
    # their real categories. Their trace shows up only in "read", and if
    # it is non-zero, the sum of what was read by class will be less than
    # the total element count. This is not an error, but it is not
    # silence either: we print it.
    alias_read = {k: v for k, v in extracted.items() if k in COLLECTOR_ALIASES}

    return {
        "directory": str(directory),
        "doc_name": header.get("document", {}).get("doc_name", ""),
        "ops": ops,
        "ops_by_class": ops_by_class,
        "ops_class_source": ops_class_source,
        "elements_read": elements,
        "generator_children": generator_children,
        "census_total": census_total,
        "categories_total": len(census),
        # ═══ WHAT THIS PERCENTAGE DEPENDS ON, RIGHT NEXT TO IT ═══
        #
        # MEASURED 2026-08-12, TWO REVISIONS OF THE SAME FACADE, THE
        # COMPILER DID NOT CHANGE BY A SINGLE LINE BETWEEN THEM:
        # `sob62_fas_r23_v12` gives 63.80%, `sob62_fas_r23_v19` — 91.23%.
        # A difference of 27 points, and it is made NOT by expressiveness
        # or even by the volume of reading in the naive sense: read
        # 5,095 versus 5,218, i.e. +2.4%.
        #
        # THE MECHANISM IS SHARPER. One extra category read — 122 curtain
        # wall grids — let the lifter RECOGNIZE 1,264 panels and mullions
        # as generated children of the curtain wall. `generator_child` is
        # excluded from the honest figure, so the denominator dropped by
        # exactly them (4,205 -> 2,942), while the numerator barely moved
        # (2,683 -> 2,806). That is, **123 read elements reclassified
        # 1,264 others**, and the percentage grew from READING, not from
        # the compiler.
        #
        # NO FLAG CAUGHT THIS: both runs had `census_balanced: true`,
        # `errors: []`, `done: 1`, `is_partial_read: false`, and even
        # `generator_children_assumption_broken: false`. The only thing
        # that told them apart was `categories_scanned` (14 versus 15),
        # which was never compared against anything.
        #
        # SO THE PERCENTAGE TRAVELS WITH ITS OWN CONDITIONS. The signal is
        # NOT set up from scratch — it is COMPUTED from existing
        # authorities: the extraction table (what we can read at all)
        # against the §18.1 census (what is in the document) against what
        # was actually read. A category that IS IN THE TABLE and is
        # non-zero in the census but was read as zero is not "outside the
        # table" (a known and named metric gap) but a different,
        # dangerous cause, and it must stand right next to the number.
        "conditions": _conditions(directory, census, extracted),
        "denominators": {
            "model": model,
            "model_authored": authored_model,
            "documentation": documentation,
            "content": content,
            "content_authored": authored_content,
            "document": census_total,
            "unknown": unknown,
        },
        # BUILDING is measured by the building: the numerator is model
        # ops only.
        "model_pct": pct(ops_model, model),
        "model_pct_authored": pct(ops_model, authored_model),
        # CONTENT = building + annotation, so here the numerator is full.
        "content_pct": pct(ops, content),
        "content_pct_authored": pct(ops, authored_content),
        # A lower bound: if ALL the unclassified turns out to be content.
        # The true number lies between this and content_pct_authored — an
        # interval, not one convenient number.
        "content_pct_lower_bound": pct(ops, authored_content + unknown),
        "document_pct": pct(ops, census_total),
        # The gap is broken down into two causes that are fixed by
        # DIFFERENT work.
        "gap": {
            # A line in the category table: building elements we do not see.
            "model_unread": model - model_read,
            # The lifter and the op: read, authorial, but not lifted into ops.
            "model_read_authored": authored_model_read,
            # AN INVERSION REFUSES, IT IS NOT CLAMPED AWAY (2026-08-13).
            #
            # `max(authored_model_read - ops_model, 0)` used to stand
            # here. The numerator (op nodes from `relift_offline`) and the
            # denominator (the §18.1 census) come from DIFFERENT
            # producers, and there is no check between them: nothing stops
            # the numerator from exceeding the denominator. The clamp
            # turned this into a neat zero — in the column "how much we
            # did NOT express" — that is, it printed the most flattering
            # of possible answers. **Clamping it away hid the error IN
            # FAVOR OF OUR OWN NUMBER.**
            #
            # And this is not a hypothesis: on `sob62_fas_r23_v19`, a real
            # `build` with a doubled numerator (simulating a lifter that
            # gives two ops per element) printed **182.46% and "0 not
            # expressed"** — silently. And `relift_offline.py:235`
            # remembers the 2026-08-10 measurement, when the column was
            # already printing 100.07% on `snowdon_plumb_v4`; back then
            # the CLASSIFICATION was fixed, no check was added.
            #
            # `None`, not 0: "we don't know how much is not expressed"
            # and "0 is not expressed" are different facts, and today the
            # second was printed in place of the first.
            "model_read_unlifted": (
                None if numerator_exceeds_read
                else authored_model_read - ops_model),
            "expressed_of_read_pct": (
                None if numerator_exceeds_read
                else pct(ops_model, authored_model_read)),
            # THE PROPERTY EVERYTHING RESTS ON — AND IT IS NOT GUARANTEED.
            # The column is correct as long as the lifter gives ONE op per
            # element. Measured on 13.08 across the whole corpus: 52 runs
            # with a tree, 247,347 op nodes, the same number of distinct
            # `source_element_id`s, delta 0, mute runs 0. But nothing in
            # the code requires this, and the component library has
            # already broken this property once — coverage computed from
            # the EXPANDED output was inflated by exactly the excess of
            # 2,351.
            "expressed_numerator_exceeds_read": numerator_exceeds_read,
            # A whole class we have not touched: annotation.
            "documentation_unread": documentation
            - per_class[ContentClass.DOCUMENTATION.value]["read"],
        },
        "generator_children_assumption_broken": assumption_broken,
        "per_class": {
            name: {k: v for k, v in bucket.items() if k != "rows"}
            for name, bucket in per_class.items()
        },
        "per_class_rows": {name: bucket["rows"]
                           for name, bucket in per_class.items()},
        "unknown_rows": sorted(unknown_rows, key=lambda r: -r["census"]),
        "alias_collectors_read": alias_read,
        # THE SECOND READER IS PRINTED IN ITS OWN LINES, not dissolved
        # into the overall figure: a side stage's unit of reading can be
        # wider than a category (575 group instances across three
        # categories), and the report must show exactly what closed the
        # zero.
        "side_index_reads": side_units,
        "side_index_read_by_category": dict(sorted(side_read.items())),
        "side_index_read_total": sum(side_read.values()),
    }


def _conditions_line(cond: dict[str, Any]) -> str:
    if not cond.get("table_available"):
        return ("УСЛОВИЯ НЕИЗВЕСТНЫ: таблицы извлечения нет — с чем этот "
                "процент сопоставим, сказать нечем")
    unread = cond.get("in_table_unread") or {}
    scanned = cond.get("categories_scanned")
    head = (f"условия: категорий отсканировано {scanned}; "
            f"умели прочесть, но не прочли — {len(unread)} категорий "
            f"({cond.get('in_table_unread_elements', 0)} элементов)")
    if not unread:
        return head + ". Сопоставим только с прогоном такого же множества."
    names = ", ".join(f"{k}:{v}" for k, v in list(unread.items())[:6])
    tail = "" if len(unread) <= 6 else f" и ещё {len(unread) - 6}"
    return (head + f"\n  НЕ ПРОЧИТАНО ИЗ ТОГО, ЧТО УМЕЕМ: {names}{tail}"
            "\n  Сравнивать этот процент можно ТОЛЬКО с прогоном, у которого "
            "это множество ТО ЖЕ.")


def render(report: dict[str, Any]) -> str:
    den = report["denominators"]
    gap = report["gap"]
    model_bucket = report["per_class"][ContentClass.MODEL.value]
    doc_bucket = report["per_class"][ContentClass.DOCUMENTATION.value]

    def col(value: float | None) -> str:
        """An empty denominator is printed as a dash, not a zero: zero is
        a measurement of "we express nothing", a dash is "nothing to
        measure"."""
        return f"{'—':>9} " if value is None else f"{value:>9}%"
    lines = [
        f"{report['doc_name']}  ({report['directory']})",
        f"опов поднято: {report['ops']}   элементов прочитано: "
        f"{report['elements_read']}   категорий в переписи: "
        f"{report['categories_total']}",
        # The numerator must name its composition next to the
        # percentages: while it was one number, annotation ops were
        # silently counted as building.
        f"опы по классам: {report['ops_by_class']}   ({report['ops_class_source']})",
        # THE CONDITIONS STAND ABOVE THE NUMBER, NOT BELOW IT: a reader
        # who has reached the percentage must already know what it is
        # comparable to.
        _conditions_line(report.get("conditions") or {}),
        "",
        f"{'знаменатель':<30}{'элементов':>10}{'читаем':>9}{'покрытие':>10}",
        f"{'ЗДАНИЕ':<30}{den['model']:>10}{model_bucket['read']:>9}"
        f"{col(report['model_pct'])}",
        f"{'ЗДАНИЕ без порождаемых':<30}{den['model_authored']:>10}"
        f"{gap['model_read_authored']:>9}{col(report['model_pct_authored'])}",
        f"{'+ оформление = СОДЕРЖАНИЕ':<30}{den['content_authored']:>10}"
        f"{gap['model_read_authored'] + doc_bucket['read']:>9}"
        f"{col(report['content_pct_authored'])}",
        f"{'ВЕСЬ ДОКУМЕНТ':<30}{den['document']:>10}"
        f"{report['elements_read']:>9}{col(report['document_pct'])}",
        "",
        "разрыв разложен (чинится РАЗНЫМ трудом):",
        f"  выражаем из прочитанного здания: {gap['expressed_of_read_pct']}% "
        f"({report['ops_by_class']['model']} модельных опов из "
        f"{gap['model_read_authored']} авторских)",
        f"  не ЧИТАЕМ элементов здания:      {gap['model_unread']}"
        f"   ← строка в таблице категорий",
        (f"  читаем, но не поднимаем:         {gap['model_read_unlifted']}"
         f"   ← лифтер и оп"
         if gap["model_read_unlifted"] is not None else
         "  читаем, но не поднимаем:         НЕИСЧИСЛИМО"
         "   ← числитель больше знаменателя, см. ВНИМАНИЕ ниже"),
        f"  оформление не читается вовсе:    {gap['documentation_unread']}"
        f"   ← целый класс",
        "",
        "по классам:",
    ]
    for name, bucket in report["per_class"].items():
        if not bucket["census"]:
            continue
        share = 100.0 * bucket["census"] / report["census_total"]
        lines.append(f"  {name:<14} {bucket['census']:>7} эл. "
                     f"({share:5.2f}% документа), категорий "
                     f"{bucket['categories']:>3}, читаем {bucket['read']}")
    if report["unknown_rows"]:
        lines.append("")
        lines.append("НЕ КЛАССИФИЦИРОВАНО (правь таблицу или объясни):")
        # THE CUTOFF NAMES HOW MUCH IT HID (2026-08-13). The list used to
        # be cut at twenty silently: on `snowdon_plumb_v5`, 44 unfamiliar
        # ones, the reader saw 20 and knew nothing of the other 24; on
        # `snowdon_elec_v1` — 22 and 2. This is our own rule "no silent
        # cutoffs", violated in the very instrument the shares are
        # computed from. The display is still limited — a long tail is
        # unreadable — but the limit is now DECLARED by a number.
        shown = report["unknown_rows"][:_UNKNOWN_ROWS_SHOWN]
        for row in shown:
            lines.append(f"  {row['census']:>7}  {row['category']}"
                         f"  {row['category_ru']}")
        hidden = report["unknown_rows"][len(shown):]
        if hidden:
            lines.append(
                f"  … и ещё {len(hidden)} категорий на "
                f"{sum(r['census'] for r in hidden)} элементов — НЕ ПОКАЗАНЫ "
                f"(показ ограничен {_UNKNOWN_ROWS_SHOWN} строками; полный "
                f"список в `--json`)")
        lower = report["content_pct_lower_bound"]
        lines.append(f"  ⇒ содержательное покрытие лежит между {lower}% "
                     f"и {report['content_pct_authored']}%")
    if report["alias_collectors_read"]:
        lines.append("")
        lines.append(f"коллекторы-псевдонимы (уже в переписи под своими "
                     f"категориями): {report['alias_collectors_read']}")
    if report.get("side_index_reads"):
        lines.append("")
        lines.append(
            f"ПРОЧИТАНО БОКОВЫМИ СТАДИЯМИ (не через collector в L0): "
            f"{report['side_index_read_total']} элементов")
        for unit in report["side_index_reads"]:
            names = ", ".join(unit["categories"])
            if unit["read"] is None:
                lines.append(f"  {unit['stage']:<8} — {unit['why']} "
                             f"({names}, перепись {unit['census']})")
                continue
            mark = "✓" if unit["attributed"] else "✗"
            lines.append(f"  {unit['stage']:<8} {unit['read']:>5} из "
                         f"{unit['census']:>5} по переписи  {mark} {names}")
            if not unit["attributed"]:
                lines.append(f"           не разложено по категориям: "
                             f"{unit['why']}")
    if report["gap"]["expressed_numerator_exceeds_read"]:
        lines.append("")
        lines.append(
            "ВНИМАНИЕ: ВЫРАЖЕНО БОЛЬШЕ, ЧЕМ ПРОЧИТАНО "
            f"({report['ops_by_class']['model']} опов из "
            f"{report['gap']['model_read_authored']} авторских) — числитель и "
            "знаменатель приходят от РАЗНЫХ производителей, и это значит, что "
            "лифтер дал больше одного опа на элемент либо числитель посчитан "
            "по развёрнутому выводу. Проценты выше НЕ ПЕЧАТАЮТСЯ: доля больше "
            "ста — не результат, а отказ прибора. Следующий ход: сверить число "
            "узлов-опов с числом различных source_element_id "
            "(13.08: 52 прогона, 247 347 опов, дельта 0).")
    if report["generator_children_assumption_broken"]:
        lines.append("")
        lines.append(
            "ВНИМАНИЕ: порождаемых больше, чем прочитано модельных элементов "
            f"({report['generator_children']} > {model_bucket['read']}) — "
            "допущение «порождаемое всегда модельное» нарушено, вычитание "
            "ниже не обосновано")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("directory", type=pathlib.Path)
    parser.add_argument("--ops", type=int, default=None,
                        help="число опов, если пересчёт лифтом не нужен")
    parser.add_argument("--json", type=pathlib.Path, default=None)
    args = parser.parse_args(argv)

    # 🔴 THE DECOMPILE IS NAMED OUT LOUD. The coverage share as a whole is
    # a function of WHICH decompile is fed in: 52.58% on the tower and
    # 78.43% on the same tower "without generated elements" — two
    # different numbers under one name. Before 2026-08-18 the instrument
    # printed percentages and did not print whose they were.
    from kir.instruments.measure_header import measure_header
    report = build(args.directory, ops=args.ops)
    print(measure_header(
        source=args.directory,
        blind=(
            "процент ВЫРАЗИМОСТИ не говорит о ПЕРЕСБОРКЕ: на Snowdon 98.4 % "
            "труб подняты и 0 из 26 чанков собрались",
            "элементы связанных файлов в разбор не входят и в знаменатель "
            "не попадают",
            "оформление (размеры, марки, линии) читается боковыми стадиями, "
            "а не этим числом",
        ),
        note=("   опы: %s" % ("подан --ops %d" % args.ops if args.ops
                              else "пересчитаны лифтом"))))
    print(render(report))
    if args.json:
        args.json.write_text(json.dumps(report, ensure_ascii=False, indent=1),
                             encoding="utf-8")
        print(f"\n→ {args.json}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
