using System.Text.Json;
using System.Text.Json.Nodes;

namespace CompileService;

/// <summary>
/// Dependency-free deterministic vectors generated by the Python
/// CompileReceipt contract. This class is intentionally host-neutral: a later
/// service wave may invoke it, but it never binds a socket, initializes Roslyn
/// references, or makes an execution/ACK/acceptance claim.
/// </summary>
internal static class ContractSelfTest
{
    private const string ExpectedManifestDigest =
        "4fe7a0b9b39a96eaf2f81a111533866a649306cd5f9c1678f1d480c8e6ef838f";
    private const string ExpectedWrapperDigest =
        "46802d07b4527ebccdc14632e40dbfb3daea3012064dbc7d2f321c29a3b03b77";
    private const string ExpectedArtifactDigest =
        "f0b8e6c5d8285e9a34d8b1ac19c84fc2f34f898033d803e050ee26a32cabe69a";
    private const string ExpectedReceiptDigest =
        "a6fdc24772d35b2341e7eddc8567d71e5b2190a885d587ab539f476de0f80b62";

    private const string PythonRequestVector = """
        {"schema":"kir-compile-request/1","source":"var message = \"Привет\";\nreturn message;","artifact":{"schema":"kir-emitted-artifact/1","lower_digest":"1111111111111111111111111111111111111111111111111111111111111111","target_profile_digest":"e52891173b5efd458b00db73a59dea0fdfcac01a7289c76f080d4286a436ba3c","emitter_contract":"kukai-authoring-csharp/1","source_encoding":"utf-8","source_sha256":"32058cb185c9a8cf63d5cba8fcf27b58075eb75b0313344d77265e1f61b4bb9c","source_bytes":45,"artifact_digest":"f0b8e6c5d8285e9a34d8b1ac19c84fc2f34f898033d803e050ee26a32cabe69a"},"compile_unit":{"wrapper_contract":"kukai-revit-execute-wrapper/1","source_encoding":"utf-8","source_sha256":"46802d07b4527ebccdc14632e40dbfb3daea3012064dbc7d2f321c29a3b03b77","source_bytes":571},"target":{"profile_id":"revit-2026-net8-cs10-r1","revit_year":"2026","profile_digest":"e52891173b5efd458b00db73a59dea0fdfcac01a7289c76f080d4286a436ba3c","manifest_digest":"4fe7a0b9b39a96eaf2f81a111533866a649306cd5f9c1678f1d480c8e6ef838f"}}
        """;

    internal static void Run()
    {
        var manifest = TargetProfileManifest.LoadPackaged();
        Equal(ExpectedManifestDigest, manifest.ManifestDigest, "manifest digest");
        Equal("net8.0", manifest.ProfileForYear("2026").TargetFramework, "framework");

        var validated = Validate(PythonRequestVector, manifest);
        Equal(45L, validated.Artifact.SourceBytes, "UTF-8 body byte length");
        Equal(571L, validated.CompileUnit.SourceBytes, "wrapper byte length");
        Equal(
            ExpectedWrapperDigest,
            StrictJson.Sha256Hex(validated.WrappedSource),
            "Python wrapper digest");
        Equal(
            ExpectedArtifactDigest,
            validated.Artifact.ArtifactDigest,
            "Python artifact digest");

        var receipt = CompileReceiptProtocol.MintReceipt(validated);
        Equal(ExpectedReceiptDigest, receipt.ReceiptDigest, "Python receipt digest");
        VerifyReceiptWireShape(receipt);

        var tamperCases = new Action<JsonObject>[]
        {
            root => root["extra"] = true,
            root => root["source"] = "return 7;",
            root => root["artifact"]!.AsObject()["source_bytes"] = true,
            root => root["artifact"]!.AsObject()["artifact_digest"] = new string('0', 64),
            root => root["compile_unit"]!.AsObject()["source_sha256"] = new string('0', 64),
            root => root["compile_unit"]!.AsObject()["wrapper_contract"] = "other-wrapper/1",
            root => root["target"]!.AsObject()["manifest_digest"] = new string('0', 64),
            root => root["target"]!.AsObject()["target_framework"] = "net8.0",
        };
        foreach (var tamper in tamperCases)
        {
            var root = JsonNode.Parse(PythonRequestVector)!.AsObject();
            tamper(root);
            Reject(root.ToJsonString(), manifest);
        }

        var duplicateSchema = PythonRequestVector.Replace(
            "{\"schema\":",
            "{\"schema\":\"kir-compile-request/1\",\"schema\":",
            StringComparison.Ordinal);
        Reject(duplicateSchema, manifest);

        Console.WriteLine("compile-service contract self-test: PASS");
    }

    private static void VerifyReceiptWireShape(CompileReceiptEvidence receipt)
    {
        var json = JsonSerializer.Serialize(
            receipt,
            StrictJson.SerializerOptions);
        using var document = JsonDocument.Parse(json);
        var root = StrictJson.Object(
            document.RootElement,
            "receipt",
            "schema",
            "artifact",
            "compile_unit",
            "target",
            "compiler_contract",
            "receipt_digest");
        Equal(
            CompileReceiptProtocol.ReceiptSchema,
            StrictJson.String(root["schema"], "receipt.schema"),
            "receipt schema");
        Equal(
            ExpectedReceiptDigest,
            StrictJson.String(
                root["receipt_digest"],
                "receipt.receipt_digest"),
            "serialized receipt digest");
    }

    private static ValidatedCompileRequest Validate(
        string json,
        TargetProfileManifest manifest)
    {
        using var document = JsonDocument.Parse(json);
        return CompileReceiptProtocol.Validate(document.RootElement, manifest);
    }

    private static void Reject(string json, TargetProfileManifest manifest)
    {
        try
        {
            Validate(json, manifest);
        }
        catch (Exception exception) when (
            exception is JsonContractException or CompileProtocolException)
        {
            return;
        }
        throw new InvalidOperationException("tampered request was accepted");
    }

    private static void Equal<T>(T expected, T actual, string label)
        where T : notnull
    {
        if (!EqualityComparer<T>.Default.Equals(expected, actual))
        {
            throw new InvalidOperationException(
                $"{label} mismatch: expected={expected}, actual={actual}");
        }
    }
}
