"""THE MCP SURFACE: WHAT KIR PRESENTS TO THE HOST — AND WHY EXACTLY THIS
WAY.

This module KNOWS NOTHING about the protocol SDK and does not import it in
a single line. It hands back ordinary dictionaries `{name, description,
input_schema}`, and `server.py` turns them into wire objects. The split is
paid for by two arguments:

  1. THE SURFACE IS A FACT OF THIS TREE, not a fact of someone else's
     package. The determinism gate
     (`tests/test_surface_is_deterministic.py`) must judge it for whoever
     installs KIR — that is, WITHOUT `mcp` installed.
  2. Swapping the SDK does not change a single byte of what the model
     sees.

🔴 THE SCHEMA IS NOT DERIVED FROM PYTHON SIGNATURES, AND THIS IS NOT TASTE.
The SDK's ergonomic layer (`MCPServer.tool`) builds `inputSchema` from
type annotations. This is forbidden here by the tree's law, recorded in
`schema_gen`'s header: "JSON Schema is generated by the registry, never
hand-written." A python function's annotation would be a SECOND carrier
of truth about the language and would drift from `spec.OPS` on the very
first new op — silently, because there is nothing to stop them from
drifting apart. So the server is built at the SDK's lower level, where
`input_schema` is delivered VERBATIM from the generator.

🔴 THE PROSE LIVES IN THE SERVER'S `instructions`, NOT IN EVERY TOOL'S
DESCRIPTION. Measured 02.09.2026: `tool_doc.build_tool_description()` —
29,944 bytes. There are five tools; a copy in each would cost 149,720
bytes for one `tools/list`. This prose's subject is THE LANGUAGE, not one
door, and so its place is at the server level.

🔴 TOOL ORDER IS A TUPLE, NOT A DICTIONARY LEFT TO CHANCE.
The 2026-07-28 spec (minor revision 3) asks for a deterministic order for
the sake of the client's cache and hitting the model's prompt cache. A
nondeterministic order breaks nothing visible — it silently misses the
cache for EVERY client, and that is exactly the kind of defect this tree
has already paid for with the obfuscator: five obfuscations of one text
gave five different sources, Revit could not cache the build, and the K3
transfer degraded 3 s -> 250 s -> refusal.
"""
from __future__ import annotations

import copy
from typing import Any

from kir.mcp import app as _app

#: The name of the LANGUAGE prefix. Tools are named `kir_*`, because the
#: host shows them mixed in with everyone else's: a name without an owner
#: is an invitation to collide.
PREFIX = "kir"


def _versions_enum() -> list[str]:
    """The list of Revit versions — FROM THE AUTHORITY, not as a literal.

    The same argument recorded in
    `compile_client._ALL_SHIPPED_REVIT_VERSIONS`: a literal would drift
    from the registry exactly at the version we do not have — that is, on
    someone else's machine, and silently.
    """
    from kir.registry_base import REVIT_VERSIONS
    return list(REVIT_VERSIONS)


def _program_outline(flat: dict) -> dict:
    """THE PROGRAM ENVELOPE WITHOUT THE PER-OP PARAMETER DETAIL — DERIVED
    FROM THE GENERATED SCHEMA, NEVER WRITTEN BY HAND.

    🔴 WHAT THIS COSTS AND WHY IT IS PAID. Measured 13.09.2026 on this
    tree, by the same probe as the audit of section H (§1.1):

        tools/list          75 602 B, of which `kir_compile` alone  65 969 B
        instructions()      48 070 B
        FIRST TOUCH        123 672 B  ~= 41 000 tokens, before the agent
                                         has said one word

    For a 200k-token model that is a fifth of the context spent on a
    listing. The `ops` branch is the whole of it: of the 437 934 B of the
    flat schema, `ops` is 431 095 B and the entire rest of the envelope is
    6 564 B. Those 431 KB are 86 branches spelling out every slot of every
    op — and the door that answers exactly that question, for ONE op, in
    hundreds of bytes, already exists and was built for this: `kir_spec`
    (`_SPEC_DESC`: "дверь прогрессивного раскрытия"). Two decisions about
    one subject stood in one surface; this removes the second.

    🔴 WHAT IS NOT REMOVED, AND THIS IS THE POINT. The envelope keeps every
    bound that REFUSES: `ir_version` const, `lineage` pattern and length
    (a SIGNED field of plan /5 — see `test_public_lineage_schema`),
    `allow_destructive`, `defaults`, `required`, and
    `additionalProperties: false` at both levels. The op NAME stays
    enumerated, so `{"op": "invented"}` is still rejected on the wire. What
    goes is documentation, not checking: the refusal belongs to the
    compiler (`schema_gen`'s header, SPEC 12.9), and it is unchanged.

    🔴 THE RISK IS NAMED, NOT PAPERED OVER. This tree already holds a
    measurement in the OTHER direction: 18.08.2026, `deepseek-v4-flash`,
    the COLLAPSED schema wrecked the result — 4 accepted blocks of 6
    against 5 of 5, and in block 0 not one program in 13 turns
    (`_program_schema`'s docstring). That measurement is about `$ref`
    indirection inside one blob, not about an on-demand door, and the two
    mechanisms are not the same thing — but nobody has measured THIS one
    on a model. Until someone does, the re-measurement obligation recorded
    in `_program_schema` carries over to this function verbatim.

    The names come from the generated branches, not from a literal: a
    literal list of ops would be a second carrier of truth about the
    language and would drift on the first new op, silently — the same
    argument as `_versions_enum`.
    """
    out = copy.deepcopy(flat)
    ops = out["properties"]["ops"]
    branches = ops["items"]["oneOf"]
    names = [b["properties"]["op"]["const"] for b in branches]
    # `id` is the one slot every branch shares and the one the author needs
    # in order to reference an output later; it is copied from a branch, not
    # re-declared here.
    id_schema = copy.deepcopy(branches[0]["properties"]["id"])
    ops["items"] = {
        "type": "object",
        "description": (
            "Операция KIR. Параметры здесь НЕ перечислены намеренно: "
            "контракт одного опа — слоты, виды, границы, постусловие — "
            "спрашивается инструментом `kir_spec` и стоит сотни байт "
            "вместо десятков тысяч."),
        "required": ["op"],
        "properties": {
            "op": {
                "enum": names,
                "description": (
                    "Имя операции из реестра. Параметры опа передаются "
                    "рядом; их форму даёт `kir_spec(\"<оп>\")`."),
            },
            "id": id_schema,
        },
    }
    return out


def _program_schema() -> dict:
    """The program schema for the `program` FIELD of the `kir_compile`
    tool.

    🔴 HERE, HOISTING INTO `$defs` IS ON BY DEFAULT, AND THIS IS A DECISION
    ABOUT MCP, NOT ABOUT THE PRODUCT. `schema_transport.transport_verdict()`
    keeps the schema flat until `$ref` support has been MEASURED on a
    specific provider — and that rule is correct where the provider is
    ours. With MCP the client chooses the provider, there is in principle
    nothing to measure it with, and the 2026-07-28 spec (SEP-2106) ALLOWS
    `$ref` and sets the rules for resolving it. That is, the TRANSPORT
    question for this door is settled not by measurement but by the
    protocol itself.

    A COST MEASUREMENT, 02.09.2026, by this tree:

        flat        426,992 B  (~107k tokens for one `tools/list`)
        collapsed    61,114 B  (6.85x, 76 forms hoisted out)

    Flat here is not "more expensive," it is UNUSABLE: one schema eats up
    a share of context after which there is nothing left to build with.
    The choice between "works" and "does not work" is not decided by the
    provider's switch.

    🔴 WHAT REMAINS OPEN AND IS NOT PAPERED OVER: the question of the
    MODEL. A measurement on 18.08.2026 with `deepseek-v4-flash` shows that
    the collapsed schema WRECKS the result (4 accepted blocks out of 6
    against 5 out of 5; in block 0, not one program in 13 turns, nothing
    but "refusal · reconnaissance"). That measurement was taken on our own
    provider, and stage 2 of the plan carries a RE-MEASUREMENT on whatever
    model ends up driving MCP. The switch is named:
    `KIR_MCP_SCHEMA_DEDUP=0` returns the flat schema in full.
    """
    from kir import env
    from kir.schema_gen import program_schema

    outline = _program_outline(program_schema())
    if (env.get("KIR_MCP_SCHEMA_DEDUP") or "").strip() == "0":
        return outline
    from kir.schema_dedup import hoist
    return hoist(outline)


def _program_ref() -> dict:
    """A reference to the program, for doors that do NOT COMPOSE it, but
    read it.

    🔴 WHY, BY MEASUREMENT AT THE VERY FIRST BUILD OF THE SURFACE
    (02.09.2026). The full schema stood at all three doors that take
    `program`, and the surface came out at 1,284,912 bytes — the same
    schema, carried THREE TIMES OVER. The defect would have slipped
    through silently: each door looked correct on its own.

    The program schema is a GUIDE FOR THE AUTHOR, not a checker: its
    bounds stand as documentation, and the refusal belongs to the compiler
    (`schema_gen`'s header, SPEC 12.9). Exactly one door composes a
    program, `kir_compile`; rehearsal and preview receive something
    ALREADY WRITTEN — from `kir_author` or from a past turn. So the second
    and third copies of the guide teach no one, and every tool list pays
    for them.
    """
    return {
        "type": "object",
        "description": (
            "Программа KIR (операции JSON). Форма — та же, что у поля "
            "`program` инструмента `kir_compile`: там оболочка программы и "
            "перечень имён опов. Контракт отдельного опа — у `kir_spec`, и "
            "ни в одном списке инструментов его больше нет."),
    }


def schema_note() -> str:
    """What shape the program schema went out in and WHY — as a string,
    for the log and the gate.

    Nothing silent: the path on which hoisting was not applied must say
    so. Otherwise "we saved" and "we did not save" look identical, and a
    regression lives unnoticed right up to the next count (the
    `schema_transport` rule).
    """
    import json

    from kir import env
    from kir.schema_gen import program_schema

    full = program_schema()
    full_bytes = len(json.dumps(full, ensure_ascii=False))
    outline_bytes = len(json.dumps(_program_outline(full), ensure_ascii=False))
    got = len(json.dumps(_program_schema(), ensure_ascii=False))
    ops_note = (f"параметры опов сняты со списка и живут у `kir_spec` "
                f"({full_bytes}->{outline_bytes} Б)")
    if (env.get("KIR_MCP_SCHEMA_DEDUP") or "").strip() == "0":
        return (f"схема ПЛОСКАЯ, {got} Б: {ops_note}; свёртка выключена "
                f"рубильником KIR_MCP_SCHEMA_DEDUP=0")
    ratio = (outline_bytes / got) if got else 0.0
    return (f"схема СВЁРНУТА в $defs ({ratio:.2f}x, {outline_bytes}->{got} Б): "
            f"{ops_note}; $ref разрешён спекой 2026-07-28 (SEP-2106), замер "
            f"транспорта для MCP не нужен; вопрос МОДЕЛИ остаётся открытым")


def instructions() -> str:
    """Prose about THE LANGUAGE: the list of ops from the registry, idioms,
    and pitfalls with provenance.

    Word for word the same text that rides as the description of
    `revit_ir` in the product. A second copy is not introduced: it would
    drift from the registry, and `test_tool_doc` guards only the
    original.
    """
    import json

    from kir.mcp import policy
    from kir.tool_doc import build_tool_description

    # 🔴 ALLOWANCES ARE SHOWN, NOT GUESSED. A model that does not know
    # what it is permitted to do spends a turn probing what is already
    # open — and that is exactly what the stage-2 rig saw: a hand with the
    # collapsed schema kept sliding into "refusal · reconnaissance ·
    # refusal." Cheaper to just say it.
    return build_tool_description() + (
        "\n\nДОПУЩЕНИЯ ЭТОЙ ДВЕРИ (она ШИРЕ продуктовой, и вот чем):\n"
        + json.dumps(policy.latitudes(), ensure_ascii=False, indent=2))


# ─────────────────────────────────────────────────────────────────────────────
# Tools
# ─────────────────────────────────────────────────────────────────────────────

_AUTHOR_DESC = """\
Написать программу KIR ПИТОНОМ и получить операции IR. Ничего не строит и \
Ревита не требует.

Скрипт исполняется в песочнице ОТДЕЛЬНЫМ ПРОЦЕССОМ: сеть недостижима \
физически (своё пространство имён), корень пуст, запись на диск запрещена \
RLIMIT_FSIZE=0, импорты — белый список (math, itertools, functools и сам DSL). \
Наружу выходит РОВНО список операций IR.

🔴 ПОЛИТИКА СЕТИ — `required`, то есть fail-closed: на ядре без пространств \
имён пользователя (в частности на Windows) запуск НЕ СОСТОИТСЯ и вернёт \
названный отказ, а не тихо ослабленную изоляцию. Это условие, а не дефект: \
обещание «ноль сети» либо доказано замером на этом запуске, либо не дано.

Контракт любого опа спрашивается инструментом `kir_spec` — и тем же именем \
`spec("<оп>")` внутри самого скрипта."""

_COMPILE_DESC = """\
Скомпилировать программу KIR в C# для названных версий Ревита. \
ОФЛАЙН: ни Ревита, ни лицензии, ни службы — ничего не запускается и никуда \
не отправляется. Возвращает по версии: получилось ли, длину C# и диагностику.

«Скомпилировалось» без названной версии не значит ничего (SPEC 11.2), поэтому \
версии перечисляются, а ответ разложен по ним.

🔴 СХЕМА ПОЛЯ `program` НЕСЁТ ОБОЛОЧКУ И ИМЕНА ОПОВ, НЕ ИХ ПАРАМЕТРЫ. Форма \
одного опа спрашивается у `kir_spec` и стоит сотни байт; полный перечень \
слотов всех опов стоил 65 969 Б в каждом `tools/list` и уехал отсюда \
13.09.2026. Имя опа при этом по-прежнему проверяется на проводе: \
несуществующий оп — отказ схемы, а не молчание."""

_REHEARSE_DESC = """\
Репетиция: что в этой программе будет проверено свидетелем, а что НЕ БУДЕТ — \
до единого рейса в Ревит.

Заведена по замеру 18–19.08.2026: два крупных провала из трёх на живой башне \
были не ошибками геометрии, а обязательствами, которые НЕ ПОБЕЖАЛИ, и \
молчанием об этом (420 колонн встали на 2500 мм вместо 3600–4500; 540 балок \
из 540 — на z=0 при написанном «Этаж 5»)."""

_PREVIEW_DESC = """\
План этажа картинкой (SVG) из ПРОГРАММЫ — до всякой транзакции.

Не судит: рисует заявленное и отдельной переписью предъявляет то, чего на \
картинке НЕТ (толщины, ширины проёмов и границы помещений без документа \
неизвестны и правдоподобным числом не заменяются). Перепись лежит машинным \
JSON внутри SVG, у каждой фигуры есть `data-el`/`data-cat`."""

_OPEN_DESC = """\
Открыть здание: спросить у Ревита, ЧТО сейчас открыто, и получить РУЧКУ.

Ручка передаётся полем `building` в `kir_write`. Она несёт заголовок \
документа, версию Ревита и отпечаток на момент выдачи — то есть делает выбор \
документа предъявленным, а не угаданным. У неё есть срок: ручка, пережившая \
свой документ, выглядит рабочей и адресует то, чего уже нет.

🔴 ТРЕБУЕТ ТРАНСПОРТА ДО РЕВИТА (порт «mcp.revit»). Если хозяин его не \
поставил — отказ НАЗЫВАЕТ порт, а весь офлайн-путь остаётся открыт."""

_WRITE_DESC = """\
Записать программу KIR в открытый документ. ЕДИНСТВЕННАЯ дверь, которая \
что-то меняет.

ПО УМОЛЧАНИЮ ПИШЕТ СРАЗУ, ОДНИМ ХОДОМ (решение владельца 03.09.2026). \
Человека в петле нет: между тобой и живым зданием никто не стоит.

Хозяин может включить подтверждение — `KIR_MCP_CONFIRM=session` (спросить раз \
на здание) или `call` (на каждую запись). Тогда первый вызов НИЧЕГО НЕ ПИШЕТ, \
а возвращает вопрос человеку, и согласие привязано к ПОДПИСИ программы: \
подтвердили одно, пришло другое — отказ, а не запись похожего.

🔴 ПО УМОЛЧАНИЮ ВЫКЛЮЧЕНА. Пока хозяин не выставил `KIR_MCP_WRITE=on`, дверь \
отказывает и называет причину. Это умолчание, а не поломка.

🔴 ЗАПИСЬ СИНХРОННА и ограничена таймаутом: программа на минуты сюда пока не \
годится. Долгая запись — предмет расширения Tasks, и оно не построено, потому \
что против мока его нечем помЕрить.

🔴 ПОВТОР ПОСЛЕ ПОТЕРЯННОГО ОТВЕТА НЕ УДВАИВАЕТ ЗАПИСЬ. Каждая отправка \
получает имя операции и durable-отметку; пока исход предыдущей записи в ЭТОТ \
документ неизвестен, следующая не уходит, а спрашивает человека — и этот \
вопрос переживает перезапуск сервера и переименование документа. Хозяин, \
умеющий `lookup(operation_id)`, снимает вопрос сам, без человека. Отметка \
живёт в каталоге данных ПОЛЬЗОВАТЕЛЯ (`$XDG_DATA_HOME/kir/mcp`, иначе \
`~/.local/share/kir/mcp`; на Windows `%LOCALAPPDATA%\\kir\\mcp`) — не в \
дереве хозяина; свой каталог называется `KIR_MCP_PENDING_DIR`. Если писать в \
него нельзя, дверь отказывает ДО отправки и называет причину."""

_SPEC_DESC = """\
Контракт операции из реестра: форма вызова, слоты с видами и границами, формы \
селекторов, пул заземления, постусловие и допуски свидетеля. Без имени — \
оглавление реестра целиком.

Это дверь прогрессивного раскрытия: полная схема всех опов стоит десятки \
тысяч токенов на каждый список инструментов, а один контракт — сотни."""


def tools() -> tuple[dict[str, Any], ...]:
    """The whole surface, in a FIXED order.

    Returns new dictionaries on every call ON PURPOSE: a shared mutable
    object would one day get patched in place in one of two branches, and
    the surface would drift apart from itself between two `tools/list`
    calls. The same argument is recorded at
    `schema_gen._node_id_schema`.
    """
    from kir.schema_dedup import lift_property_defs

    program = _program_schema()
    program_ref = _program_ref()
    versions = _versions_enum()
    return (
        {
            "name": f"{PREFIX}_author",
            "description": _AUTHOR_DESC,
            "input_schema": {
                "type": "object",
                "additionalProperties": False,
                "required": ["program_py"],
                "properties": {
                    "program_py": {
                        "type": "string",
                        "description": (
                            "Исходник питона, собирающий программу KIR. "
                            "Последнее выражение или переменная `program` — "
                            "то, что уедет в IR."),
                        "minLength": 1,
                    },
                    "params": {
                        "type": "object",
                        "description": (
                            "Значения, которые скрипт читает именем `params`. "
                            "Подпись параметров едет в квитанцию отдельно от "
                            "подписи исходника: так «двинули ползунок» "
                            "отличается от «переписали определение»."),
                    },
                },
            },
        },
        {
            "name": f"{PREFIX}_spec",
            "description": _SPEC_DESC,
            "input_schema": {
                "type": "object",
                "additionalProperties": False,
                "properties": {
                    "op": {
                        "type": "string",
                        "description": (
                            "Имя операции, например `create_wall`. "
                            "Без него — оглавление реестра."),
                        "maxLength": 128,
                    },
                },
            },
        },
        {
            "name": f"{PREFIX}_compile",
            "description": _COMPILE_DESC,
            "input_schema": lift_property_defs({
                "type": "object",
                "additionalProperties": False,
                "required": ["program"],
                "properties": {
                    "program": program,
                    "versions": {
                        "type": "array",
                        "description": (
                            "Версии Ревита. По умолчанию — все поставленные."),
                        "items": {"type": "string", "enum": versions},
                        "minItems": 1,
                        "maxItems": len(versions),
                    },
                    "out_dir": {
                        "type": "string",
                        "description": (
                            "Каталог, куда положить C# файлами по версиям. "
                            "Без него текст возвращается ВСТРОЕННЫМ, а если он "
                            "длиннее предела — ответ называет предел и просит "
                            "этот каталог. Обрезки не бывает. В stdio путь и "
                            "перезапись работают как раньше. HTTP: путь внутри "
                            "--out-root (относительные пути — от этого корня), "
                            "только новые файлы, без перехода по symlink; "
                            "без безопасных directory-handle API файловый вывод "
                            "отказан, inline доступен."),
                        "maxLength": 4096,
                    },
                },
            }, "program"),
        },
        {
            "name": f"{PREFIX}_rehearse",
            "description": _REHEARSE_DESC,
            "input_schema": {
                "type": "object",
                "additionalProperties": False,
                "required": ["program"],
                "properties": {"program": program_ref},
            },
        },
        {
            "name": f"{PREFIX}_open",
            "description": _OPEN_DESC,
            "input_schema": {
                "type": "object",
                "additionalProperties": False,
                "properties": {},
            },
        },
        {
            "name": f"{PREFIX}_write",
            "description": _WRITE_DESC,
            "input_schema": {
                "type": "object",
                "additionalProperties": False,
                "required": ["building", "program"],
                "properties": {
                    "building": {
                        "type": "string",
                        "description": ("Ручка, выданная `kir_open`. "
                                        "Вид «bld_…»."),
                        "pattern": "^bld_[0-9a-f]{16}$",
                    },
                    "program": program_ref,
                },
            },
        },
        {
            "name": f"{PREFIX}_preview",
            "description": _PREVIEW_DESC,
            # 🔴 A REFERENCE TO THE APP (SEP-2133,
            # `io.modelcontextprotocol/ui`). A host that has negotiated
            # the extension PRELOADS this document even before the call;
            # a host without the extension simply does not read the
            # field, and the tool's result stays the same. The
            # degradation is not "just in case," it is by construction:
            # the app adds nothing to the CONTENT of the response.
            "meta": {"ui": {"resourceUri": _app.APP_URI}},
            "input_schema": {
                "type": "object",
                "additionalProperties": False,
                "required": ["program"],
                "properties": {
                    "program": program_ref,
                    "levels": {
                        "type": "array",
                        "description": (
                            "Какие этажи рисовать. Молчание — все."),
                        "items": {"type": "string", "maxLength": 128},
                        "maxItems": 64,
                    },
                },
            },
        },
    )


def names() -> tuple[str, ...]:
    """Names in the same order — for the gate and for error messages."""
    return tuple(t["name"] for t in tools())
