"""HTTP client for the C# Revit bridge (BRIDGE_PROTOCOL.md)."""

from __future__ import annotations

import asyncio
import logging
import uuid
from typing import Any, Optional

import httpx

from kir.bridge.models import (
    BridgeError,
    BridgeRequest,
    BridgeResponse,
    ContextResult,
    ExecuteResult,
    ExportViewResult,
    FamilyPassport,
    HighlightResult,
    ImportCadResult,
    PingResult,
    SelectResult,
)

logger = logging.getLogger(__name__)


class BridgeClient:
    """Async HTTP client that talks to the Revit bridge via JSON-RPC."""

    def __init__(self, base_url: str, timeout: float = 5.0, execute_timeout: float = 30.0):
        self._base_url = base_url.rstrip("/")
        self._timeout = timeout
        self._execute_timeout = execute_timeout
        self._connected = False
        self._last_ping: Optional[PingResult] = None
        self._client: Optional[httpx.AsyncClient] = None

    async def _get_client(self) -> httpx.AsyncClient:
        if self._client is None or self._client.is_closed:
            self._client = httpx.AsyncClient(
                base_url=self._base_url,
                # connect capped at 5s: if the Revit plugin is down, fail fast
                # instead of hanging up to bridge_timeout (900s). read stays
                # large for long-running Revit operations.
                timeout=httpx.Timeout(self._timeout, connect=5.0, read=self._execute_timeout),
                headers={"Content-Type": "application/json"},
            )
        return self._client

    async def close(self) -> None:
        if self._client and not self._client.is_closed:
            await self._client.aclose()
            self._client = None

    def _make_request(self, method: str, params: dict[str, Any] | None = None) -> BridgeRequest:
        return BridgeRequest(
            method=method,
            params=params or {},
            id=str(uuid.uuid4()),
        )

    async def _call(self, method: str, params: dict[str, Any] | None = None,
                    timeout: float | None = None) -> dict[str, Any]:
        """Send a JSON-RPC request and return the result dict."""
        req = self._make_request(method, params)
        client = await self._get_client()

        read_t = timeout or self._timeout
        try:
            resp = await client.post(
                "/rpc",
                json=req.model_dump(),
                # connect stays small so a closed Revit plugin fails in ~5s;
                # read uses the (possibly large) per-call timeout for long ops.
                timeout=httpx.Timeout(read_t, connect=min(5.0, read_t)),
            )
            resp.raise_for_status()
            body = resp.json()
        except (httpx.ConnectError, httpx.ConnectTimeout):
            # Revit plugin not listening — surface a clean, user-facing message.
            # This string reaches the LLM tool-result and the end user, so keep
            # it human and actionable rather than a raw httpx error.
            logger.warning("Bridge not reachable on method=%s (Revit plugin not connected)", method)
            raise BridgeError(-32010, "Revit не подключён — откройте плагин KUKAI в Revit")
        except httpx.TimeoutException:
            logger.warning("Bridge timeout on method=%s", method)
            raise BridgeError(-32004, f"Bridge timeout on {method}")
        except httpx.HTTPError as e:
            logger.error("Bridge HTTP error on method=%s: %s", method, e)
            raise BridgeError(-32010, f"Bridge HTTP error: {e}")

        bridge_resp = BridgeResponse.model_validate(body)

        # 🔴 THE ANSWER MUST BE THE ANSWER TO THIS REQUEST (30.08.2026, audit
        # finding F-350). `req.id` is generated by uuid4 right here and was
        # never READ again after sending: an answer to SOMEONE ELSE's
        # request was accepted as one's own. Over HTTP this is rare, but the
        # client survives plugin reconnects, and the protocol is declared as
        # JSON-RPC 2.0, where checking the id is part of the PROTOCOL, not a
        # precaution.
        if bridge_resp.id != req.id:
            raise BridgeError(
                -32012,
                f"ответ моста относится к другому запросу: пришёл id "
                f"{bridge_resp.id!r}, ожидался {req.id!r}")
        if bridge_resp.error is not None and bridge_resp.result is not None:
            # A contradictory envelope. Silently picking one would mean
            # deciding on the bridge's behalf; previously `error` won, and
            # the result vanished without a trace.
            raise BridgeError(
                -32014,
                "конверт несёт и result, и error разом — это не JSON-RPC 2.0, "
                "и решать за мост, что из этого правда, нельзя")

        if bridge_resp.is_error:
            err = bridge_resp.error
            assert err is not None
            raise BridgeError(err.code, err.message, err.data)

        # 🔴 "SUCCESS WITHOUT A BODY" IS NOT AN EMPTY RESULT (30.08.2026,
        # F-350 carries F-349 through to the shared seam). Previously
        # `result or {}` stood here, and the absence of a body turned into
        # `{}` for ALL methods; each of them then failed later with an
        # uninformative `ValidationError` instead of a named refusal.
        #
        # A refusal cannot fire on a legitimate input, and this is
        # MEASURED: ALL eight response models in this file have at least
        # one MANDATORY field (`PingResult`, `ContextResult`,
        # `ExecuteResult`, `SelectResult`, `HighlightResult`,
        # `ExportViewResult`, `ImportCadResult`, `FamilyPassport`), meaning
        # an empty body is not accepted by a single method. The fix changes
        # the KIND of refusal, not the set of accepted responses.
        #
        # A NEW MODEL MUST HAVE AT LEAST ONE MANDATORY FIELD — otherwise it
        # would inherit the same muteness; this is guarded by
        # `test_bridge_result_models_refuse_emptiness.py`.
        if bridge_resp.result is None:
            raise BridgeError(
                -32011,
                "мост ответил успехом БЕЗ ТЕЛА — это не пустой результат: "
                "успех без тела не отвечает на вопрос, который был задан")
        return bridge_resp.result

    # --- Public API ---

    @property
    def connected(self) -> bool:
        return self._connected

    @property
    def last_ping(self) -> Optional[PingResult]:
        return self._last_ping

    async def ping(self) -> PingResult:
        """Health check — returns bridge status."""
        result = await self._call("ping")
        ping_result = PingResult.model_validate(result)
        self._connected = True
        self._last_ping = ping_result
        return ping_result

    async def context(self) -> ContextResult:
        """Get model context for LLM system prompt."""
        result = await self._call("context", timeout=10.0)
        return ContextResult.model_validate(result)

    async def family_inspect(self) -> FamilyPassport:
        """Rich read-only inventory of the active family document.

        Used by the `inspect_family` LLM tool in family-editor mode. Returns
        a snapshot of category/parameters/types/solids/refs/labeled dims/
        materials so Gemini can compose tool calls aware of current state.

        Safe on family docs (no project-only API access — same defensive
        try/catch pattern as Collect() V1).

        🔴 AN EMPTY RESULT IS NOT AN EMPTY FAMILY (29.08.2026, F-349).
        `_call` returns `bridge_resp.result or {}`, meaning "success with no
        body" and "success with an empty body" arrive here as IDENTICAL.
        Parsing that into a passport would mean telling the model "inspected,
        no failures, nothing inside" — about a document nobody looked at.
        """
        # Slightly longer timeout — passport walks several collectors
        result = await self._call("family_inspect", timeout=15.0)
        if not result:
            raise BridgeError(
                -32011,
                "осмотр семейства не вернул результата — это НЕ значит, что "
                "семейство пустое: мост ответил успехом без тела")
        return FamilyPassport.model_validate(result)

    async def execute(self, code: str, timeout_ms: int = 30000) -> ExecuteResult:
        """Execute C# code inside Revit."""
        result = await self._call(
            "execute",
            {"code": code, "timeout_ms": timeout_ms},
            timeout=max(timeout_ms / 1000 + 5, self._execute_timeout),
        )
        return ExecuteResult.model_validate(result)

    async def select(self, element_ids: list[int]) -> SelectResult:
        """Select elements in Revit viewport."""
        result = await self._call("select", {"element_ids": element_ids})
        return SelectResult.model_validate(result)

    async def highlight(
        self,
        element_ids: list[int],
        color: dict[str, int] | None = None,
        clear_previous: bool = True,
    ) -> HighlightResult:
        """Highlight elements with color override."""
        params: dict[str, Any] = {
            "element_ids": element_ids,
            "color": color or {"r": 255, "g": 0, "b": 0},
            "clear_previous": clear_previous,
        }
        result = await self._call("highlight", params)
        return HighlightResult.model_validate(result)

    async def export_view(self, filename: str = "kukai_export.png", format: str = "png") -> ExportViewResult:
        """Export the current Revit view to an image file."""
        result = await self._call("export_view", {"filename": filename, "format": format})
        return ExportViewResult.model_validate(result)

    async def import_cad(self, file_path: str) -> ImportCadResult:
        """Import a CAD file (DWG/DXF) into the current Revit document."""
        result = await self._call("import_cad", {"file_path": file_path})
        return ImportCadResult.model_validate(result)

    # --- Heartbeat ---

    async def check_connection(self) -> bool:
        """Attempt a ping; update connected status. Returns True if connected."""
        try:
            await self.ping()
            self._connected = True
            return True
        except (BridgeError, Exception):
            self._connected = False
            self._last_ping = None
            return False

